### ISSUE TITLE
Amplify Gen 2 does not seems to work out of the box.

### ISSUE THREAD

**Issue by latheeshvm** [aws-amplify/amplify-backend#1022]
### Environment information

```plain text
System:
  OS: Windows 11 10.0.22631
  CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Memory: 16.91 GB / 31.84 GB
Binaries:
  Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
  Yarn: undefined - undefined
  npm: 10.2.5 - C:\Program Files\nodejs\npm.CMD
  pnpm: undefined - undefined
NPM Packages:
  @aws-amplify/backend: 0.12.1
  @aws-amplify/backend-cli: 0.11.1
  aws-amplify: 6.0.16
  aws-cdk: 2.127.0
  aws-cdk-lib: 2.127.0
  typescript: 5.3.3
AWS environment variables:
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
  AWS_STS_REGIONAL_ENDPOINTS = regional
No CDK environment variables
```

### Description

When attempting to deploy a Next.js application using AWS Amplify, I encountered multiple issues across different versions of the setup. Initially, with an older setup of Amplify and Next.js, there were problems out of the box, particularly related to image optimization which required significant changes to the codebase to work around limitations that do not exist in alternative deployment solutions like Vercel.

After upgrading to the latest versions of Next.js and AWS Amplify (referred to as GEN 2 in the context of this report), I aimed for a straightforward deployment with minimal to no configuration changes. Despite this approach, I encountered a critical issue related to the Node.js version compatibility.

Steps to Reproduce

1. Install the latest versions of Next.js and AWS Amplify.
2. Set up a basic Next.js application without any modifications specific to Amplify.
3. Attempt to deploy the application using AWS Amplify with the default build settings.
4. Encounter the Node.js version compatibility error.
5. Change the Node version to 20 in the build settings and attempt to redeploy.

Expected Behavior
The deployment process should recognize and use the specified Node.js version setting from the Amplify build settings, allowing for a successful build and deployment of the Next.js application.

Actual Behavior
Despite specifying a Node.js version (20) that meets the requirements for Next.js, the deployment process fails, indicating that it's using Node.js 18.13.0 and requiring a version >= v18.17.0. This occurs even after explicitly setting the Node version to 20 in the build settings.

Error Message

```
You are using Node.js 18.13.0. For Next.js, Node.js version >= v18.17.0 is required.
2024-02-13T02:53:43.688Z [ERROR]: !!! Build failed
```

Environment
Next.js Version: latest
Node.js Version (Attempted): 18.13.0 (default), 20 (specified in build settings)

This issue highlights a broader concern regarding the clarity and documentation of supported versions for dependencies, particularly Node.js, within the AWS Amplify environment for Next.js applications**. A clearer specification of compatible versions** and better handling of user-specified versions in the build settings would significantly improve the developer experience.

**Comment by ykethan** [comment]
Hey @latheeshvm, thank you for reaching out. you will need to switch the build image to use `al:2023` that supports Node.js versions 18 and 20. Refer to the [documentation](https://docs.amplify.aws/gen2/start/quickstart/nextjs-pages-router/#connect-branch-in-the-amplify-console) providing this information

**Comment by latheeshvm** [comment]
@ykethan That worked well. Thank you.

**Comment by ykethan** [comment]
@latheeshvm thank you for the confirmation. Closing the issue, do reach out to us if you encounter any issues.
