### ISSUE TITLE
Empty backend.data.resources.cfnResources.cfnTables object 

### ISSUE THREAD

**Issue by exai-sukh** [aws-amplify/amplify-backend#1030]
### Environment information

```plain text
System:
  OS: macOS 14.3
  CPU: (10) arm64 Apple M1 Pro
  Memory: 651.58 MB / 32.00 GB
  Shell: /bin/zsh
Binaries:
  Node: 20.1.0 - /usr/local/bin/node
  Yarn: 1.22.19 - /opt/homebrew/bin/yarn
  npm: 9.6.4 - /usr/local/bin/npm
  pnpm: undefined - undefined
NPM Packages:
  @aws-amplify/backend: 0.12.0
  @aws-amplify/backend-cli: 0.11.1
  aws-amplify: 6.0.15
  aws-cdk: Not Found
  aws-cdk-lib: Not Found
  typescript: 5.3.3
AWS environment variables:
  AWS_STS_REGIONAL_ENDPOINTS = regional
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
No CDK environment variables
```

### Problem Summary:

In the `amplify/data/resources.ts` file, I defined a schema which provisions DynamoDB tables. However, there is an issue I observed in the `amplify/backend.ts` file:

**Expected Behavior:** 
Both `backend.data.resources.cfnResources.cfnTables` and `backend.data.resources.amplifyDynamoDbTables` should contain data on tables defined in `amplify/data/resources.ts`.

**Actual Behavior:** 
The `backend.data.resources.cfnResources.cfnTables` object is empty, while `backend.data.resources.amplifyDynamoDbTables` contains data on tables defined in `amplify/data/resources.ts`.

### Impact and Context:

My goal is to define global secondary indices using Amplify to allow for querying DynamoDB in downstream processes where the use of AppSync is not optimal. Although `backend.data.resources.amplifyDynamoDbTables` lacks a method to define GSIs, it seems that this can be achieved using `backend.data.resources.cfnResources.cfnTables`.

**Comment by ykethan** [comment]
Hey @exai-sukh, this is currently being on https://github.com/aws-amplify/amplify-category-api/issues/2137.
Closing the issue as duplicate, do subscribe to the linked issue for new update.
