### ISSUE TITLE
The given region has not been bootstrapped.

### ISSUE THREAD

**Issue by stuart-robinson** [aws-amplify/amplify-backend#1031]
### Environment information

```plain text
System:
  OS: macOS 14.3.1
  CPU: (8) arm64 Apple M2
  Memory: 123.14 MB / 16.00 GB
  Shell: /bin/zsh
Binaries:
  Node: 18.17.0 - ~/.nvm/versions/node/v18.17.0/bin/node
  Yarn: 1.22.19 - /opt/homebrew/bin/yarn
  npm: 9.6.7 - ~/.nvm/versions/node/v18.17.0/bin/npm
  pnpm: undefined - undefined
NPM Packages:
  @aws-amplify/backend: 0.12.1
  @aws-amplify/backend-cli: 0.11.1
  aws-amplify: 6.0.16
  aws-cdk: 2.128.0
  aws-cdk-lib: 2.128.0
  typescript: 5.3.3
AWS environment variables:
  AWS_STS_REGIONAL_ENDPOINTS = regional
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
No CDK environment variables
```

### Description

I run 
`npx amplify sandbox --profile my-aws-profile`
On the cmd line I get 
`The given region has not been bootstrapped. Sign in to console as a Root user or Admin to complete the bootstrap process and re-run the amplify sandbox command.` 

But in the web console that I get directed to it looks like the sandbox has been bootstrapped just fine
![image](https://github.com/aws-amplify/amplify-backend/assets/1536931/54a88a85-e5d7-4c2c-a6b6-2f8b15c6ee90)

**Comment by edwardfoyle** [comment]
Hi @stuart-robinson, can you double check that the region configured for `my-aws-profile` is the same as the region that shows it's been bootstrapped in the console?

Also, are you using the `AWS_DEFAULT_REGION` environment variable by any chance? We have [this issue](https://github.com/aws-amplify/amplify-backend/issues/965) tracking some inconsistencies between using `AWS_DEFAULT_REGION` and `AWS_REGION`. `AWS_REGION` is the environment variable that should be used to ensure consistency

**Comment by ykethan** [comment]
@stuart-robinson following up on this, were you able to run the sandbox?

**Comment by ykethan** [comment]
Closing the issue due to inactivity, do reach out to us if you require any further assistance.

**Comment by droyuki** [comment]
For those who may encounter this issue, I ran into it as well and finally resolved it by manually running the bootstrap command: `npx aws-cdk@latest bootstrap aws://<your-aws-account-id>/<your-aws-region>`

**Comment by michi88** [comment]
Ran into the same issue. I did not have the CDKToolkit cloudformation template applied, which indeed was fixed by running `npx aws-cdk@latest bootstrap aws://<your-aws-account-id>/<your-aws-region>` (thanks droyuki) but the UI said it was setup correctly and I can close the browser. 

I also didn't encounter that I needed to bootstrap the account when following the quick start docs here: https://docs.amplify.aws/react-native/start/quickstart/

Very confusing...

CC @ykethan

**Comment by manosalamoda** [comment]
> Ran into the same issue. I did not have the CDKToolkit cloudformation template applied, which indeed was fixed by running `npx aws-cdk@latest bootstrap aws://<your-aws-account-id>/<your-aws-region>` (thanks droyuki) but the UI said it was setup correctly and I can close the browser.
> 
> I also didn't encounter that I needed to bootstrap the account when following the quick start docs here: https://docs.amplify.aws/react-native/start/quickstart/
> 
> Very confusing...
> 
> CC @ykethan

I love you man, this unblock me, thanks
