### ISSUE TITLE
How to destroy main stack

### ISSUE THREAD

**Issue by truefalse10** [aws-amplify/amplify-backend#1042]
### Environment information

```plain text
NPM Packages:
  @aws-amplify/backend: 0.12.1
  @aws-amplify/backend-cli: 0.11.1
  aws-amplify: 6.0.16
  aws-cdk: 2.128.0
  aws-cdk-lib: 2.128.0
  typescript: 5.3.3
```

### Description

Hi there,

not sure if this is a bug report or a feature request. My production stack can not be updated anymore and I would like to destroy it and redeploy the project (new sandbox stacks have no deployment issues). Hitting the "redeploy" button only brings me to the same "ROLLBACK_COMPLETE" state.
There seems to be no command like `npx amplify delete` anymore. How can I destroy my non-sandbox stack?

**Comment by blinkdaffer** [comment]
you can delete your stack from cloud formation directly or from amplify dashboard. alternatively just delete the rollback status stacks from cloud formation and you might be able to deploy again.

**Comment by ykethan** [comment]
@truefalse10 adding to the information provided by @blinkdaffer, removing a branch on the Amplify console under the `App Setting` -> `Repository Setting` should disconnect the branch and delete the resources.

**Comment by ykethan** [comment]
@truefalse10 following up on this issue, were you able to redeploy the project?

**Comment by ykethan** [comment]
Closing the issue due to inactivity, do reach out to us if you require any further assistance.
