### ISSUE TITLE
Document function environment variables and secrets

### ISSUE THREAD

**Issue by FirstSanny** [aws-amplify/amplify-backend#1052]
### Environment information

```plain text
System:
  OS: macOS 13.0.1
  CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Memory: 1.16 GB / 16.00 GB
  Shell: /bin/sh
Binaries:
  Node: 21.0.0 - /usr/local/bin/node
  Yarn: 1.22.21 - /usr/local/bin/yarn
  npm: 10.2.2 - /usr/local/bin/npm
  pnpm: 8.15.3 - /usr/local/bin/pnpm
NPM Packages:
  @aws-amplify/backend: 0.12.1
  @aws-amplify/backend-cli: 0.11.1
  aws-amplify: 6.0.17
  aws-cdk: 2.129.0
  aws-cdk-lib: 2.129.0
  typescript: 5.3.3
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!                                                                                                                      !!
!!  This software has not been tested with node v21.0.0.                                                                !!
!!  Should you encounter odd runtime issues, please try using one of the supported release before filing a bug report.  !!
!!                                                                                                                      !!
!!  This software is currently running on node v21.0.0.                                                                 !!
!!  As of the current release of this software, supported node releases are:                                            !!
!!  - ^20.0.0 (Planned end-of-life: 2026-04-30)                                                                         !!
!!  - ^18.0.0 (Planned end-of-life: 2025-04-30)                                                                         !!
!!                                                                                                                      !!
!!  This warning can be silenced by setting the JSII_SILENCE_WARNING_UNTESTED_NODE_VERSION environment variable.        !!
!!                                                                                                                      !!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
AWS environment variables:
  AWS_STS_REGIONAL_ENDPOINTS = regional
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
No CDK environment variables
```

### Description

The secrets arent getting loaded into my app. It works if I just hardcode them (thats how I figured, it's something about the secrets). It is also worth to mention, that if I wouldn't double cast them, typescript would throw an error, because it is recognising it as an object of type `BackendSecret`.

This is the code: 

```typescript
import { secret } from "@aws-amplify/backend";

class ShopifyClient {
  private shopifyGQLClient: GraphqlClient;
  constructor() {
    // const shopifyHostName = <string>process.env.SHOPIFY_HOST_NAME;

    const shopifyApiKey = <string>(<unknown>secret("SHOPIFY_API_KEY"));
    console.log(shopifyApiKey);
    const shopifyApiSecretKey = <string>(
      (<unknown>secret("SHOPIFY_API_SECRET_KEY"))
    );
    const shopifyAdminApiAccessToken = <string>(
      (<unknown>secret("SHOPIFY_ADMIN_API_ACCESS_TOKEN"))
    );
```
I added for alle branches and my sandbox. But no luck...
![image](https://github.com/aws-amplify/amplify-backend/assets/23708333/41357950-bdc2-44e1-bdd3-736d686102d0)

**Comment by edwardfoyle** [comment]
Hi @FirstSanny, the `secret('name')` pattern can only be used in specific places within a backend. It cannot be used to resolve secrets in arbitrary locations within CDK code. Specifically, it can be used [within `defineAuth` to configure social providers](https://docs.amplify.aws/gen2/build-a-backend/auth/add-social-provider/#configure-social-sign-in-backend) and it can be used within `defineFunction` to to specify secret environment variables.

Can you explain more about where you are trying to use the secrets and what your use case is?

**Comment by FirstSanny** [comment]
Hello @edwardfoyle ,

thanks for your reply. Currently this class is defined in the amplify/clients folder and will be globally assigned to an default instance like this: 
![image](https://github.com/aws-amplify/amplify-backend/assets/23708333/6cc505db-fc1f-43dd-9592-8459c439c404)

The issue came, when using this instance, but is it called inside of an defineFunction context. The finction is getting exported with the data export of the resource.ts 
![image](https://github.com/aws-amplify/amplify-backend/assets/23708333/e90d282a-8ab6-4816-ada5-6722241773d7)
and used like this.
![image](https://github.com/aws-amplify/amplify-backend/assets/23708333/e6b8e311-a71a-4f44-a216-f75ebc9c9416)

We can try to fetch the credentials inside of the handler function and pass them to the instance from there. Do you think this would work?

**Comment by FirstSanny** [comment]
Tried to fetch it directly in the handler and commented out all the others. Still not working and throwing errors

Code change:
![image](https://github.com/aws-amplify/amplify-backend/assets/23708333/b235da8b-88b5-4e7a-91c4-a3d153aa04b4)

Error:
![image](https://github.com/aws-amplify/amplify-backend/assets/23708333/38babced-9f56-4803-8abf-9dc96efd2cb0)

**Comment by edwardfoyle** [comment]
@FirstSanny thanks for the additional context. The way you would do this is to define a secret environment variable in your function like so:
```ts
defineFunction({
  entry: './some/path.ts',
  environment: {
    SHOPIFY_API_KEY: secret('SHOPIFY_API_KEY')
  }
})
```
Then in your function code, you can use `SHOPIFY_API_KEY` as a normal environment variable:
```
export const handler = async () => {
  process.env.SHOPIFY_API_KEY // this will be the value of the API key when the lambda runs
}
```
We need to update our docs to describe this new behavior!

**Comment by FirstSanny** [comment]
That worked. Thanks.

**Comment by chucklam** [comment]
@edwardfoyle I'm trying something similar, but I want to access the secrets inside the Next.js API routes. Is there any easy way to do that? I imagine I can rewrite it as a Function fronted by an API Gateway and follow your example above, but hoping for a simpler solution.

**Comment by josefaidt** [comment]
Hey @chucklam you can manage secrets for branches from the Amplify console
![image](https://github.com/aws-amplify/amplify-backend/assets/5033303/7d1dedd4-4a7f-45d3-8ff5-e93a42e7d790)
https://docs.amplify.aws/gen2/deploy-and-host/fullstack-branching/secrets-and-vars

then you can `echo` to a dotenv file for your Next.js app

**Comment by jbp35** [comment]
> @FirstSanny thanks for the additional context. The way you would do this is to define a secret environment variable in your function like so:
> 
> ```ts
> defineFunction({
>   entry: './some/path.ts',
>   environment: {
>     SHOPIFY_API_KEY: secret('SHOPIFY_API_KEY')
>   }
> })
> ```
> 
> Then in your function code, you can use `SHOPIFY_API_KEY` as a normal environment variable:
> 
> ```ts
> export const handler = async () => {
>   process.env.SHOPIFY_API_KEY // this will be the value of the API key when the lambda runs
> }
> ```
> 
> We need to update our docs to describe this new behavior!

Is it supposed to work within the sandbox? I am using npx amplify sandbox secret XXXX to configure my secret but it only works when deI deploy the branch. Thanks.

**Comment by chucklam** [comment]
> Hey @chucklam you can manage secrets for branches from the Amplify console https://docs.amplify.aws/gen2/deploy-and-host/fullstack-branching/secrets-and-vars
> 
> then you can `echo` to a dotenv file for your Next.js app

I have set the secrets from the Amplify console. Not clear to me how to `echo` to a dotenv file though. I know I [could](https://docs.amplify.aws/gen2/deploy-and-host/fullstack-branching/secrets-and-vars/#access-environment-variables) do the following if I set `NEXTAUTH_SECRET` as an environment variable. But if I set it as a secret then the `echo` command isn't picking it up.

```yaml
build:
  commands:
    - echo "NEXTAUTH_SECRET=$NEXTAUTH_SECRET" >> .env
    - npm run build
```

**Comment by bnova-stefan** [comment]
> Hey @chucklam you can manage secrets for branches from the Amplify console ![image](https://private-user-images.githubusercontent.com/5033303/311391520-7d1dedd4-4a7f-45d3-8ff5-e93a42e7d790.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NzQxMjUsIm5iZiI6MTcxMDc3MzgyNSwicGF0aCI6Ii81MDMzMzAzLzMxMTM5MTUyMC03ZDFkZWRkNC00YTdmLTQ1ZDMtOGZmNS1lOTNhNDJlN2Q3OTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMThUMTQ1NzA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzgzYjI4NTE1YTU3YTBmYTcyYWFkYjJmNDBmMTRmYWY0ZjA3NjY5YWM1N2NjMmQwMTE5MWNlMjYzZjI4ODdmOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.3zNv5eiUO7brU4dccfWb1h67O9p7ibvMJF6TnmaYbOo) https://docs.amplify.aws/gen2/deploy-and-host/fullstack-branching/secrets-and-vars
> 
> then you can `echo` to a dotenv file for your Next.js app

Hey @chucklam, @jbp35 
I have the same problem. I try to use a secret in my route. So what I tried it is the following: 

I have defined the secrets in the amplify console:
![image](https://github.com/aws-amplify/amplify-backend/assets/17455553/8c0242f3-1928-4395-b5e5-ee10e900604d)

And then I try to read the secrets and write them to a dotenv file
```yaml
build:
  commands:
    - echo "KEYCLOAK_SECRET=$(echo $secrets | jq -r '.KEYCLOAK_SECRET')" >> .env
```

But if I look at the .env file the I get just `null` as value:
![Screenshot 2024-03-18 at 16 14 59](https://github.com/aws-amplify/amplify-backend/assets/17455553/85d56c03-9598-49ac-8f28-695567cbf8cd)

Do you have any solution for this in the meantime?

Many thanks and regards, 
Stefan

**Comment by chucklam** [comment]
@bnova-stefan @josefaidt In fact if I just look at `process.env.secrets`, I get back an empty json object `{}`. Maybe I need to configure something to have the secrets show up there?

> ```bash
> echo $secrets
> ```

**Comment by campbellgoe** [comment]
`process.env.secrets` seems to be empty if you didn't properly specify the app id and backend name, and seems to only be available during build time, not run time.

**Comment by owlyowl** [comment]
Did anyone get the echo secrets to a .env file to work?

**Comment by taraspos** [comment]
> @bnova-stefan @josefaidt In fact if I just look at `process.env.secrets`, I get back an empty json object `{}`. Maybe I need to configure something to have the secrets show up there?
> 
> > ```shell
> > echo $secrets
> > ```

> @owlyowl  Did anyone get the echo secrets to a .env file to work?

If you look at Amplify build logs, you will see log line like this:

```
2024-11-08T18:50:07.430Z [INFO]: ---- Setting Up SSM Secrets ----
2024-11-08T18:50:07.430Z [INFO]: SSM params {"Path":"/amplify/<app_id>/main/","WithDecryption":true}
2024-11-08T18:05:21.329Z [WARNING]: !Failed to set up process.env.secrets
```

`[WARNING]: !Failed to set up process.env.secrets` is happening if your IAM Service role doesn't have permissions to `ssm: GetParametersByPath` for the `/amplify/<app_id>/` path. Once you configure this your IAM role, this warning should disappear and amplify will start reading them.

However, what's even more confusing, if you configure secrets through AWS Amplify Gen2 console as mentioned in the documentation[^1].
[^1]: https://docs.amplify.aws/react/deploy-and-host/fullstack-branching/secrets-and-vars/

It actually creates Parameters by path like `/amplify/<app-id>/main-branch-<some-unknown-id>/<secret-name>`.
Which is super confusing, however if you follow gen1 documentation[^2] it will work and manually create secrets in SSM Parameter store by path `/amplify/<app_id>/main/` it will work.

[^2]: https://docs.aws.amazon.com/amplify/latest/userguide/environment-secrets.html#set-environment-secrets

Also, see this super helpful comment:
- https://github.com/aws-amplify/amplify-hosting/issues/3348#issuecomment-1476044689

**Comment by swbergmann** [comment]
> @FirstSanny thanks for the additional context. The way you would do this is to define a secret environment variable in your function like so:
> 
> ```ts
> defineFunction({
>   entry: './some/path.ts',
>   environment: {
>     SHOPIFY_API_KEY: secret('SHOPIFY_API_KEY')
>   }
> })
> ```
> 
> Then in your function code, you can use `SHOPIFY_API_KEY` as a normal environment variable:
> 
> ```ts
> export const handler = async () => {
>   process.env.SHOPIFY_API_KEY // this will be the value of the API key when the lambda runs
> }
> ```
> 
> We need to update our docs to describe this new behavior!

Hi @edwardfoyle  please can you provide more details to your suggested solution:
1. In which files is the code you posted?
2. Why does it work like you suggested (what is the connection, to what documentation are you referring)?

I cannot reproduce your solution and I need to access secrets in my nextJS application typescript back end. There is NO reproducible solution/tutorial anywhere online.

Thank you!

**Comment by juanRabaa** [comment]
I need to access a secret contain a bitbucket app token to update commits build status, but it seems that it can't be done based on what I've read here. Nowhere in the docs is the limitation of secrets explained, but the difference between them and env variables in regards to privacy is enfacized, so anyone would try to handle this kind of data as secrets with no success.
I guess there is a reason for such limitation to exists, but it needs to be documented. If env variables and secrets cannot be used in the same scopes, it should be noted in https://docs.amplify.aws/react/deploy-and-host/fullstack-branching/secrets-and-vars

**Comment by 2bitburrito** [comment]
Bit of a workaround but after being stuck on this for 3 days I have opted to using SSM Parameter store and caching the results. 

You can set them simply in the CLI with the below command:
```bash
aws ssm put-parameter \
  --name "/<project-name>/<secret-key>" \
  --value "<secret-value>" \
  --type "SecureString"

```

```typescript
import { SSMClient, GetParameterCommand } from '@aws-sdk/client-ssm';

type ssmValues =
  "API_KEY" |
  "API_BASE_URL"

const secretCache: Record<ssmValues, string | null> = {
  API_KEY: null,
  API_BASE_URL: null,
};

async function getSecretValue(value: ssmValues) {
  'use server'

  if (secretCache[value]) {
    return secretCache[value]
  }

  const client = new SSMClient({ region: "us-west-1" });

  const command = new GetParameterCommand({
    Name: `"/<project-name>/<secret-value>"`,
    WithDecryption: true,
  });

  const { Parameter } = await client.send(command);
  const secretValue = Parameter?.Value;

  if (!secretValue) {
    return
  }

  secretCache[value] = secretValue

  return secretValue
}

```
It obviously incurrs a small fee (I beleive its something like $0.05 per secret) but at least it works. 


AWS please could you work on a better solution for storing secrets. I don't want to be forced to use lambdas - i just want to upload my secrets and have them accessable at runtime for server code.
