### ISSUE TITLE
add support for one-time sandbox deployment with `npx amplify sandbox --once`

### ISSUE THREAD

**Issue by johnpc** [aws-amplify/amplify-backend#1062]
### Environment information

```plain text
N/A
```

### Description

I would like to have a flag available like `npx amplify sandbox --once` flag that prevents the watcher from being enabled.

I mostly would use it when writing repro steps for issues I cut. Or setup instructions in a README on how to initially set up your dev environment. It could also be useful for testing the `sandbox` command itself. These are some examples, but I'm sure there are other places where a deployment needs to happen but only once.

**Comment by josefaidt** [comment]
marking as a feature request for sandbox to have some command for a one-shot sandbox deployment. another idea would be 
```
npx amplify sandbox deploy
```
(to somewhat align with `pipeline-deploy`)

**Comment by edwardfoyle** [comment]
Some other options discussed offline:

`npx amplify deploy sandbox` single deployment of sandbox
`npx amplify deploy sandbox --watch` start the sandbox file watcher
`npx amplify deploy branch` equivalent to the current `pipeline-deploy` command
`amplify deploy [--watch] [--app-id] [--branch]` presence or absence of app-id and branch determines whether it's a sandbox deploy or not

One other thing to consider in all of this is where do the other sandbox subcommands go? (secret management and deleting)
