### ISSUE TITLE
Schema fields helpers types are gone

### ISSUE THREAD

**Issue by JJK801** [aws-amplify/amplify-backend#1069]
### Environment information

```plain text
System:
  OS: macOS 13.3.1
  CPU: (10) arm64 Apple M2 Pro
  Memory: 153.45 MB / 16.00 GB
  Shell: /bin/zsh
Binaries:
  Node: 20.0.0 - ~/.nvm/versions/node/v20.0.0/bin/node
  Yarn: 1.22.19 - ~/.nvm/versions/node/v20.0.0/bin/yarn
  npm: 9.6.4 - ~/.nvm/versions/node/v20.0.0/bin/npm
  pnpm: undefined - undefined
NPM Packages:
  @aws-amplify/backend: Not Found
  @aws-amplify/backend-cli: Not Found
  aws-amplify: Not Found
  aws-cdk: Not Found
  aws-cdk-lib: Not Found
  typescript: Not Found
AWS environment variables:
  AWS_STS_REGIONAL_ENDPOINTS = regional
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
No CDK environment variables
```

### Description

Hi,

I'm in trouble with my typing since i aimed to clean my dependencies, i probably did something wrong but i can't figure what 🤔 

# Issue

When importing the `a` data field builder from `@aws-amplify/backend@0.12.1` (which uses `@aws-amplify/data-schema@0.12.14`) some methods are untyped (VSCode shows typing in autocomplete, but note in the code).

```
import { a } from '@aws-amplify/backend';

a.string() // <= Type: string(): any
```

it seems that some types (like `ModelField`, `ModelType`) cannot be accessed.

I tried installing `@aws-amplify/data-schema@0.13.6`, and types were working (when importing directly, not via backend), but TS complained with as TS2742 error, probably because of the version mismatch with `@aws-amplify/backend`.

Any idea to solve this ? (i tried some combination of upgrade/downgrade of versions, but nothing worked)

**Comment by JJK801** [comment]
I upgraded to backend@0.13.0-beta.3 and it works again (still not working on 0.12.1)

**Comment by josefaidt** [comment]
Hey @JJK801 :wave: thanks for raising this! As you have mentioned, upgrading to the latest `@beta` release will resolve the issue. To track this fix's progress to `@latest` I'll mark this as a bug and keep the issue open 🙂

**Comment by arundna** [comment]
Closing this out as the fix is already in `@beta`.
