### ISSUE TITLE
unable to update function source code during sandbox

### ISSUE THREAD

**Issue by josefaidt** [aws-amplify/amplify-backend#1074]
### Environment information

```plain text
System:
  OS: macOS 14.3.1
  CPU: (10) arm64 Apple M1 Pro
  Memory: 87.30 MB / 32.00 GB
  Shell: /opt/homebrew/bin/fish
Binaries:
  Node: 18.10.0 - ~/Library/Caches/fnm_multishells/77574_1680319338649/bin/node
  Yarn: 1.22.19 - ~/Library/Caches/fnm_multishells/77574_1680319338649/bin/yarn
  npm: 8.19.2 - ~/Library/Caches/fnm_multishells/77574_1680319338649/bin/npm
  pnpm: 8.15.4 - ~/Library/Caches/fnm_multishells/77574_1680319338649/bin/pnpm
NPM Packages:
  @aws-amplify/backend: 0.13.0-beta.3
  @aws-amplify/backend-cli: 0.12.0-beta.3
  aws-amplify: 6.0.17
  aws-cdk: 2.130.0
  aws-cdk-lib: 2.130.0
  typescript: 5.3.3
AWS environment variables:
  AWS_PROFILE = josef-gen2
  AWS_REGION = us-east-1
  AWS_STS_REGIONAL_ENDPOINTS = regional
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
No CDK environment variables
```

### Description

I have a Pre Sign Up trigger defined with `defineFunction`:

```ts
// amplify/auth/resource.ts
import { defineAuth, defineFunction } from "@aws-amplify/backend"

const preSignUp = defineFunction({
  entry: "./pre-sign-up.ts",
})

/**
 * Define and configure your auth resource
 * When used alongside data, it is automatically configured as an auth provider for data
 * @see https://docs.amplify.aws/gen2/build-a-backend/auth
 */
export const auth = defineAuth({
  loginWith: {
    email: true,
  },
  userAttributes: {
    birthdate: {
      required: true,
      // mutable: false,
    },
  },
  triggers: {
    preSignUp,
  },
})
```

However if I update my Function handler's code after initial deployment I receive the following error

```
The CloudFormation deployment has failed. Find more information in the CloudFormation AWS Console for this stack.
Caused By: ❌ Deployment failed: AccessDeniedException: Resource is not in the state updateFunctionPropertiesToFinish
```

I am able to work around this issue by removing and re-adding the Function on `defineAuth`

**Comment by josefaidt** [comment]
this popped up again after signing in via SSO and starting sandbox to reconnect with what I was working on
![image](https://github.com/aws-amplify/amplify-backend/assets/5033303/7cfba2a6-92e7-4a0c-a624-29c4b160c48c)

**Comment by josefaidt** [comment]
this is relevant https://github.com/aws/aws-cdk/discussions/23882

**Comment by JJK801** [comment]
👍 i had this issue a few times and it seems deploy anyway, but prevents regeneration of the YML file.

The only way i found were to drop my sandbox.

PS: this doesn't happens on each update

**Comment by renebrandel** [comment]
For me this happens on every update once the issue starts to occur. The only way for me to recover has been to destroy the stack and recreate it via `npx amplify sandbox delete`

**Comment by ykethan** [comment]
The workaround for this is to add a inline policy as follows; which seems to missing on the `AmplifyBackendDeployFullAccess ` policy.

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "states:UpdateStateMachine"
            ],
            "Resource": "*"
        }
    ]
}
```

**Comment by edwardfoyle** [comment]
Did a little more digging here. Looks like it is coming from [this waiter](https://github.com/aws/aws-cdk/blob/8b0dbb7fb8b174c67aa1ef2dc1889afeaf845492/packages/aws-cdk/lib/api/hotswap/lambda-functions.ts#L313) in CDK and the missing permission is [GetFunction](https://docs.aws.amazon.com/lambda/latest/api/API_GetFunction.html)

**Comment by rtpascual** [comment]
[AmplifyBackendDeployFullAccess](https://us-east-1.console.aws.amazon.com/iam/home?region=us-east-1#/policies/details/arn%3Aaws%3Aiam%3A%3Aaws%3Apolicy%2Fservice-role%2FAmplifyBackendDeployFullAccess) was updated with the missing permissions.
