### ISSUE TITLE
Backend deployment stuck on "Extracting Cache"

### ISSUE THREAD

**Issue by JJK801** [aws-amplify/amplify-backend#1100]
### Environment information

```plain text
System:
  OS: macOS 13.3.1
  CPU: (10) arm64 Apple M2 Pro
  Memory: 91.20 MB / 16.00 GB
  Shell: /bin/zsh
Binaries:
  Node: 20.0.0 - ~/.nvm/versions/node/v20.0.0/bin/node
  Yarn: 4.1.0 - ~/.nvm/versions/node/v20.0.0/bin/yarn
  npm: 9.6.4 - ~/.nvm/versions/node/v20.0.0/bin/npm
  pnpm: undefined - undefined
NPM Packages:
  @aws-amplify/backend: Not Found
  @aws-amplify/backend-cli: Not Found
  aws-amplify: Not Found
  aws-cdk: Not Found
  aws-cdk-lib: Not Found
  typescript: 5.3.3
AWS environment variables:
  AWS_STS_REGIONAL_ENDPOINTS = regional
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
No CDK environment variables
```

### Description

Hi,

I'm pushing my app in staging phase and, after some deploys, one got stuck at "Extracting Cache" phase during 30 minutes (normal full deploy time is around 5/10 minutes).

Context:

- The previous deploys were ok
- I pushed 2 times in a few minutes before this happens (maybe its related, due to the 2 deploys planned)

it highlights some issues with the CI/CD:

- This is unclear why this happens, and i've no way to investigate it
- Deploys are not canceled by subsequent deploys (if i push 5 times, should i make 5 deploys ?)
- We are unable to cancel a deploy, it's really bad because in this case i had to destroy the full app (i am not in production yet)

**Comment by blinkdaffer** [comment]
your view additional logs from cloud formation, apart from that on amplify site you view logs for each deployment.

**Comment by JJK801** [comment]
@blinkdaffer yes i can view the logs on Amplify, but the only log i've is that its "Extracting Cache" (which is a pipeline thing) and this happens before i run cloudformation

**Comment by ykethan** [comment]
Hey @JJK801, could you provide us the AppID and the build number?

**Comment by JJK801** [comment]
@ykethan as mentioned, i had to delete my app to kill the build.

App ID was `d1suwdedpi40c` and it was the last running build (another was waiting) of this app

**Comment by Jay2113** [comment]
@JJK801 👋 , since the Amplify app `d1suwdedpi40c` has been deleted we cannot review the logs for it. Are you currently blocked and are observing a similar behavior with a different Amplify app? If yes, can you share the app id?

Here are some insights on the additional queries:
> Deploys are not canceled by subsequent deploys (if i push 5 times, should i make 5 deploys?)

Today, each commit on a git branch will trigger a new Amplify build. To skip an automatic build on a particular commit, you can include the `[skip-cd]` text at the end of the commit message.

> We are unable to cancel a deploy, it's really bad because in this case i had to destroy the full app (i am not in production yet)

We have identified this as a bug and are working on fixing it. In the meantime, as a workaround you can use the `stop-job` [CLI command](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/amplify/stop-job.html) to cancel the ongoing deployment:
```
aws amplify stop-job --app-id {value} --branch-name {value} --job-id {deploy/build #}

Verify if the job has stopped using: aws amplify get-job --app-id {value} --branch-name {value} --job-id {deploy/build #}
```

**Comment by johnpc** [comment]
Out of curiosity, what region was your app in?

**Comment by JJK801** [comment]
@Jay2113 thanks for the commands to stop job.

> Today, each commit on a git branch will trigger a new Amplify build. To skip an automatic build on a particular commit, you can include the [skip-cd] text at the end of the commit message.

yes but in a team flow, we dont want to skip CI/CD, just make the latest build cancels the previous builds. Given a build takes 10 minutes ans i merge 5 PRs  at the same time, i will have 50 minutes building where 10 would be enough.

**Comment by JJK801** [comment]
@johnpc 

> Out of curiosity, what region was your app in?

my app is in eu-west-3 region

**Comment by ykethan** [comment]
@JJK801 wanted to follow up on this issue. Were you able to mitigate the issue?

**Comment by ykethan** [comment]
Closing the issue due to inactivity.
