### ISSUE TITLE
How do I use an existing UserPool?

### ISSUE THREAD

**Issue by asanobm** [aws-amplify/amplify-backend#1118]
### Environment information

```plain text
Debugger attached.
Debugger attached.
System:
  OS: macOS 14.3.1
  CPU: (10) arm64 Apple M1 Max
  Memory: 29.79 GB / 64.00 GB
  Shell: /bin/zsh
Binaries:
  Node: 18.19.0 - ~/.nodebrew/current/bin/node
  Yarn: 1.22.21 - ~/.nodebrew/current/bin/yarn
  npm: 10.2.3 - ~/.nodebrew/current/bin/npm
  pnpm: undefined - undefined
NPM Packages:
  @aws-amplify/backend: 0.13.0-beta.4
  @aws-amplify/backend-cli: 0.12.0-beta.4
  aws-amplify: 6.0.19
  aws-cdk: 2.131.0
  aws-cdk-lib: 2.131.0
  typescript: 5.4.2
Debugger attached.
Debugger attached.
AWS environment variables:
  AWS_STS_REGIONAL_ENDPOINTS = regional
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
No CDK environment variables
```

### Description

How do I use an existing UserPool?

If possible, I would like to use the existing UserPool.

And why can't I set up login with Username?

I don't know why they force email login.

**Comment by edwardfoyle** [comment]
Hi @asanobm, we currently don't support using existing UserPools in `defineAuth`. You could model your existing UserPool using `defineAuth` and then do a [CloudFormation import](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resource-import-existing-stack.html) to replace the UserPool created by `defineAuth` with your existing UserPool.
