### ISSUE TITLE
stream Function logs to terminal during `sandbox`

### ISSUE THREAD

**Issue by josefaidt** [aws-amplify/amplify-backend#1133]
### Environment information

```plain text
n/a
```

### Description

It would be helpful to debug Function executions by streaming logs to the terminal where Sandbox is running. For example, viewing a logs for Cognito triggers during an auth flow:

```console
[sandbox] watching for file changes...
[auth:preSignUp] EVENT {...}
[auth:preSignUp] validating email domain
[auth:preSignUp] successfully validated email domain
[auth:postConfirmation] adding user xxxx to group "EVERYONE"
[auth:postConfirmation] creating UserProfile for user xxx
[auth:postConfirmation] failed to create UserProfile for user xxx
# ...Function stack trace
```

**Comment by AakashKB** [comment]
Is there currently any place the view the logs? I am not able to find on docs.

**Comment by bradyrichmond** [comment]
Looks like this may have been resolved. There is an option when starting sandbox for `--stream-function-logs` per [docs](https://docs.amplify.aws/react/build-a-backend/functions/streaming-logs/).

Just found the [backend pr](https://github.com/aws-amplify/amplify-backend/pull/1492) and the [docs pr](https://github.com/aws-amplify/docs/pull/7841). Both merged in over the last week or so.

**Comment by josefaidt** [comment]
Hey folks, as @bradyrichmond mentioned this is now resolved! Be sure to check out the docs at https://docs.amplify.aws/react/build-a-backend/functions/streaming-logs/
