### ISSUE TITLE
No "groups" option in defineAuth

### ISSUE THREAD

**Issue by alexbelash** [aws-amplify/amplify-backend#1134]
### Environment information

```plain text
System:
  OS: macOS 14.3.1
  CPU: (10) arm64 Apple M1 Max
  Memory: 269.28 MB / 32.00 GB
  Shell: /bin/zsh
Binaries:
  Node: 20.8.0 - /opt/homebrew/bin/node
  Yarn: 1.22.19 - /opt/homebrew/bin/yarn
  npm: 10.1.0 - /opt/homebrew/bin/npm
  pnpm: undefined - undefined
NPM Packages:
  @aws-amplify/backend: 0.12.1
  @aws-amplify/backend-cli: 0.11.1
  aws-amplify: 6.0.20
  aws-cdk: Not Found
  aws-cdk-lib: Not Found
  typescript: 5.4.2
AWS environment variables:
  AWS_STS_REGIONAL_ENDPOINTS = regional
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
No CDK environment variables
```

### Description

Quote from Amplify Gen2 docs, Storage page: "If you have configured user groups in defineAuth, you can scope storage access to specific groups. Suppose you have a defineAuth config with admin and auditor groups."
[https://docs.amplify.aws/gen2/build-a-backend/storage/#user-group-access](https://docs.amplify.aws/gen2/build-a-backend/storage/#user-group-access)

There is no "groups" option in defineAuth props object.

Is it not available yet?

**Comment by edwardfoyle** [comment]
Hi @alexbelash, you'll need to install the latest beta version of the backend and backend cli packages:
```
npm install @aws-amplify/backend@beta @aws-amplify/backend-cli@beta
```

**Comment by alexbelash** [comment]
@edwardfoyle oh, I see. Just tried, it worked, thank you!
