### ISSUE TITLE
[CICD] Windows e2e tests get stuck during package installation

### ISSUE THREAD

**Issue by edwardfoyle** [aws-amplify/amplify-backend#1168]
### Description

eg https://github.com/aws-amplify/amplify-backend/actions/runs/8347579307/job/22847621217#step:8:234

The `create-amplify` tests start installing packages and then the process hangs until the job times out.

This seems to only happen on Windows workers and seems to be happening with more frequency since using `windows-latest` runners instead of custom large runners.

**Comment by edwardfoyle** [comment]
Some additional occurrences
https://github.com/aws-amplify/amplify-backend/actions/runs/8332834641/job/22803051714
https://github.com/aws-amplify/amplify-backend/actions/runs/8330141253/job/22797492103

**Comment by rtpascual** [comment]
Additional occurrence: https://github.com/aws-amplify/amplify-backend/actions/runs/8367027538/job/22909402425?pr=1178#step:8:159
