### ISSUE TITLE
What about adding `.nvmrc` to make the node version explicit?

### ISSUE THREAD

**Issue by magisystem0408** [aws-amplify/amplify-backend#1200]
### Environment information

```plain text
System:
  OS: macOS 14.3.1
  CPU: (20) arm64 Apple M1 Ultra
  Memory: 133.77 MB / 128.00 GB
  Shell: /opt/homebrew/bin/fish
Binaries:
  Node: 21.0.0 - ~/.local/share/nvm/v21.0.0/bin/node
  Yarn: undefined - undefined
  npm: 10.2.0 - ~/.local/share/nvm/v21.0.0/bin/npm
  pnpm: undefined - undefined
NPM Packages:
  @aws-amplify/backend: 0.12.1
  @aws-amplify/backend-cli: 0.11.1
  aws-amplify: 6.0.20
  aws-cdk: 2.133.0
  aws-cdk-lib: 2.133.0
  typescript: 5.4.2
```

### Description

now Node version is 18+, but how about clarification in `.nvmrc`?

https://github.com/aws-amplify/amplify-backend/blob/eb646d8839fd0faf61dd8c8085f1208c89972bc2/package.json#L46-L48

**Comment by edwardfoyle** [comment]
Hi @magisystem0408, thanks for the suggestion! We explicitly gitignore several types of config files for local developer tools, including nvmrc: https://github.com/aws-amplify/amplify-backend/blob/54de5f773a6d1fcebc86404f3aab50f661fab9ca/.gitignore#L11-L16

We do this to keep the repo as agnostic as possible to the types of tooling developers want to use locally. Some developers may choose to use nvm to manage node versions but others may not. Where possible we try not to dictate developer tooling and don't want to add config to the repo that is specific to one tool.
