### ISSUE TITLE
Add time and comit message to most recent deployments in web interface

### ISSUE THREAD

**Issue by johnf** [aws-amplify/amplify-backend#1205]
### Environment information

```plain text
N/A
```

### Description

On the deployments web page, the most recent deployment is missing a started at and the commit message, so it's hard to know if it just happened or if maybe I pushed it to the wrong branch and it's an old deployment.

![image](https://github.com/aws-amplify/amplify-backend/assets/42590/973abbd7-4d3c-447e-9b6b-25353520e7ac)

**Comment by josefaidt** [comment]
Hey @johnf :wave: thanks for raising this! Marking this as a console feature request to evaluate further 🙂

**Comment by swaminator** [comment]
<img width="1051" alt="image" src="https://github.com/aws-amplify/amplify-backend/assets/2429410/afafeeae-c242-4b2b-97e6-be859d18f220">
This has been resolved.
