### ISSUE TITLE
Request for Enhanced Documentation on File Uploads Using New Access Patterns in Amplify Gen2

### ISSUE THREAD

**Issue by sithu951** [aws-amplify/amplify-backend#1221]
### Environment information

```plain text
System:
  OS: Linux 5.15 Ubuntu 20.04.6 LTS (Focal Fossa)
  CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
  Memory: 5.28 GB / 7.55 GB
  Shell: /bin/bash
Binaries:
  Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
  Yarn: 1.22.17 - /usr/local/bin/yarn
  npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
  pnpm: undefined - undefined
NPM Packages:
  @aws-amplify/backend: 0.13.0-beta.8
  @aws-amplify/backend-cli: 0.12.0-beta.8
  aws-amplify: 6.0.21
  aws-cdk: 2.133.0
  aws-cdk-lib: 2.133.0
  typescript: 5.4.2
AWS environment variables:
  AWS_STS_REGIONAL_ENDPOINTS = regional
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
No CDK environment variables
```

### Description

**Problem Description**
In the process of integrating AWS Amplify's storage capabilities with my project, I encountered challenges understanding the transition from Gen1 to Gen2, especially regarding file uploads with the new access patterns. The current Amplify Gen2 documentation details access patterns for authenticated users, guests, groups, and owners but redirects to Gen1 documentation for practical implementation of file uploads and downloads.

The redirection to Gen1 documentation is here: [Gen1 upload docs](https://docs.amplify.aws/javascript/build-a-backend/storage/upload/). This section uses accessLevel parameters such as guest, public, and private, automatically creating corresponding folders. However, there's a lack of guidance on how to upload files directly to a custom path (e.g., '/foo/*') without being confined to these predefined folders, which is critical for projects needing more flexible storage structures.

**Feature Request**
I propose an enhancement or update to the Amplify Gen2 documentation that:

Provides Clear Examples and Guidelines on how to upload files to custom paths (e.g., '/foo/' or '/foo/{entity_id}/') without defaulting to the public/private/protected folder structure. This includes examples using the new access patterns that Gen2 supports.
Expands on Access Control Mechanisms for these custom paths, detailing how permissions can be managed in a way that aligns with Gen2's flexible access controls.

**Rationale**
The ability to directly upload files to custom paths with detailed control over access levels is essential for developers to fully leverage AWS Amplify's storage capabilities, ensuring security and flexibility in how data is organized and accessed. Enhanced documentation in this area would greatly aid in the adoption and effective use of Amplify Gen2, especially for applications with complex storage and access requirements.

Thank you for considering this request. Enhanced clarity and guidance on this topic would significantly benefit the developer community, facilitating more sophisticated and secure storage solutions in our applications.

**Comment by edwardfoyle** [comment]
Hi @sithu951 thanks for pointing this out! We are still working on the frontend part of the gen 2 file upload/download experience. We are planning to overhaul the frontend docs for this new experience once the implementation is stable. We'll take this feedback into account when updating the docs!

**Comment by VivianaGarces** [comment]
> Hi @sithu951 thanks for pointing this out! We are still working on the frontend part of the gen 2 file upload/download experience. We are planning to overhaul the frontend docs for this new experience once the implementation is stable. We'll take this feedback into account when updating the docs!

Hi @edwardfoyle, based on the current version of the library is it possible to upload a file using `uploadData`? I see that it adds a "public", "private", "protected" sub folder and it gives me an 403 error. I used the [Owner-based access](https://docs.amplify.aws/gen2/build-a-backend/storage/#owner-based-access) config. Is there another way to achieve the upload?

**Comment by ykethan** [comment]
Hey @VivianaGarces, the documentation has been updated with custom paths and access patterns. Closing the issue.
