### ISSUE TITLE
Amplify Gen2 tutorial Deploy step is broken - unable to process request error

### ISSUE THREAD

**Issue by moatazsoli** [aws-amplify/amplify-backend#1229]
### Environment information

```plain text
System:
  OS: macOS 14.2.1
  CPU: (10) arm64 Apple M2 Pro
  Memory: 74.02 MB / 16.00 GB
  Shell: /bin/zsh
Binaries:
  Node: 20.11.1 - /usr/local/bin/node
  Yarn: undefined - undefined
  npm: 10.2.4 - /usr/local/bin/npm
  pnpm: undefined - undefined
NPM Packages:
  @aws-amplify/backend: 0.13.0-beta.14
  @aws-amplify/backend-cli: 0.12.0-beta.16
  aws-amplify: 6.0.25
  aws-cdk: 2.134.0
  aws-cdk-lib: 2.134.0
  typescript: 5.4.3
AWS environment variables:
  AWS_STS_REGIONAL_ENDPOINTS = regional
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
No CDK environment variables%
```

### Description

I'm following the tutorial here: https://docs.amplify.aws/gen2/start/quickstart/vite-react-app/
The app works locally and the sandbox works.

everything works good until I get to the step for "Deploy and host a fullstack branch"

https://us-east-1.console.aws.amazon.com/amplify/create

1- I choose source code provider as github
![image](https://github.com/aws-amplify/amplify-backend/assets/5561372/92e84d09-229a-42ed-a699-dba5a3f23e69)
2- On the 2nd step I'm able to select my repository branch
![image](https://github.com/aws-amplify/amplify-backend/assets/5561372/0a21fe6c-adae-41c2-a17c-2b84d749e3ca)
3- Then once I hit save and deploy I get this error, with no logs or no useful messages to debug

![image](https://github.com/aws-amplify/amplify-backend/assets/5561372/66efde11-0f18-49a8-aed7-7fcc0e3b098e)

**### Thanks for your help. This is on the tutorial path so many people are affected and prevents adoption for Gen2**

**Comment by ykethan** [comment]
Hey @moatazsoli, thank you for reaching out. Are you able to create a Gen 1 app using the `build an app` on the Amplify console? if you are observing a similar error, could you open a support case, refer to the [comment](https://github.com/aws-amplify/amplify-cli/issues/13470#issuecomment-1850691317) providing additional information.

**Comment by moatazsoli** [comment]
turned out to be an account issue. Raised a ticket/support case and they resolved it in 1 day. Great turnaround.

**Comment by bytrangle** [comment]
Hey @moatazsoli . When you raised a ticket for this issue, did you choose "Technical" or "Account and Billing"?
