### ISSUE TITLE
Support Landba function Urls configuration

### ISSUE THREAD

**Issue by jbp35** [aws-amplify/amplify-backend#1231]
### Environment information

```plain text
System:
  OS: Windows 11 10.0.22000
  CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Memory: 1.75 GB / 15.73 GB
Binaries:
  Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
  Yarn: undefined - undefined
  npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
  pnpm: undefined - undefined
NPM Packages:
  @aws-amplify/backend: 0.12.1
  @aws-amplify/backend-cli: 0.11.1
  aws-amplify: 6.0.19
  aws-cdk: Not Found
  aws-cdk-lib: Not Found
  typescript: 5.4.2
AWS environment variables:
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
  AWS_STS_REGIONAL_ENDPOINTS = regional
No CDK environment variables
```

### Description

Are there any plans to integrate Landba function Urls in fonction configuration? I would like to create a function to handle webhooks and it would be nice to be able to create an HTTP endpoint easily.

**Comment by ykethan** [comment]
Hey @jbp35, thank you for reaching. you can override the function and add the function URL. Refer to the documentation providing an [example](https://docs.amplify.aws/gen2/build-a-backend/add-aws-services/overriding-resources/#example---grant-access-permissions-between-resources)

for example, I was able to add a function URL using the following

```
import { myDemoFunction } from "./function/resource";
import { Function, FunctionUrlAuthType } from "aws-cdk-lib/aws-lambda";

const backend = defineBackend({
  myDemoFunction,
});

const myFunc = backend.myDemoFunction.resources.lambda as Function;

myFunc.addFunctionUrl({
  authType: FunctionUrlAuthType.AWS_IAM,
});

```

**Comment by jbp35** [comment]
> Hey @jbp35, thank you for reaching. you can override the function and add the function URL. Refer to the documentation providing an [example](https://docs.amplify.aws/gen2/build-a-backend/add-aws-services/overriding-resources/#example---grant-access-permissions-between-resources)
> 
> for example, I was able to add a function URL using the following
> 
> ```
> import { myDemoFunction } from "./function/resource";
> import { Function, FunctionUrlAuthType } from "aws-cdk-lib/aws-lambda";
> 
> const backend = defineBackend({
>   myDemoFunction,
> });
> 
> const myFunc = backend.myDemoFunction.resources.lambda as Function;
> 
> myFunc.addFunctionUrl({
>   authType: FunctionUrlAuthType.AWS_IAM,
> });
> 
> ```

Thank you, that's working great!
