### ISSUE TITLE
Can't perform schema changes

### ISSUE THREAD

**Issue by cabcookie** [aws-amplify/amplify-backend#1232]
### Environment information

```plain text
System:
  OS: macOS 14.3.1
  CPU: (10) arm64 Apple M1 Pro
  Memory: 686.28 MB / 32.00 GB
  Shell: /bin/zsh
Binaries:
  Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
  Yarn: undefined - undefined
  npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
  pnpm: undefined - undefined
NPM Packages:
  @aws-amplify/backend: 0.13.0-beta.14
  @aws-amplify/backend-cli: 0.12.0-beta.16
  aws-amplify: 6.0.26
  aws-cdk: 2.135.0
  aws-cdk-lib: 2.135.0
  typescript: 5.4.3
AWS environment variables:
  AWS_STS_REGIONAL_ENDPOINTS = regional
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
No CDK environment variables
```

### Description

I run the command:
`npx amplify sandbox --profile amplify-event-registration`

And I get the following output:
✨  Synthesis time: 0.03s

⚠️ The --hotswap and --hotswap-fallback flags deliberately introduce CloudFormation drift to speed up deployments
⚠️ They should only be used for development - never use them for your production Stacks!

amplify-eventregistration-carskoch-sandbox-c6933caeee: deploying... [1/1]

✨ hotswapping resources:
   ✨ AWS::AppSync::FunctionConfiguration 'MutationcreateRegistrationauth0Function'
   ✨ AWS::AppSync::FunctionConfiguration 'MutationupdateRegistrationauth0Function'
   ✨ AWS::AppSync::GraphQLSchema 'm3oq6glwevgi5jozts3kjw3ioyGraphQLSchema'
   ✨ Contents of S3 Bucket 'amplify-eventregistration-amplifydataamplifycodege-vw3zkgzxx4av'

✨ Contents of S3 Bucket 'amplify-eventregistration-amplifydataamplifycodege-vw3zkgzxx4av' hotswapped!
The CloudFormation deployment has failed.
Caused By: ❌ Deployment failed: AccessDeniedException: User: arn:aws:iam::711568858726:user/amplify-dev is not authorized to perform: appsync:ListFunctions on resource: arn:aws:appsync:eu-west-1:711568858726:/v1/apis/m3oq6glwevgi5jozts3kjw3ioy/functions

Resolution: Find more information in the CloudFormation AWS Console for this stack.
[Sandbox] Watching for file changes...

This problem happened after I was trying to add a field to an existing model.

**Comment by cabcookie** [comment]
I checked the CloudTrail and couldn't find a record where the `appsync:ListFunctions` API has been called.

**Comment by ykethan** [comment]
Hey @cabcookie, thank you for reaching out. From the error message, it appears the IAM user profile being utilized does not allow `"appsync:ListFunctions",`. Does the IAM user `amplify-dev` have [AmplifyBackendDeployFullAccess](https://us-east-1.console.aws.amazon.com/iam/home?region=us-east-1#/policies/details/arn%3Aaws%3Aiam%3A%3Aaws%3Apolicy%2Fservice-role%2FAmplifyBackendDeployFullAccess) policy attached?

**Comment by cabcookie** [comment]
Yes, that actually solved it. I only had `AdministratorAccess-Amplify` assigned to it.
