### ISSUE TITLE
There is no generated directory in the .amplify directory

### ISSUE THREAD

**Issue by rnrnstar2** [aws-amplify/amplify-backend#1244]
### Environment information

```plain text
System:
  OS: macOS 14.0
  CPU: (10) arm64 Apple M2 Pro
  Memory: 120.00 MB / 16.00 GB
  Shell: /bin/zsh
Binaries:
  Node: 20.5.0 - /usr/local/bin/node
  Yarn: 1.22.19 - /usr/local/bin/yarn
  npm: 9.8.0 - /usr/local/bin/npm
  pnpm: 8.15.5 - ~/Library/pnpm/pnpm
NPM Packages:
  @aws-amplify/backend: 0.12.1
  @aws-amplify/backend-cli: 0.11.1
  aws-amplify: 6.0.25
  aws-cdk: 2.134.0
  aws-cdk-lib: 2.134.0
  typescript: 5.4.3
AWS environment variables:
  AWS_DEFAULT_PROFILE = cloudteam
  AWS_STS_REGIONAL_ENDPOINTS = regional
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
No CDK environment variables
```

### Description

https://docs.amplify.aws/gen2/build-a-backend/functions/

I tried to specify the path to the function's env by referring to this document, but an error occurs because there is no env information in the .amplify directory.

**Comment by ykethan** [comment]
Hey @rnrnstar2, thank you for reaching out. Could you provide some additional information on the use case and what env are you referring to such as the environment variables for the function or the sandbox information? 
The `.amplify` folder is an build output with cdk artifacts and assets.

**Comment by edwardfoyle** [comment]
Hi @rnrnstar2, this feature is only available in the latest @beta version of gen 2. Try installing `@aws-amplify/backend@beta` and `@aws-amplify/backend-cli@beta`

**Comment by rnrnstar2** [comment]
got it.
So, at this point, is the best way to get it from amplifyconfiguration.json and set it in the lambda environment variable?

**Comment by edwardfoyle** [comment]
The best way would be to use the beta version of the packages. Barring that, you can use normal `process.env.ENV_VAR_NAME` access in your lambda function, but you won't get any types for the available environment variables.
