### ISSUE TITLE
About amplifyconfiguration.json when separating back-end and front-end applications in monorepo

### ISSUE THREAD

**Issue by rnrnstar2** [aws-amplify/amplify-backend#1257]
### Environment information

```plain text
System:
  OS: macOS 14.0
  CPU: (10) arm64 Apple M2 Pro
  Memory: 104.36 MB / 16.00 GB
  Shell: /bin/zsh
Binaries:
  Node: 20.5.0 - /usr/local/bin/node
  Yarn: 1.22.19 - /usr/local/bin/yarn
  npm: 9.8.0 - /usr/local/bin/npm
  pnpm: 8.15.5 - ~/Library/pnpm/pnpm
NPM Packages:
  @aws-amplify/backend: Not Found
  @aws-amplify/backend-cli: Not Found
  aws-amplify: Not Found
  aws-cdk: Not Found
  aws-cdk-lib: Not Found
  typescript: Not Found
AWS environment variables:
  AWS_DEFAULT_PROFILE = cloudteam
  AWS_STS_REGIONAL_ENDPOINTS = regional
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
No CDK environment variables
```

### Description

I have two apps in monorepo.
These two are each created as amplify applications.
These two use the same backend, so the backend is created in a separate amplify application.
Therefore, amplifyconfiguration.json is created in that build, so there is no amplifyconfiguration.json in the front application.
What should I do?

**Comment by edwardfoyle** [comment]
Hi @rnrnstar2, you can use the `amplify generate client-config` command to create the frontend config file any time after deploying the backend.
```
npx amplify generate config --app-id <id> --branch <branch>
```
will generate the frontend config for that Amplify App and branch. Or
```
npx amplify generate config --stack <stack name>
```
will generate the frontend config for any Amplify Gen 2 CloudFormation stack

See: https://docs.amplify.aws/gen2/deploy-and-host/fullstack-branching/monorepos/#deploy-frontend-apps for more info.

Feel free to follow up if you have additional questions!

**Comment by rnrnstar2** [comment]
thank you.
The production environment amplifyconfiguration.json has been generated.
However, during local development I want to use the sandbox amplifyconfiguration.json, but in the production environment I want to use the production environment amplifyconfiguration.json.
Copying it every time is a bad development experience, so is there a better way?

**Comment by rnrnstar2** [comment]
```

├── apps
│   └── admin
├── backend
│   ├── amplify
│   ├── amplify.yml
│   ├── amplifyconfiguration.json
│   ├── index.html
│   ├── node_modules
│   └── package.json
├── node_modules
├── package.json
├── packages
│   ├── eslint-config
│   ├── shared-backend
│   ├── tailwind-config
│   ├── typescript-config
│   └── ui
├── tsconfig.json
└── turbo.json
```

This is a repository for monorepos like this.
Packages and apps are monorepo workspaces.

When you install a package with npm using turborepo, node_modules are only generated in the root directory, and no node_modules are generated in the workspace root directory.

If node_modules are not generated, when you run `npx amplify sandbox --debug`, you will see the following and you will not be able to use the latest version.
````
NPM Packages:
   @aws-amplify/backend: Not Found
   @aws-amplify/backend-cli: Not Found
   aws-amplify: Not Found
   aws-cdk: Not Found
   aws-cdk-lib: Not Found
   typescript: Not Found
````

Therefore, I had to remove the amplify directory from the monorepo workspace.
However, if you remove the amplify directory from the workspace, a number of problems will occur, such as not being able to refer to the data schema and having to copy amplifyconfiguration.json every time.

How can I solve these problems?

**Comment by edwardfoyle** [comment]
I am not very familiar with turborepo, but if `@aws-amplify/backend` and `@aws-amplify/backend-cli` get installed into `<project root>/backend/node_modules` then you should be able to run any `npx amplify` command within the `<project root>/backend` directory.

**Comment by josefaidt** [comment]
Hey @rnrnstar2 in your monorepo you can define a few subpath exports in your "backend" package to point to the config file and schema. 
```
  "exports": {
    "./config": "./amplifyconfiguration.json",
    "./schema": "./amplify/data/schema.ts"
  },
```
your frontend build tool will need to be compatible with `moduleResolution: bundler` or preserve (e.g. Vite, esbuild) to load the typescript file, otherwise you can separate that into its own type definition file

**Comment by rnrnstar2** [comment]
I avoided this problem by forcibly creating node_modules in `<project root>/packages/shared-backend`.
The way to do that is to copy and use the externally generated node_modules as is.
When I solved it using this method, an error occurred in the reference relationship within node_modules.
Therefore, I thought that a fundamental solution was needed, so I opened the issue again.

In the monorepo environment, there is only one `<project root>/node_modules`.
Since we want to share the amplify directory, it is located at `<project root>/packages/shared-backend/amplify`.
However, the `npx amplify sandbox` command must be used in the folder where the amplify directory is located.

But npx requires node_modules to be in the directory where you run that command.
(Because NPM Packages is Not Found in npx amplify info.)

To solve these problems, you need to run the `npx amplify sandbox` command in `<project root>` and specify the amplify directory to refer to, but this function is not currently available.

Could you please help me with this issue?

**Comment by josefaidt** [comment]
Hey @rnrnstar2 
> But npx requires node_modules to be in the directory where you run that command.
> (Because NPM Packages is Not Found in npx amplify info.)

this is due to the info package looking for the dependencies in that directory rather than attempting to resolve each dependency and its version. npm should be able to resolve the binary via npx in the directory of your shared backend

**Comment by rnrnstar2** [comment]
It worked fine when I wrote the script in the workspace's package.json in the root directory and executed it.

**Comment by AlexThomas90210** [comment]
@rnrnstar2 What do you mean you wrote the script in the workspace's package.json? Did you cd to the folder which contained the /amplify folder?
