### ISSUE TITLE
Sandbox Unknown argument: name

### ISSUE THREAD

**Issue by jbp35** [aws-amplify/amplify-backend#1395]
### Environment information

```plain text
System:
  OS: Windows 11 10.0.22000
  CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Memory: 3.38 GB / 15.73 GB
Binaries:
  Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
  Yarn: undefined - undefined
  npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
  pnpm: undefined - undefined
NPM Packages:
  @aws-amplify/backend: 0.13.4
  @aws-amplify/backend-cli: 0.12.1
  aws-amplify: 6.1.4
  aws-cdk: Not Found
  aws-cdk-lib: Not Found
  typescript: 5.4.5
AWS environment variables:
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
  AWS_STS_REGIONAL_ENDPOINTS = regional
No CDK environment variables
```

### Description

After upgrading aws amplify, the command `npx amplify sandbox --name MySandboxName` does not work anymore.

It returns the following error: `Unknown argument: name`

I do not see the argument in the help list as well. Was this deprecated or is it a bug?

**Comment by jbp35** [comment]
OK, looks like --name as been replaced by --identifier.

However, the documentation does not seems to be updated. For instance:
https://docs.amplify.aws/gen2/deploy-and-host/sandbox-environments/features/

**Comment by ykethan** [comment]
@jbp35 thank you for reaching out. The documentation has been updated, closing the issue.
