### ISSUE TITLE
"fullname" userAttribute is not Populating and passwordPolicy Error in Authentication

### ISSUE THREAD

**Issue by suryaishnavi** [aws-amplify/amplify-backend#1438]
### Environment information

```plain text
System:
  OS: Windows 11 10.0.22631
  CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
  Memory: 7.97 GB / 15.84 GB
Binaries:
  Node: 20.12.2 - C:\Program Files\nodejs\node.EXE
  Yarn: undefined - undefined
  npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD
  pnpm: undefined - undefined
NPM Packages:
  @aws-amplify/backend: 1.0.0
  @aws-amplify/backend-cli: 1.0.1
  aws-amplify: 6.2.0
  aws-cdk: 2.140.0
  aws-cdk-lib: 2.140.0
  typescript: 5.4.5
AWS environment variables:
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
  AWS_STS_REGIONAL_ENDPOINTS = regional
No CDK environment variables
```

### Description

1. In the userAttributes, I included the standard attribute "fullname," but it does not appear on the signupAttributes.
2. In the password policy Overrides the newPasswordPolicyRequirements are not appearing
![Screenshot 2024-05-05 123659](https://github.com/aws-amplify/amplify-backend/assets/18899052/b495c7e5-82d9-451b-89b3-ba593be7b57f)

**Comment by ykethan** [comment]
Hey @suryaishnavi, thank you for reaching out. The issue appears to be similar to https://github.com/aws-amplify/amplify-backend/issues/762. To prevent any miscommunication between issue, marking this as duplicate.
