### ISSUE TITLE
[New Amplify Console UI] Missing branches and access for Team Members

### ISSUE THREAD

**Issue by biller-aivy** [aws-amplify/amplify-backend#1439]
### Environment information

```plain text
We are missing branches in the the new UI. 
Also only the account admin can access the the console at the moment. 
The other team member getting a loader...
```

### Description

All Branches are there and team member should have access

**Comment by ykethan** [comment]
Hey @biller-aivy, do you observe any notable errors in the browser debug console or the network tab ?

**Comment by Jay2113** [comment]
@biller-aivy can you also share your Amplify app id?

**Comment by hackmajoris** [comment]
Such changes overnight should be illegal. Please give the possibility to rollback to the old UI. The new UI looks horrible, buggy and this is inadmissible for a team which run production apps.

**Comment by biller-aivy** [comment]
> Hey @biller-aivy, do you observe any notable errors in the browser debug console or the network tab ?
<img width="1221" alt="Bildschirmfoto 2024-05-07 um 09 37 07" src="https://github.com/aws-amplify/amplify-backend/assets/88539760/501a4294-2588-4b2c-8729-dcb78e61db3e">
<img width="1064" alt="Bildschirmfoto 2024-05-07 um 09 35 49" src="https://github.com/aws-amplify/amplify-backend/assets/88539760/0088b290-6d88-4653-9d46-3d691f92ddaa">
<img width="227" alt="Bildschirmfoto 2024-05-07 um 09 36 10" src="https://github.com/aws-amplify/amplify-backend/assets/88539760/8b5c40c7-13b2-4918-a84a-9763c6c8b6b9">
<img width="241" alt="Bildschirmfoto 2024-05-07 um 09 36 18" src="https://github.com/aws-amplify/amplify-backend/assets/88539760/b36230d2-0301-46af-b346-e736795a7728">
<img width="1221" alt="Bildschirmfoto 2024-05-07 um 09 36 34" src="https://github.com/aws-amplify/amplify-backend/assets/88539760/916d06d5-05bd-492f-ae67-2b22b8c6a868">

**Comment by biller-aivy** [comment]
> @biller-aivy can you also share your Amplify app id?

- d2v6n1oht50tox
- d33b18ppqinomp 

all my apps are not working correct in the UI. 
when I change the URL by myself, I can access the branches.

**Comment by biller-aivy** [comment]
<img width="385" alt="Bildschirmfoto 2024-05-07 um 09 51 04" src="https://github.com/aws-amplify/amplify-backend/assets/88539760/afd6e778-e713-4193-b227-d0827119af73">

This is also missing when I create a new connection to a branch. We need this, because otherwise an old branch would be deploy also an old backend.

**Comment by Jay2113** [comment]
@biller-aivy to expedite the troubleshooting process we would like to jump on a call with you. Can you please share your email and availability privately via a DM on our [community discord server](https://discord.gg/amplify)? My username is `Jay Raval`.

**Comment by ChengS-U** [comment]
I've run into a similar issue, especially when trying to pick a branch from the dropdown for custom domains. It only shows some of the branches, and there doesn't seem to be any pattern to which ones are visible. Even if the branch is already set up there is a chance that it will show an empty dropdown

Also, I didn't spot any errors in the console related to this.

![screenshot](https://github.com/aws-amplify/amplify-backend/assets/70675203/920eeae2-2310-4e42-a7eb-28bd83dd8f75)

**Comment by swaminator** [comment]
@ChengS-U can you please send me your account ID on our [community discord server](https://discord.gg/amplify)? My username is `swaminator`

**Comment by arundna** [comment]
Closing the issue. Please feel free to open a new issue if you encounter problems
