### ISSUE TITLE
Missing branches on amplify console custom domains

### ISSUE THREAD

**Issue by Siqlain** [aws-amplify/amplify-backend#1440]
### Environment information

```plain text
After Gen2 update we have been experiencing issues regarding custom domain mappings as list of branches is incomplete.

And some of the teammates reported that amplify is loading for them forever.

In the screenshot attached you can see the one that was previosly linked to staging is now empty field
```

### Description
![image](https://github.com/aws-amplify/amplify-backend/assets/144030556/634ffb37-ec51-4e52-a4be-193a4e59b9f2)

**Comment by mzabalza** [comment]
My team and I are experiencing similar issues, with gitlab branches connections

**Comment by Jay2113** [comment]
@Siqlain @mzabalza thanks for reaching out. Can you share your Amplify app id?

From the screenshot, its a bit unclear on how many branches are connected to your app. In the older console experience, was the `queue` subdomain previously connected to the `staging` git branch? Also, is this issue happening across different apps and/or git branches?

**Comment by Siqlain** [comment]
HI @Jay2113 

Sorry won't be able to share the app id.
About the other part yes my queue subdomain was and is connected to staging as you can see in the screenshot .
The problem is when i go for the domain-configuration to assign a different branch to a sub-domain or add a new sub-domain the listing of branches are limited doesn't show all the connected branches

**Comment by Siqlain** [comment]
![image](https://github.com/aws-amplify/amplify-backend/assets/144030556/1fa85347-7b6f-45cf-a46f-257cb1894b08)

**Comment by Siqlain** [comment]
We have in total of 13 branches connected for this app

**Comment by Siqlain** [comment]
In domain-configuration the branch dropdown has these much branches only 
![image](https://github.com/aws-amplify/amplify-backend/assets/144030556/b35e488c-76e7-43fb-a1d7-44872410bd5d)

**Comment by Siqlain** [comment]
This same issue is with other amplify apps as well.
This is happening to us after the new UI update. On the side note can we access the old UI until this fixes?

**Comment by biller-aivy** [comment]
same like here: https://github.com/aws-amplify/amplify-backend/issues/1439

**Comment by swaminator** [comment]
@Siqlain can you please send me your account ID on our [community discord server](https://discord.gg/amplify)? My username is swaminator

**Comment by arundna** [comment]
Closing the issue. Please feel free to open a new issue if you encounter problems.
