### ISSUE TITLE
All Deployments/Apps are missing from the new UI

### ISSUE THREAD

**Issue by kingychiu** [aws-amplify/amplify-backend#1444]
### Environment information

```plain text
Region: ap-southeast-1
```

### Description

![Screenshot 2024-05-07 at 9 47 00 AM](https://github.com/aws-amplify/amplify-backend/assets/11500136/9742df73-d21f-45d2-96b8-44756083ccb1)

![Screenshot 2024-05-07 at 9 49 27 AM](https://github.com/aws-amplify/amplify-backend/assets/11500136/ad1d7195-38c3-498e-94d0-7c7fe79f45e0)

I dont see any other meaningful error message. Thank you.

**Comment by kingychiu** [comment]
```
❯ aws amplify list-apps --region ap-southeast-1

An error occurred (InternalFailureException) when calling the ListApps operation (reached max retries: 2): Oops, something went wrong. Please try again later.
```

**Comment by kingychiu** [comment]
I already fired support tickets as well

- Technical Case ID 171505131000979
- Technical Case ID 171505325900250

**Comment by kingychiu** [comment]
In case this won't be fixed in the short term. Can you provide us with a way to remove domain associations? 

We got Amplify working in another region, I want to link the domain to that region app... 

But because list-app cli is not working, we don't know the app-id of the app that we want to move. Thank you!

**Comment by hackmajoris** [comment]
You should be able to change the region here: 
<img width="86" alt="image" src="https://github.com/aws-amplify/amplify-backend/assets/3758212/a5371f13-f9cb-4737-abe6-898b41fdc35f">

**Comment by swaminator** [comment]
@kingychiu we are prioritizing a fix for your  issue

**Comment by Jay2113** [comment]
@kingychiu we have deployed a fix for this issue, can you now retry accessing the console in the `ap-southeast-1` region?

Please let us know how it goes. Thanks!

**Comment by kingychiu** [comment]
> @kingychiu we have deployed a fix for this issue, can you now retry accessing the console in the `ap-southeast-1` region?
> 
> Please let us know how it goes. Thanks!

```
aws amplify list-apps --region ap-southeast-1
```
is working now, thank you!

The console is also working fine.
