### ISSUE TITLE
Cant connect to Gitlab to deploy my app

### ISSUE THREAD

**Issue by mzabalza** [aws-amplify/amplify-backend#1450]
### Environment information

- region=eu-west-3

```plain text
aws amplify console
```

### Description

Since the new Aws Amplify UI I am not able to connect aws amplify to my gitlab account.
All our team is experiencing the same issue not only with one aws account but with several.
This are the exact steps to reproduce the bug:
1. Connect to aws account
2. Go to aws amplify service
3. Click on Create new app
4. In the first step "Choose source code provider", I choose Gitlab and click "Next".
5. New pop up page appears "Authorize AWS Amplify (CDG) to use your account?". I click on "Authorize".
![image](https://github.com/aws-amplify/amplify-backend/assets/30298519/ad71f171-e3a8-4a01-bc7b-eb203a0ea313)
6 . Pop up closes but reopens immediately and even if I keep clicking in Authorize it keeps reopening.
7 sometimes the pop up dissappears but I dont see any branch option:
![image](https://github.com/aws-amplify/amplify-backend/assets/30298519/487815b4-3cf8-483c-975f-b45eea9f9720)

In another aws account I did the connection one month ago so that connection is correctly linked but when I try to make a connection to a new branch the error is the same.

No matter the aws account, the gitlab user, this issue is always present.
Our time relies on aws amplify to deliver different projects to different clients and to be unable to even connect it to gitlab where all our codebase is hosted its a big issue for us.

**Comment by swaminator** [comment]
@mzabalza can we hop on a call with you.

**Comment by mzabalza** [comment]
yes of course

**Comment by Sepudev** [comment]
same error here, we cant connect new branchsss, helppp!

**Comment by swaminator** [comment]
@Sepudev @mzabalza can you please share your account ID via a DM on our [community discord server](https://discord.gg/amplify)? My username is swaminator.

**Comment by Sepudev** [comment]
@swaminator I left you a message on discord dm!

**Comment by swaminator** [comment]
@Sepudev i responded. Please send us your account ID.

**Comment by emily-malone** [comment]
@swaminator I am having the same issue.

**Comment by griffins-planera** [comment]
We are also encountering this issue. Since the new update all our team members have been unable to add new gitlab branches to our Amplify app. Amplify gets stuck in an loop of opening new authorization requests until we hit the maximum retry limit.

<img width="578" alt="Screenshot 2024-05-09 at 12 17 18 PM" src="https://github.com/aws-amplify/amplify-backend/assets/95201668/183e349a-77ea-4533-b0e1-9dd5798e4dcb">

<img width="435" alt="Screenshot 2024-05-09 at 12 13 25 PM" src="https://github.com/aws-amplify/amplify-backend/assets/95201668/4d264938-b5ff-45b9-a3e6-739874521c03">

**Comment by Jay2113** [comment]
@emily-malone @griffins-planera can you please share your account ID via a DM on our [community discord server](https://discord.gg/amplify)? My username is `Jay Raval`.

**Comment by mzabalza** [comment]
hey @Jay2113 @swaminator, thank you for your help.
Im trying to contact you through your community discord server without success. Are you dispo today?

**Comment by Sepudev** [comment]
@Jay2113 @swaminator I tried to contact by discord and got no answer, in our team we have not been able to connect and we have a little stuck this issue, no solution for the moment?

**Comment by swaminator** [comment]
@emily-malone @griffins-planera can you please share your account ID via a DM on our [community discord server](https://discord.gg/amplify)? My username is `swaminator`.

**Comment by iCodeForBananas** [comment]
Hi everyone,

We're going to track all further discussions and updates in ticket #1490. Please post any new information or questions there. Closing this issue as a duplicate.

Thank you!
