### ISSUE TITLE
[New Amplify Console UI] Missing option to connect a backend when connect a branch. 

### ISSUE THREAD

**Issue by biller-aivy** [aws-amplify/amplify-backend#1452]
### Environment information

```plain text
----
```

### Description

- Missing the "Set up continuous deploys with develop backend (Edit)" 
- Missing the option to connect a Backend to a Frontend App when we add a new Branch. Than we get the error, missing aws-export.js for sure.

**Comment by swaminator** [comment]
@biller-aivy we will fix this. In the interim, you can just go to your branch settings > Actions > Edit backend env to associate it with one.
<img width="1104" alt="image" src="https://github.com/aws-amplify/amplify-backend/assets/2429410/a61bb061-da5c-4560-8510-3e2a300160ce">

**Comment by biller-aivy** [comment]
<img width="935" alt="Bildschirmfoto 2024-05-07 um 17 39 56" src="https://github.com/aws-amplify/amplify-backend/assets/88539760/3d721278-fb1b-4497-829c-f54a8a4cec14">
@swaminator 

Not possible in my apps?!

**Comment by biller-aivy** [comment]
@swaminator 
FYI: We are using one Amplify App as Backend and 6 Frontend Apps which are connected to this Backend. Created by the Console and connected to the Backend via Console.

**Comment by swaminator** [comment]
@biller-aivy Can you please share your email and availability via a DM on our [community discord server](https://discord.gg/amplify)? My username is swaminator

**Comment by Jay2113** [comment]
@biller-aivy I was able to reproduce this issue and marking this as a bug. We are actively working on prioritizing a fix for it and will keep you posted with any updates.

**Comment by jciangarottis** [comment]
Hello! On my end, I'm dealing with a similar issue regarding integration with my branch. When using the 'add branch' option in the branch settings view, the browser returns an OAuth connection error. This is quite strange as I already have other branches added, as seen in the photo. I appreciate providing this to see if this information helps a bit more.

<img width="669" alt="Captura de pantalla 2024-05-09 a la(s) 10 09 58 a  m" src="https://github.com/aws-amplify/amplify-backend/assets/168228843/42c11610-f59f-4146-b813-f7ca74836f97">



<img width="1410" alt="Captura de pantalla 2024-05-09 a la(s) 10 11 20 a  m" src="https://github.com/aws-amplify/amplify-backend/assets/168228843/b92a3045-d96c-4a19-b52e-6380e8ec322b">


<img width="1138" alt="Captura de pantalla 2024-05-09 a la(s) 10 11 56 a  m" src="https://github.com/aws-amplify/amplify-backend/assets/168228843/e78deb6c-d655-4208-b541-b7ef8c84fa3e">

**Comment by swaminator** [comment]
@jciangarottis @biller-aivy we addressed this issue by adding a `Gen 1 Backend environments` tab in the branch settings in the console for all apps.
<img width="1289" alt="image" src="https://github.com/aws-amplify/amplify-backend/assets/2429410/d3d63572-0bb1-4f7c-8786-43e009dd6930">
