### ISSUE TITLE
[New Amplify Console UI] Unable to redeploy older deployment

### ISSUE THREAD

**Issue by petetrickey** [aws-amplify/amplify-backend#1464]
### Environment information

```plain text
----
```

### Description

When attempting to deploy an older version of the App, we select the older deployment and then click the `redeploy` button.
The behaviour we are seeing is that no matter which older deployment we select, it is always the latest deployment that is deployed.

It clones the repository and then we see check out the commit hash from the latest successful deployment, rather than the older one we were trying to select (we were trying to roll back the app).
In the older version of the UI the older commit hash would have been selected and the older app version of the app would have been deployed.

<img width="2061" alt="Screenshot 2024-05-08 at 15 58 32" src="https://github.com/aws-amplify/amplify-backend/assets/7979745/b5c551dc-e361-4cc5-a307-19ca7e17cf51">

**Comment by Jay2113** [comment]
@petetrickey thanks for reaching out. We have identified this as a bug and have prioritized a fix for it. We are actively working on it and will keep you posted with any updates. In the meantime, as a workaround you can use the `start-job` CLI command to redeploy an existing job:

```
aws amplify start-job --app-id <YOUR_APP_ID> --job-id <YOUR_JOB_ID> --job-type RETRY
```
Docs: https://awscli.amazonaws.com/v2/documentation/api/latest/reference/amplify/start-job.html

**Comment by lanesawyer** [comment]
For anyone trying the CLI workaround, the new Amplify UI hides the job ID, but you can dig it up in the "Deploy" accordion and you'll see it listed as "buildId" in the logs.

In addition, you'll need to specify `--branch-name` on the command as well.

**Comment by Jay2113** [comment]
@petetrickey @lanesawyer we have deployed a fix for this issue and you should now be able to redeploy an older deployment from the console. Can you please confirm if you are unblocked? Thanks!

**Comment by Jay2113** [comment]
Closing this thread since a fix has been deployed.
