### ISSUE TITLE
[New Amplify Console UI] When defining a sub-domain only the first 10 branches are displayed

### ISSUE THREAD

**Issue by netaxis-solutions** [aws-amplify/amplify-backend#1466]
### Environment information

```plain text
Using Amplify console on https://eu-central-1.console.aws.amazon.com/amplify/apps/
```

### Description

I have an Application with many version.
Each of the in branch. I think I have around 40 branches.
Each branch is mapped to a sub-domain.

I have added a new branch and now I need to add a new sub-domain for it.
But when doing this, the drop-down list of the brnaches shows only the 10 first branches. Therefore I can not select my new one.
![Screenshot 2024-05-08 at 17 58 51](https://github.com/aws-amplify/amplify-backend/assets/91882788/ba978ade-cb0f-44ca-a868-dcfb25d3ac01)

Also in this edit page, existing sub-domains do not show the branch linked (only a blanck screen)
![Screenshot 2024-05-08 at 17 59 02](https://github.com/aws-amplify/amplify-backend/assets/91882788/637a3929-f956-423e-8c2d-f4be948eebb6)

While when it is the display view (so not the edit view) all branches are displayed correclty
![Screenshot 2024-05-08 at 17 59 24](https://github.com/aws-amplify/amplify-backend/assets/91882788/a900f468-1a1f-48e2-a3c3-3dfa028bb441)

As a result I am currenlty no more able to define a sub-domain for the new version of my application.

**Comment by arundna** [comment]
Closing the issue. Please feel free to open a new issue if you encounter problems.
