### ISSUE TITLE
Deployment branches missing/hidden since new Amplify UI

### ISSUE THREAD

**Issue by jbreemhaar** [aws-amplify/amplify-backend#1469]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have removed any sensitive information from my code snippets and submission.

### Amplify Hosting feature

Frontend builds, One click deploy

### Is your feature request related to a problem? Please describe:

Hi all!

Since the new Amplify UI in the AWS Console some of my deployment branches in an Amplify app (dpzme52p5orzv) are missing (or hidden in the Amplify UI). I know they are still there because deployments still work, they're listed in some other places (like when adding a branch, or showing the custom domains mapped to branches).
 
I've checked some other Amplify apps, and it sees the branches of other apps _are_ shown. 

### Describe how you'd like this feature to work

Show all branches

![image](https://github.com/aws-amplify/amplify-hosting/assets/15439317/2992b6f7-90a9-48e0-abc0-6540afa398c9)
![image](https://github.com/aws-amplify/amplify-hosting/assets/15439317/afb54b76-d90d-48b1-834f-d1d807cf03b2)

**Comment by swaminator** [comment]
@jbreemhaar you still facing this issue?

**Comment by jbreemhaar** [comment]
> @jbreemhaar you still facing this issue?

No they're visible again! All branches are listed. Thanks, I've closed this issue.
