### ISSUE TITLE
[New Amplify Console UI] - Dark mode hidding modal title

### ISSUE THREAD

**Issue by jacsonrsasse** [aws-amplify/amplify-backend#1473]
### Environment information

```plain text
Using Amplify console on https://eu-central-1.console.aws.amazon.com/amplify/apps/
```

### Description

Console dark mode hides modal's title in disconnect branch. Images below:

![Screenshot from 2024-05-08 15-33-23](https://github.com/aws-amplify/amplify-backend/assets/14006502/2f7e1d11-3370-4f61-8f07-41655d5fab71)

![Screenshot from 2024-05-08 15-35-08](https://github.com/aws-amplify/amplify-backend/assets/14006502/030abbad-65d5-4bed-a353-3097c177a2a6)

It's not a big deal, just a report.

**Comment by ykethan** [comment]
Hey @jacsonrsasse, thank you for reaching out and providing us the screenshots. I was able to reproduce the issue, marking as bug.
on enabling the dark mode
![image (21)](https://github.com/aws-amplify/amplify-backend/assets/87995712/c092630e-8f4b-4163-bab8-46d043a9bffb)

after refreshing the page
![image (22)](https://github.com/aws-amplify/amplify-backend/assets/87995712/e0e710e2-c7d8-4f38-adc7-44196492ba55)

**Comment by arundna** [comment]
Closing the issue as this has been fixed. Please open a new issue if you encounter any further problems.
