### ISSUE TITLE
New UI enters infinite loop when trying to Redeploy

### ISSUE THREAD

**Issue by samstash** [aws-amplify/amplify-backend#1479]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have removed any sensitive information from my code snippets and submission.

### Amplify Hosting feature

Deployments

### Is your feature request related to a problem? Please describe:

1. Go to deployments screen
2. Select an old deployment
3. Hover over Redeploy button

Browser will not let you redeploy. The button enters an infinite loop getting mounted/unmounted from the DOM and requesting the `/jobs` endpoint

https://github.com/aws-amplify/amplify-hosting/assets/22029976/d5890e83-1679-48bc-aa41-6a6a61d1c523

### Describe how you'd like this feature to work

Redeploys should work

**Comment by Jay2113** [comment]
Hi @samstash 👋 , we have deployed a fix for this issue. Can you please verify and confirm whether you are able to now select the `Redeploy` button from the console? Thanks!

**Comment by Jay2113** [comment]
Closing this thread since a fix has been deployed.
