### ISSUE TITLE
I'm encountering difficulties when trying to deploy updates for the existing app using AWS Amplify.

### ISSUE THREAD

**Issue by Wellkies** [aws-amplify/amplify-backend#1482]
### Environment information

```plain text
Showing this error "Must specify jobId or sourceUrl for StartDeploymentRequest."
I encountered the same issue with the previous build that was previously hosted.
```

### Description

Must specify jobId or sourceUrl for StartDeploymentRequest.

**Comment by tedoughty** [comment]
I'm running into this issue doing a manual deployment via the console in the browser. Drag and drop and browsing to the archive both result in this error.

**Comment by treymcmeans** [comment]
Same issue.

**Comment by Jay2113** [comment]
@Wellkies @tedoughty @treymcmeans I am unable to reproduce this behavior. Are you observing this error on an existing Gen 1 app or when deploying a new app? Also, can you instead try using Amazon S3 for performing the manual deployment?

**Comment by treymcmeans** [comment]
It is an existing app in my case. I have had success using S3 with a zip archive. That’s been my workaround for now.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by treymcmeans** [comment]
FYI, this is now resolved for me.

**Comment by Jay2113** [comment]
Glad to hear that @treymcmeans! 

@tedoughty @Wellkies just checking in to see whether are you still running into this issue? Are you unblocked when using the Amazon S3 method for the manual deployments?

**Comment by Jay2113** [comment]
Closing this thread due to inactivity.
