### ISSUE TITLE
Overriding default installed version of node does not work

### ISSUE THREAD

**Issue by gongora92** [aws-amplify/amplify-backend#1488]
### Environment information

```plain text
AWS Console
```

### Description

I am trying to overwrite the nodejs version to use nodejs 20.11.1 but it's not getting overwrited once the building starts

This is the overwrite specifying nodejs 20.11.1
![Screenshot 2024-05-09 at 12 05 24](https://github.com/aws-amplify/amplify-backend/assets/44581880/f21e7394-763b-4ea0-ad7c-e41e92327340)

I am getting nodejs 18.18.2
![Screenshot 2024-05-09 at 12 20 14](https://github.com/aws-amplify/amplify-backend/assets/44581880/9f18a574-94bf-4e5d-9da0-c1380355ee97)

**Comment by gongora92** [comment]
As additional information, I made the nodejs overwrite after the branch was added. I deleted the branch and created again and the nodejs version was overwrited

**Comment by ykethan** [comment]
Hey @gongora92, thank you for reaching. I was able to reproduce the issue, marking as bug.

reproduction steps:

1. created new app with no added overrides, this starts the first build
2. add node override 
3. then redeploy, observe this doesn't detect the override

note: observed adding the override on the app creation advances setting or re-attaching the branch does detect the override.

**Comment by Jay2113** [comment]
Hi @gongora92 👋 , thanks for your continued patience. We have deployed a fix for this issue and you should now be able override the default node version as expected for Gen 1 apps. Thanks!
