### ISSUE TITLE
want to `ip address restrict` at Access Control

### ISSUE THREAD

**Issue by magisystem0408** [aws-amplify/amplify-backend#1498]
### Environment information

```plain text
System:
  OS: macOS 14.4.1
  CPU: (20) arm64 Apple M1 Ultra
  Memory: 7.13 GB / 128.00 GB
  Shell: /opt/homebrew/bin/fish
Binaries:
  Node: 18.17.0 - ~/.local/share/nvm/v18.17.0/bin/node
  Yarn: 1.22.21 - ~/.local/share/nvm/v18.17.0/bin/yarn
  npm: 9.6.7 - ~/.local/share/nvm/v18.17.0/bin/npm
  pnpm: undefined - undefined
NPM Packages:
  @aws-amplify/backend: Not Found
  @aws-amplify/backend-cli: Not Found
  aws-amplify: Not Found
  aws-cdk: Not Found
  aws-cdk-lib: Not Found
  typescript: 5.2.2
AWS environment variables:
  AWS_STS_REGIONAL_ENDPOINTS = regional
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
No CDK environment variables
```

### Description

Amplify app can setting access control at aws amplify console.
now i want to set not only Username and Password access but also, ip access controll.

![screen sot](https://github.com/aws-amplify/amplify-backend/assets/61937077/9cc371ba-6604-4d6e-9b60-ed8f3055ac6a)

**Comment by ykethan** [comment]
Hey @magisystem0408, thank you for reaching out. Marking this as feature request to support ip access control on Access control.

**Comment by ykethan** [comment]
Closing this issue, as this is currently being tracked on https://github.com/aws-amplify/amplify-hosting/issues/36. Do subscribe to the issue for any further updates.
