### ISSUE TITLE
Gen 2 Dashboard not allowing user creation -- phone number field not showing

### ISSUE THREAD

**Issue by ChristopherGabba** [aws-amplify/amplify-backend#1505]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

GraphQL API, DataStore

### Amplify Version

v6

### Amplify Categories

api

### Backend

Amplify Gen 2 (Preview)

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

I am trying to create a dummy user using the ui in the dashboard and the phoneNumber field is not showing:

<img width="541" alt="Screenshot 2024-05-11 at 2 35 30 PM" src="https://github.com/aws-amplify/amplify-js/assets/122328438/f2a059c0-028e-4da5-b7eb-37c6dd6ed7eb">

<img width="506" alt="Screenshot 2024-05-11 at 2 42 12 PM" src="https://github.com/aws-amplify/amplify-js/assets/122328438/15eb5ceb-eca5-404c-bc37-a4ca26335bd9">

### Expected behavior

The UI should allow me to enter the phone number.

### Reproduction steps

1. Create a gen 2 app with an AWS Phone Number type as an object parameter and try to create a user with that paramter

### Code Snippet

N/A - My dashboard is for a react native app

### Log output

<details>

```
// Put your logs below this line


```

</details>

### Mobile Browser

Safari

**Comment by ykethan** [comment]
@ChristopherGabba thank you for reaching out. I was able to reproduce the issue, marking as bug.

**Comment by ChristopherGabba** [comment]
Thanks @ykethan, I figured it had to be. Appreciate you and @chrisbonifacio 's quick response!

**Comment by ykethan** [comment]
Closing the issue as a fix has been deployed. Re-tested this and did not observe the error messages.
