### ISSUE TITLE
standard_required_attributes not working

### ISSUE THREAD

**Issue by lejovaar7** [aws-amplify/amplify-backend#1511]
### Environment information

```plain text
System:
  OS: macOS 14.4.1
  CPU: (8) arm64 Apple M2
  Memory: 155.56 MB / 8.00 GB
  Shell: /bin/zsh
Binaries:
  Node: 18.17.0 - ~/.nvm/versions/node/v18.17.0/bin/node
  Yarn: undefined - undefined
  npm: 9.6.7 - ~/.nvm/versions/node/v18.17.0/bin/npm
  pnpm: undefined - undefined
NPM Packages:
  @aws-amplify/backend: 1.0.1
  @aws-amplify/backend-cli: 1.0.2
  aws-amplify: 6.3.1
  aws-cdk: 2.141.0
  aws-cdk-lib: 2.141.0
  typescript: 5.4.5
AWS environment variables:
  AWS_STS_REGIONAL_ENDPOINTS = regional
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
No CDK environment variables
```

### Description

Here resources.ts

![image](https://github.com/aws-amplify/amplify-backend/assets/26439842/4ea3b581-f6b0-4a86-8c95-b5099a53fd85)

backend.ts

![image](https://github.com/aws-amplify/amplify-backend/assets/26439842/17cbdee2-d255-4199-ac19-abec725ef5fa)

User pool Required attributes:

![image](https://github.com/aws-amplify/amplify-backend/assets/26439842/b233d2a7-7461-44a4-8a67-1b5280f86e2e)

here amplify_outputs.json:

![image](https://github.com/aws-amplify/amplify-backend/assets/26439842/083cf019-4fe7-4e05-b001-f6ab7372f5a7)

It can also be seen that in password_policy the values `require_numbers`, `require_lowercase`, `require_uppercase`, and require_symbols are set to `true` when I have set them to `false`.

**Comment by ykethan** [comment]
Hey @lejovaar7, thank you for reaching out. The property override no updating the amplify_outputs is currently being tracked on https://github.com/aws-amplify/amplify-backend/issues/762.
tried reproducing the issue on the standard attributes not appearing 

```
// auth/resource.ts
import { defineAuth } from "@aws-amplify/backend";
/**
 * Define and configure your auth resource
 * @see https://docs.amplify.aws/gen2/build-a-backend/auth
 */
export const auth = defineAuth({
  loginWith: {
    email: true,
    phone: true,
  },
  multifactor: {
    mode: "OPTIONAL",
    totp: true,
    sms: true,
  },

  userAttributes: {
    email: {
      required: true,
      mutable: true,
    },
    phoneNumber: {
      required: true,
      mutable: true,
    },
    address: {
      required: false,
      mutable: true,
    },
    givenName: {
      required: true,
      mutable: true,
    },
    familyName: {
      required: true,
      mutable: true,
    },
  },
});

```

```
const backend = defineBackend({
  auth,
  // data,
  // storage,
});

const { cfnUserPool } = backend.auth.resources.cfnResources;

cfnUserPool.addPropertyOverride("Policies", {
  PasswordPolicy: {
    MinimumLength: 8,
    RequireLowercase: false,
    RequireNumbers: false,
    RequireSymbols: false,
    RequireUppercase: false,
  },
});

cfnUserPool.addPropertyOverride("Schema", [
  {
    Name: "access_status",
    AttributeDataType: "Boolean",
    DeveloperOnlyAttribute: true,
  },
]);

```

<img width="504" alt="image" src="https://github.com/aws-amplify/amplify-backend/assets/87995712/3bc47d02-fd8f-4871-8400-6b78d897a942">

**Comment by ykethan** [comment]
it appears the console deploy does remove the required attributes as well
<img width="504" alt="image" src="https://github.com/aws-amplify/amplify-backend/assets/87995712/7540b00f-2a20-443c-ba3f-61d7b2e45be9">

**Comment by Amplifiyer** [comment]
The example given in the [docs](https://docs.amplify.aws/react/build-a-backend/auth/modify-resources-with-cdk/#custom-attributes) is wrong. [`CfnUserPool.schema`](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_cognito.CfnUserPool.html#schema) contains both `standard_attributes` as well as `custom_attributes`. Overriding it will indeed clear all the standard attributes. It works in the incremental way because CFN is able to take the "diff" and apply on top of the existing configuration because the existing schema is non-mutable by definition.

One way to achieve it would be something like
```ts
const { cfnUserPool } = backend.auth.resources.cfnResources;

(cfnUserPool.schema as any).push({
  name: "access_status",
  attributeDataType: "Boolean",
  developerOnlyAttribute: true
});
```

cc: @josefaidt
