### ISSUE TITLE
How to configure external provider sign in with Auth0 in Gen2

### ISSUE THREAD

**Issue by VinayakSingh64** [aws-amplify/amplify-backend#1526]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

Angular

### Which UI component?

Authenticator

### How is your app built?

npm install and then ng serve

### What browsers are you seeing the problem on?

Chrome, Firefox, Microsoft Edge, Safari

### Which region are you seeing the problem in?

eu-central-1

### Please describe your bug.

I am using Auth0 by okta to have sign in for users who are in SAML or OIDC group trying to sign in to amplify authenticator. But once they try to sign in the authenticator replies with "user not found". There is no official document for users trying to sign in as external provider by auth0. How do i let those users sign in even when they are available in the same cognito userpool but not as default users?

### What's the expected behaviour?

External provider users coming from auth0 should be able to log in via amplify authenticator like normal users who are present in normal userpool

### Help us reproduce the bug!

Have a user as external provider in cognito userpool group and have a sign in experience via amplify authenticator, but make sure the user tries the auth0 sign in experience

### Code Snippet

```typescript
// Put your code below this line.

```
Amplify.configure({
  Auth: {
    Cognito: {
      userPoolId: environment.userPoolId,
      userPoolClientId: environment.userPoolClientId,
    },
  }
});

I have added this code in app.module.ts file and i want to put the auth0 code also so that it authenticates the user via the amplify authenticator.

Also i have added resource.ts file in auth folder created manually under amplify folder and here is the code

amplify/auth/resource.ts

```ts
import { defineAuth, secret } from '@aws-amplify/backend';


export const auth = defineAuth({
  loginWith: {
    email: true,
    externalProviders: {
      oidc: [
        {
         name: 'auth0',
          clientId: secret('auth0_CLIENT_ID'),
          clientSecret: secret('auth0_CLIENT_SECRET'),
          issuerUrl: '<your-issuer-url>',
        },
      ],
      logoutUrls: ['http://localhost:3000/', 'https://mywebsite.com'],
      callbackUrls: [
        'http://localhost:3000/profile',
        'https://mywebsite.com/profile',
      ],
    },
  },
});
```

Also i created a auth-client-js.js file under src

```
import { signInWithRedirect } from 'aws-amplify/auth';

await signInWithRedirect({
  provider: {
    custom: 'auth0'
  }
});
```

Still i am unable to configure the OIDC provider. Help me out with the configuration

**Comment by VinayakSingh64** [comment]
okay but i have configured the auth via code, not via amplify init command.

**Comment by josefaidt** [comment]
Hey @VinayakSingh64 :wave: thanks for raising this! What issues are you encountering when attempting to sign in?

**Comment by VinayakSingh64** [comment]
I am getting "user does not exist" reply from authenticator when i try to sign in via amplify authenticator, For normal users in cognito userpool it is working fine but when i try with an external provider user it shows "user does not exist"

![Screenshot 2024-05-17 104418](https://github.com/aws-amplify/amplify-backend/assets/106259659/9cb23581-63c9-4789-8dab-b62c604e71bf)

**Comment by VinayakSingh64** [comment]
Also i would like to mention that i havent configured the secret in Aws amplify console, rather like i used the auth setup in code itself i am doing the same thing for the secrets also like hardcoding it

clientId: secret('abcdefgh') like this.

**Comment by VinayakSingh64** [comment]
Also is there a way where the clientID and clientsecret is taken from cognito not via amplify backend. This makes the task easier for me as i am tryingg to authenticate SSO users via authenticator using external proviser auth0.

**Comment by josefaidt** [comment]
Hey @VinayakSingh64 instead of hardcoding your secrets, you can use `ampx sandbox secret set` to create secrets for your sandbox https://docs.amplify.aws/react/reference/cli-commands/#npx-ampx-sandbox-secret. These secrets can then be used by name with the `secret()` function. For example:

```bash
npx ampx sandbox secret set AUTH0_CLIENT_ID
```

```ts
// amplify/auth/resource.ts
```

**Comment by VinayakSingh64** [comment]
I have tried with the command but the command is giving an "could not determine executable error"

![image](https://github.com/aws-amplify/amplify-backend/assets/106259659/32c24f97-d022-4b3a-bd64-d202902a3124)

**Comment by VinayakSingh64** [comment]
Is there any other way to set the secrets?

**Comment by josefaidt** [comment]
Hey @VinayakSingh64 are you executing that command from the root of your project? Do you have the `@aws-amplify/backend-cli` package installed?

**Comment by VinayakSingh64** [comment]
Yes i have @aws-amplify/backend-cli package installed and i am executing the command from the root of the project

**Comment by ykethan** [comment]
Hey @VinayakSingh64, thanks for chatting on discord, glad to hear you were able to mitigate the issue by installing `@aws-amplify/backend-cli` to your project.

**Comment by ykethan** [comment]
@VinayakSingh64 following up on this this issue, would you require any further assistance on this?

**Comment by VinayakSingh64** [comment]
yeah!, please have a proper documentation for auth0 external provider, as there is no proper documentation

**Comment by ykethan** [comment]
@VinayakSingh64 created an documentation issue to add a Auth0 example: https://github.com/aws-amplify/docs/issues/7712
Closing this issue.
