### ISSUE TITLE
Flutter projects do not have name field on package.json

### ISSUE THREAD

**Issue by sampaio96** [aws-amplify/amplify-backend#1537]
### Description

It took me a few hours to figure out the cause of this bug on Flutter:

Command (create a sandbox, on AWS CLI):
`npx ampx sandbox`

Response:
```
InvalidPackageJsonError: Cannot load name from the package.json
Resolution: Ensure you are running ampx commands in root of your project (i.e. in the parent of the 'amplify' directory).
Also ensure that your root package.json file has a "name" field.
```

I thought there was a missing step in my Amplify configuration, and the file `package.json` was missing something.

However, this is a simple bug, with a simple solution.

Amplify supposes, by mistake, that all Flutter apps have the field `name` on `package.json`. However, that is more common in Node.js and other frameworks. On Flutter, the file that contains that information is `pubspec.yaml`.

The fix is simple: just add the line `name: <your_app_name>` to `package.json`.

Amazon should change this behavior, or at least change the error message to be more clear. This is a suggestion:
```
InvalidPackageJsonError: Cannot load name from the package.json
Add the line "name: <your-app-name>" to your root package.json file.
```

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

Set up Amplify on Flutter.

### Platforms

- [X] iOS
- [X] Android
- [X] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.22.0

### Amplify Flutter Version

2.0.0

### Deployment Method

Amplify CLI

**Comment by ykethan** [comment]
Hey @sampaio96, thank you for reaching for reaching out. Curious on how the project was setup? did you run into the error while using our [quickstart guide](https://docs.amplify.aws/flutter/start/quickstart/) ?

**Comment by ykethan** [comment]
Hey @sampaio96, following up on this issue.

**Comment by sampaio96** [comment]
Hi. No guide was used. My code is close to production.

This issue is not critical. As a workaround, I am using the number -1 instead of null.

I wouldn't even say it is a bug. It is more of a missing feature.

The issue is easy to understand. The function `model.copyWith`, which is auto-generated by Amplify, takes multiple key-values as input, but when a value is null, the function cannot understand if the value is null or absent. So it just treats it as absent, and does not update the value on the object.
