### ISSUE TITLE
Amplify Custom Headers Monorepo format not supported

### ISSUE THREAD

**Issue by hackmajoris** [aws-amplify/amplify-backend#1542]
### How did you install the Amplify CLI?

pnpm

### If applicable, what version of Node.js are you using?

18+

### Amplify CLI Version

11.0.5

### What operating system are you using?

macOS

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Describe the bug

The custom headers format for monorepo is  not recognised.

### Expected behavior

The custom headers format for monorepo is recognised.

### Reproduction steps

1. Go to Amplify Console
2. Select the Application/Hosting/Custom Headers
3. Try to use the Monorepo format as shown in the example: https://docs.aws.amazon.com/amplify/latest/userguide/custom-headers.html#custom-header-YAML-format
ex: 
```JSON
applications:
  - appRoot: 'dfd'
    customHeaders:
      - pattern: '**'
        headers:
          - key: 'Strict-Transport-Security'
            value: 'max-age=31536000; includeSubDomains'
          - key: 'X-Frame-Options'
            value: 'SAMEORIGIN'
          - key: 'X-XSS-Protection'
            value: '1; mode=block'
          - key: 'X-Content-Type-Options'
            value: 'nosniff'
          - key: 'Content-Security-Policy'
            value: "default-src 'self'"

```

The result: 

![image](https://github.com/aws-amplify/amplify-cli/assets/3758212/9ab25eb7-66b4-4186-89ea-1b2964c61420)

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
On a quick test, I was able to reproduce the issue. Marking as bug.

created the header as nested throws an error:
![image (22)](https://github.com/aws-amplify/amplify-backend/assets/87995712/733ab979-60df-434c-94db-6105c4fe66a8)

creating it without nested does not throw an error.
![image (21)](https://github.com/aws-amplify/amplify-backend/assets/87995712/076f1b12-bb24-4c97-bcee-b9147573cc78)

The docs show as nested: https://docs.aws.amazon.com/amplify/latest/userguide/custom-headers.html#custom-header-YAML-format

On a save the console throws an error:

<img width="1430" alt="image" src="https://github.com/aws-amplify/amplify-backend/assets/87995712/018c171c-440f-4a9b-93c4-a50f1a5849ef">

**Comment by swaminator** [comment]
@hackmajoris we are prioritizing a fix for this issue. In the meantime can you DM me or @Jay2113  on Discord to discuss this?

**Comment by Jay2113** [comment]
@hackmajoris thank you for your continued cooperation. We have deployed a fix for this issue and can you please verify if you are now unblocked?

**Comment by hackmajoris** [comment]
> @hackmajoris thank you for your continued cooperation. We have deployed a fix for this issue and can you please verify if you are now unblocked?

I did some tests and the issue is gone. Thanks for your effort to fix it. I'll close the issue.
