### ISSUE TITLE
Deleted webhook. How to recreate?

### ISSUE THREAD

**Issue by jay-babu** [aws-amplify/amplify-backend#1564]
### Environment information

```plain text
I use the gui.
```

### Description

I connected my application to github. went to github -> webhooks. deleted the amplify webhook by accident. meant to delete something else. how do i re-create it? i need some secret

**Comment by biller-aivy** [comment]
> ### Environment information
> 
> ```plain text
> I use the gui.
> ```
> 
> 
> ### Description
> 
> I connected my application to github. went to github -> webhooks. deleted the amplify webhook by accident. meant to delete something else. how do i re-create it? i need some secret

Amplify console - > reconnect repo?!

**Comment by jay-babu** [comment]
@biller-aivy in the old UI, I've done before however in the UI, I do not see an option for this. Note, the repo seems to still be connected but the webhook is missing

**Comment by Jay2113** [comment]
@jay-babu 👋 , thanks for reaching out. Currently, the new console experience does not provide a workflow for reconnecting the repository to an existing app. We have identified that as a bug and have prioritized a fix for it. In the meantime, can you recreate a new app and connect the same repository to it? This should create a new webhook in GitHub.

**Comment by jay-babu** [comment]
@Jay2113, I had done that, but there are two issues
1. The new webhook points to a different amplify application. Not a big deal, I can change that easily
2. This is bigger problem, there is a secret that I cannot see. I do not know if that secret is specific to that amplify application, if it is there is nothing I can do

**Comment by Jay2113** [comment]
Hi @jay-babu, thanks for sharing the additional context. We have recently introduced a `Reconnect Repository` button in the console which now allows you to reconnect your repository to an Amplify app. Using this workflow, you should be able to recreate a webhook in your repository. You can find this under `App settings` > `Branch settings`.

Please let us know how it goes. Thanks!

**Comment by jay-babu** [comment]
Unfortunately, I had to create a new application and delete the old one. Thanks for the fix though

**Comment by arundna** [comment]
Closing the issue. Please feel free to open a new issue if you run into any other problems. Thanks!
