### ISSUE TITLE
ENV Variable Update Failed Message

### ISSUE THREAD

**Issue by cobalt88** [aws-amplify/amplify-backend#1582]
### Environment information

```plain text
Deploying Next.js v13.4 application and updating environment variables.
```

### Description

When adding an environment variable that begins with AWS the success message is displayed even though the variable is not added. I had to do some digging to find out AWS_ is a reserved environment variable name and checked the network traffic tab to see the api calls were coming back with a 400 error. Would it be possible to display an error message instead of a success message when the environment variable update is not successful?

**Comment by Jay2113** [comment]
@cobalt88 👋 , thanks for reaching out. I was able to reproduce this behavior and marking this as a bug.

**Comment by Jay2113** [comment]
@cobalt88 👋 , we have deployed a fix for this issue. You should now see a toast notification displaying an error message as follows:

<img width="412" alt="Screenshot 2024-07-16 at 11 20 02 AM" src="https://github.com/user-attachments/assets/924c9a54-1918-4dd6-931b-ec3f5a3794d3">

**Comment by cobalt88** [comment]
That's awesome, thanks for taking care of that 👍
