### ISSUE TITLE
Support for standard Amplify json configuration file

### ISSUE THREAD

**Issue by andrew-clark-dev** [aws-amplify/amplify-backend#1595]
### Environment information

```plain text
System:
  OS: macOS 14.5
  CPU: (10) arm64 Apple M1 Pro
  Memory: 4.33 GB / 32.00 GB
  Shell: /bin/bash
Binaries:
  Node: 20.13.1 - /usr/local/bin/node
  Yarn: undefined - undefined
  npm: 10.7.0 - /usr/local/bin/npm
  pnpm: undefined - undefined
NPM Packages:
  @aws-amplify/backend: 1.0.2
  @aws-amplify/backend-cli: 1.0.3
  aws-amplify: 6.3.4
  aws-cdk: 2.143.0
  aws-cdk-lib: 2.143.0
  typescript: 5.4.5
AWS environment variables:
  AWS_STS_REGIONAL_ENDPOINTS = regional
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
No CDK environment variables
```

### Description

The generation of the configuration as a dart constant is comfortable but I think it is an unnecessary deviation from the standard Amplify usage. I would be nicer if the Amplify configure could take the standard json as a parameter.

Something like 

`npx ampx sandbox --outputs-out-dir assets`

in the pubspec.yaml

```
  assets:
    - assets/amplify_outputs.json
```

and then in main

```
    final String config =
        await rootBundle.loadString('assets/amplify_outputs.json');

    await Amplify.configure(config);

```

The main reason I have for this is that currently I cannot provide the "-outputs-format dart" to the "ampx pipeline-deploy" command and so I cannot simply deploy my frontend via the Amplify pipeline.

**Comment by ykethan** [comment]
From the comment: https://github.com/aws-amplify/amplify-flutter/issues/4834#issuecomment-2143520307 the issue will be tracked on https://github.com/aws-amplify/amplify-flutter/issues/4834. Closing this as duplicate. 
Do reach reach if you require any assistance.
