### ISSUE TITLE
 Add "-outputs-format dart" to "ampx pipeline-deploy"

### ISSUE THREAD

**Issue by andrew-clark-dev** [aws-amplify/amplify-backend#1612]
### Environment information

```plain text
System:
  OS: macOS 14.5
  CPU: (10) arm64 Apple M1 Pro
  Memory: 143.73 MB / 32.00 GB
  Shell: /bin/bash
Binaries:
  Node: 20.13.1 - /usr/local/bin/node
  Yarn: undefined - undefined
  npm: 10.7.0 - /usr/local/bin/npm
  pnpm: undefined - undefined
NPM Packages:
  @aws-amplify/backend: 1.0.2
  @aws-amplify/backend-cli: 1.0.3
  aws-amplify: 6.3.4
  aws-cdk: 2.143.0
  aws-cdk-lib: 2.144.0
  typescript: 5.4.5
AWS environment variables:
  AWS_STS_REGIONAL_ENDPOINTS = regional
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
No CDK environment variables
```

### Description

In order to deploy a flutter frontend in Amplify I need to be able to generate the Dart configuration when using pipeline-deploy . Adding the parameter that exists for this in the sandbox command to the pipeline-deploy command should allow me to do this.

**Comment by ykethan** [comment]
Thank you for opening this, marking this as feature request for further prioritization.

**Comment by sobolk** [comment]
Fixed in https://github.com/aws-amplify/amplify-backend/releases/tag/%40aws-amplify%2Fbackend-cli%401.1.0
