### ISSUE TITLE
Environment Variables Override getting removed and resetting to default value 

### ISSUE THREAD

**Issue by AmelUlMulk** [aws-amplify/amplify-backend#1614]
### Environment information

```plain text
AWS AMPLIFY Environment variables
```

### Description

Environment variable overrides are being removed automatically resetting to default values , this has happened 4 times causing live applications being connected to staging environment

**Comment by Jay2113** [comment]
@AmelUlMulk 👋 , thanks for reaching out. Can you share your Amplify app id and reproduction steps for this issue?

**Comment by Phil-Gibson-Techsico** [comment]
@Jay2113 I'm getting this same issue.  I enter an override using the AWS Amplify console and hit save.  Go back and check and it isn't there.

**Comment by Jay2113** [comment]
@Phil-Gibson-Techsico can you share your Amplify app id?

**Comment by Jay2113** [comment]
@AmelUlMulk @Phil-Gibson-Techsico Are you still experiencing the reported issue? If so, please share your Amplify app id and detailed reproduction steps to assist our investigation.

**Comment by Jay2113** [comment]
Closing this thread due to inactivity. If you continue to experience this issue, kindly reopen the thread with the above requested information. Thanks!
