### ISSUE TITLE
Tutorial has problems connecting with existing IAM IDP

### ISSUE THREAD

**Issue by stevegroom** [aws-amplify/amplify-backend#1651]
### Environment information

```plain text
On cloudshell:

npm notice 
npm notice New major version of npm available! 9.8.1 -> 10.8.1
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.8.1
npm notice Run npm install -g npm@10.8.1 to update!
npm notice 
npm ERR! could not determine executable to run

npm ERR! A complete log of this run can be found in: /home/cloudshell-user/.npm/_logs/2024-06-14T15_23_05_283Z-debug-0.log


on my localmachine

steve@Steves-MBP-8 amplifytest % npx ampx info
System:
  OS: macOS 14.5
  CPU: (12) arm64 Apple M2 Pro
  Memory: 143.34 MB / 32.00 GB
  Shell: /bin/zsh
Binaries:
  Node: 21.7.1 - /opt/homebrew/bin/node
  Yarn: undefined - undefined
  npm: 10.5.0 - /opt/homebrew/bin/npm
  pnpm: undefined - undefined
NPM Packages:
  @aws-amplify/backend: 1.0.0
  @aws-amplify/backend-cli: 1.0.1
  aws-amplify: 6.2.0
  aws-cdk: 2.140.0
  aws-cdk-lib: 2.140.0
  typescript: 5.4.5
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!                                                                            !!
!!  Node 21 has reached end-of-life on 2024-06-01 and is not supported.       !!
!!  Please upgrade to a supported node version as soon as possible.           !!
!!                                                                            !!
!!  This software is currently running on node v21.7.1.                       !!
!!  As of the current release of this software, supported node releases are:  !!
!!  - ^22.0.0 (Planned end-of-life: 2027-04-30)                               !!
!!  - ^20.0.0 (Planned end-of-life: 2026-04-30)                               !!
!!  - ^18.0.0 (Planned end-of-life: 2025-04-30)                               !!
!!                                                                            !!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
AWS environment variables:
  AWS_STS_REGIONAL_ENDPOINTS = regional
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
No CDK environment variables
steve@Steves-MBP-8 amplifytest %
```

### Description

Following the Amplify Gen2 tutorial. 
I come to this page https://docs.amplify.aws/react/start/account-setup/ 
and do not understand how to proceed. 

IAM Identity center was set up some time ago on the organisation root account and is connected to MS Entra as the identity provider.

Next, we are going to automate a number of steps that simulate the operations of setting up a user in the IAM Identity Center console. To get started open CloudShell, located in the console footer. 
(Does this refer to the cloud shell in the application account or the org root account? Can this disrupt other users?)

response=$(aws sso-admin list-instances)
ssoId=$(echo $response | jq '.Instances[0].IdentityStoreId' -r)
ssoArn=$(echo $response | jq '.Instances[0].InstanceArn' -r)
email_json=$(jq -n --arg email "$user_email" '{"Type":"Work","Value":$email}')
response=$(aws identitystore create-user --identity-store-id $ssoId --user-name amplify-admin --display-name 'Amplify Admin' --name Formatted=string,FamilyName=Admin,GivenName=Amplify --emails "$email_json")
userId=$(echo $response | jq '.UserId' -r)
response=$(aws sso-admin create-permission-set --name amplify-policy --instance-arn=$ssoArn --session-duration PT12H)
permissionSetArn=$(echo $response | jq '.PermissionSet.PermissionSetArn' -r)
aws sso-admin attach-managed-policy-to-permission-set --instance-arn $ssoArn --permission-set-arn $permissionSetArn --managed-policy-arn arn:aws:iam::aws:policy/service-role/AmplifyBackendDeployFullAccess
accountId=$(aws sts get-caller-identity | jq '.Account' -r)
aws sso-admin create-account-assignment --instance-arn $ssoArn --target-id $accountId --target-type AWS_ACCOUNT --permission-set-arn $permissionSetArn --principal-type USER --principal-id $userId
# Hit enter

**Comment by josefaidt** [comment]
Hey @stevegroom :wave: if your organization is already onboarded to IAM Identity Center then you do not need to run this script. It is intended to bootstrap IAM Identity Center with opinionated defaults for working with Amplify apps.

In your case, you can create a permission set named `AmplifyAccess` with the `AmplifyBackendDeployFullAccess` managed policy, and layer an AWS profile on top of your existing IAM Identity Center/SSO profile

```ini
[profile josef]
sso_session = josef
sso_account_id = xxxxxx
sso_role_name = AdministratorAccess
region = us-east-1

[profile josef-amplify]
source_profile = josef
sso_role_name = AmplifyAccess

[sso-session josef]
sso_start_url = https://d-xxxx.awsapps.com/start
sso_region = us-east-1
sso_registration_scopes = sso:account:access
```

**Comment by ykethan** [comment]
Closing the issue due to inactivity. Do reach out to us if you are still experiencing this issue.
