### ISSUE TITLE
Error: Setting up fake worker failed: "Unexpected token '<'".

### ISSUE THREAD

**Issue by alvaroman23** [aws-amplify/amplify-backend#1657]
### Environment information

```plain text
.
```

### Description

I am trying to deploy my vue3+vite app with pdf.js library and I am stuck with the process, as in my local everything seems to work but once I've deployed I got this error back,

- Error: Setting up fake worker failed: "Unexpected token '<'".

This happened after I've cleaned the cache in the browser but before the error was, 

- Error loading PDF: Error: Setting up fake worker failed: "Failed to fetch dynamically imported module: 

I've already configured the rewrite requests and Custom headers for the .mjs files. Anyone had the same issue or related and know any workaround?

**Comment by ykethan** [comment]
Hey, thank you for reaching out. Are you running referring to this library https://github.com/wojtekmaj/react-pdf ? 
Noticed [this](https://github.com/wojtekmaj/react-pdf/issues/991) issue on the repository, could you try the workaround on [comment](https://github.com/wojtekmaj/react-pdf/issues/991#issuecomment-1345466418) and let us know if this mitigates the issue.

**Comment by ykethan** [comment]
Closing the issue due to inactivity. Do reach out to us if you are still experiencing this issue
