### ISSUE TITLE
Access backend identifier in CDK

### ISSUE THREAD

**Issue by concavegit** [aws-amplify/amplify-backend#1659]
### Environment information

```plain text
System:
  OS: macOS 14.5
  CPU: (8) arm64 Apple M2
  Memory: 163.73 MB / 24.00 GB
  Shell: /bin/zsh
Binaries:
  Node: 22.2.0 - /opt/homebrew/bin/node
  Yarn: undefined - undefined
  npm: 10.7.0 - /opt/homebrew/bin/npm
  pnpm: undefined - undefined
NPM Packages:
  @aws-amplify/backend: Not Found
  @aws-amplify/backend-cli: Not Found
  aws-amplify: Not Found
  aws-cdk: Not Found
  aws-cdk-lib: Not Found
  typescript: Not Found
AWS environment variables:
  AWS_STS_REGIONAL_ENDPOINTS = regional
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
No CDK environment variables
```

### Description

In my backend, I am defining a lambda and a step function defined as a custom resource. I want my lambda to call that step function. That lambda needs a way to know what step function to call. The step function ARN is different depending on which stage or sandbox it is a part of. I would make the lambda function get the step function ARN from the step function's stack, but step function already depends on the lambda function in order to call it. That would cause a circular dependency. Instead, I plan to have my lambda call a step function called `MyStepFunction-<backendIdentifier>` and set my step function's name to that value. I will need access to the backend identifier in order to use that strategy though.

**Comment by ykethan** [comment]
Hey @concavegit, we appears to be similar to https://github.com/aws-amplify/amplify-backend/issues/1094 which is being tracked as feature request.

Similar to the issue you should be able to access the context information.
```
const amplifyBackendType = backend.auth.resources.userPool.node.tryGetContext(
  "amplify-backend-type"
);
const amplifyBackendNamespace =
  backend.auth.resources.userPool.node.tryGetContext(
    "amplify-backend-namespace"
  );
const amplifyBackendName = backend.auth.resources.userPool.node.tryGetContext(
  "amplify-backend-name"
);
```

the `amplifyBackendName` should be unique to each user on sandbox deployments.
