### ISSUE TITLE
Pre Sign-up Lambda user attributes not updated after user created

### ISSUE THREAD

**Issue by myendorphin** [aws-amplify/amplify-backend#1665]
### Environment information

```plain text
@aws-amplify/backend: 1.0.3
  @aws-amplify/backend-cli: 1.0.4
  aws-amplify: 6.3.4
  aws-cdk: 2.144.0
  aws-cdk-lib: 2.144.0
  typescript: 5.4.5
```

### Description

I followed the doc to add Pre Sign-up Lambda and the trigger. 
[Pre Sign-up Lambda triggers](https://docs.amplify.aws/vue/build-a-backend/auth/advanced-workflows/#pre-authentication-and-pre-sign-up-lambda-triggers)

The trigger works and logs are printed for Social Login. The lambda returns the event with added attributes:
```
return event {
  version: '1',
  region: 'us-east-1',
  userPoolId: 
...
    "request": {
        "userAttributes": {
              preferred_username: 'userName1',
               'custom:referralCode': '765030CB0C'
```

However, the attributes are not saved on the new user record created in the cognito.

**Comment by ykethan** [comment]
Hey @myendorphin, thank you for reaching out. The issue does appear to be similar to https://github.com/aws-amplify/amplify-backend/issues/1619
Did notice you did comment on the issue, you may need to utilize a post-authentication trigger as suggested in the comments following https://github.com/aws-amplify/amplify-backend/issues/1619#issuecomment-2155708986

**Comment by ykethan** [comment]
could you provide us some additional information on the use case for the Lambda function?

**Comment by myendorphin** [comment]
> could you provide us some additional information on the use case for the Lambda function?

Generate and assign some custom attribute values for a new user. Like referral code or any other

> Hey @myendorphin, thank you for reaching out. The issue does appear to be similar to #1619 Did notice you did comment on the issue, you may need to utilize a post-authentication trigger as suggested in the comments following [#1619 (comment)](https://github.com/aws-amplify/amplify-backend/issues/1619#issuecomment-2155708986)

The problem with this approach is the post-authentication trigger is not firing with Social Logins like google, apple etc.

**Comment by ykethan** [comment]
@myendorphin From the cogntio documentation the post-authenticated trigger for federated provider only triggers on Sign-in and Subsequent sign-ins. 
https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-identity-pools-working-with-aws-lambda-triggers.html#lambda-triggers-for-federated-users
https://github.com/aws-amplify/amplify-backend/issues/1619#issuecomment-2159400287

**Comment by ykethan** [comment]
Closing the issue due to inactivity. Do reach out to us if you require further assistance on this issue.
