### ISSUE TITLE
Enable Existing Cognito Resources for Per-User/Per-Owner Data Access

### ISSUE THREAD

**Issue by m-arrieta-r** [aws-amplify/amplify-backend#1672]
### Environment information

```plain text
Binaries:
  Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
  Yarn: 1.22.21 - ~/.nvm/versions/node/v18.18.2/bin/yarn
  npm: 9.8.1 - ~/.nvm/versions/node/v18.18.2/bin/npm
  pnpm: 9.0.6 - ~/Library/pnpm/pnpm
NPM Packages:
  @aws-amplify/backend: 1.0.3
  @aws-amplify/backend-cli: 1.0.4
  aws-amplify: 6.3.7
  aws-cdk: 2.146.0
```

### Description

Currently, AWS Amplify allows using existing Cognito resources but doesn't support them for per-user/per-owner data access. This limitation restricts developers who want to leverage existing authentication infrastructure for fine-grained data authorization.

#### Proposed Solutions:

I've identified potential ways to address this:

- Enhance `defineData`: Allow `defineData` to accept existing Cognito configuration settings (e.g., userPoolConfig). This would enable developers to specify their existing Cognito resources directly. [Reference](https://github.com/aws-amplify/amplify-backend/blob/4ec7cd85f61da8c394a989aa0e991b6f60a06be7/packages/backend-data/src/factory.ts#L98)
  Expected:
  ```typescript
  // ...
  export const data = defineData({
    schema,
    authorizationModes: {
      defaultAuthorizationMode: 'userPool',
      userPoolAuthorizationMode: {
        userPoolId: "<your-cognito-user-pool-id>",
        userPoolClientId: "<your-cognito-user-pool-client-id>",
        identityPoolId: "<your-cognito-identity-pool-id>",
      }
    },
  });
  ```

- Extend `defineBackend`:  Similar to the above, allow `defineBackend` to accept existing Cognito configuration for greater flexibility.
  Expected:
  ```typescript
  const backend = defineBackend({
    auth // add existing cognito settings here
    data // use existing cognito setup
  });
  ```

- Leverage addOutput({auth}): Allow `defineData` to be called after `addOutput({auth})` and retrieve the Cognito settings from the output. This would provide a streamlined way to utilize the authentication configuration.
  Expected:
  ```typescript
  const backend = defineBackend({})
  backend.addOutput({
    auth // add existing cognito settings here
    data // use existing cognito setup
  })
  ```

**Comment by josefaidt** [comment]
Hey @m-arrieta-r :wave: thanks for raising this and for taking the time to write up your thoughts for potential solutions! We have an RFC https://github.com/aws-amplify/amplify-backend/issues/1548 published to introduce `referenceAuth` as a way to reference existing Cognito resources, and we'd love to capture your thoughts and use cases (if not covered in the RFC). 

I'll close this in favor of tracking the RFC, but will mark as a feature request. Please subscribe to the RFC for further updates for this 🙂
