### ISSUE TITLE
Build Error: No prebuild or local build of @parcel/watcher found.

### ISSUE THREAD

**Issue by patreilly** [aws-amplify/amplify-backend#1682]
### Environment information

```plain text
System:
  OS: macOS 14.5
  CPU: (8) arm64 Apple M1
  Memory: 193.45 MB / 16.00 GB
  Shell: /bin/zsh
Binaries:
  Node: 22.3.0 - /opt/homebrew/bin/node
  Yarn: undefined - undefined
  npm: 10.8.1 - /opt/homebrew/bin/npm
  pnpm: undefined - undefined
NPM Packages:
  @aws-amplify/backend: 1.0.3
  @aws-amplify/backend-cli: 1.0.3
  aws-amplify: 6.3.5
  aws-cdk: 2.143.1
  aws-cdk-lib: 2.143.1
  typescript: 5.4.5
AWS environment variables:
  AWS_PROFILE = retaildemo
  AWS_STS_REGIONAL_ENDPOINTS = regional
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
No CDK environment variables
```

### Description

i'm getting this build error for a package I believe codebuild uses during the build process, but i have no control over how this is used during deployment:
> Error: No prebuild or local build of @parcel/watcher found. Tried @parcel/watcher-linux-x64-glibc. Please ensure it is installed (don't use --no-optional when installing with npm). Otherwise it is possible we don't support your platform yet. If this is the case, please report an issue to https://github.com/parcel-bundler/watcher.

I've attempted the following to fix this:

- Updated the amplify.yml to remove --cache .npm --prefer-offline from npm ci call
- Ran npm cache clean --force , deleted the node_modules folder and did a fresh npm install
- deleting the package-lock.json and recreating

[BUILD.txt](https://github.com/user-attachments/files/15990261/BUILD.txt)

**Comment by josefaidt** [comment]
Hey @patreilly :wave: thanks for raising this! We chatted offline and found that in a clean install (i.e. no `node_modules/` or `package-lock.json`) the lockfile contained entries for each platform's addon. However if the lockfile is deleted and regenerated while `node_modules/` still exist, only the addon for your host system is declared in the lockfile. This causes issues where after installing dependencies in the build system with `npm ci`, the linux addon is not installed and thus the failure in `amplify pipeline-deploy`

I'll mark this as a dependency issue for tracking, but seems similar to https://github.com/parcel-bundler/watcher/issues/152

As a workaround, delete both the lockfile and `node_modules/`, then reinstall with `npm install`

**Comment by patreilly** [comment]
This in fact fixed the issue.

**Comment by edwardfoyle** [comment]
This is actually an npm bug, not a parcel bug: https://github.com/npm/cli/issues/4828
The workaround above is corroborated by [this comment](https://github.com/npm/cli/issues/4828#issuecomment-1145683953) as well

**Comment by josefaidt** [comment]
Closing in favor of tracking the issue filed in the npm CLI's repo
