### ISSUE TITLE
I just lost all my environment variable overrides

### ISSUE THREAD

**Issue by michaeltrestianu23** [aws-amplify/amplify-backend#1689]
### Description

I was adding in 2 new environment variables for a react app in the Manage environment variables section. I also added some overrides and i subsequently lost all other branch variable overrides. I don't even know how it happened maybe the ui didn't load fully and i was too quick to save the form with the new env vars I added? Using Brave [Version 1.67.119 Chromium: 126.0.6478.114 (Official Build) (arm64)]

We've managed to add them back in, maybe it's a numbers issue? So far we have 29 variables with 39 various overrides

**Comment by Jay2113** [comment]
Hi @michaeltrestianu23 , thanks for reaching out. Can you confirm if the below steps are accurate to reproduce the issue?
- Start with an existing app that has a few environment variables and overrides
- Add a couple of new environment variables with overrides
- Save the changes
- Observe that the branch-level overrides for the existing environment variables were unexpectedly deleted

Also, can you share your Amplify app id?

**Comment by michaeltrestianu23** [comment]
Hi @Jay2113 thanks for getting back to me,

Our app id is `d2125if9n5v7i0`

I can confirm that this is defiantly a loading issue. This morning I saw that I was logged out and so I logged back in only to see that the overrides didn't load again, even after multiple page refreshes. I subsequently went to the app overview page to get you the app id and went back and they all displayed/loaded. Yesterday i didn't notice so when i added new overrides along with new variables it must've removed the ones that didn't load.

Thanks

**Comment by mattrout92** [comment]
Hi @Jay2113 I work on the same project as Michael and the issue seems to be that it doesn't always open the override variables in the UI when you click the "Manage Variables" button. I can see the variables being returned in the network tab, but they just aren't making their way to the UI. This means if you go to add a new variable and click save it completely removes the old override variables. I suspect it may be some kind of state issue in the UI. Perhaps it would be good to have a JSON tab where you can edit override variables there instead? Many Thanks!

**Comment by Jay2113** [comment]
@mattrout92 @michaeltrestianu23  thanks for sharing the additional details. If you are still able to reproduce this behavior, can you capture a HAR file and share it with us? This will be helpful for us to investigate the network requests and responses.

Steps to capture the HAR file are outlined here: https://repost.aws/knowledge-center/support-case-browser-har-file.

**Comment by michaeltrestianu23** [comment]
@Jay2113 i'm not comfortable sharing that as it'll contain sensitive info. Here are the steps to re-produce

1. Login
2. Ensure there are 29 environment variables set up for a project
3. Add overrides (we have 9 for branch w, 9 for branch x, 12 for branch y, 12 for branch z)
4. If you navigate directly to the url `variables/edit` the overrides don't loaded properly


When you manually use the internal links in the `Hosting` side menu and click `environment variables` and then select the manage variables button then they load properly.

The issue seems to be something around server side requests.

Thanks

**Comment by Jay2113** [comment]
@michaeltrestianu23 I was able to reproduce the issue when directly navigating to the `variables/edit` deep link URL. Marking this as a bug and in the interim we highly recommend you to use the console workflow for managing the environment variables and overrides i.e. `Hosting -> Environment variables -> Manage variables -> Save`.

We are working on prioritizing a fix for this issue.

**Comment by rammanokar-plateron** [comment]
Hi @Jay2113 
The Console workflow has the same problem; we've lost all our environment variables.

Hosting -> Environment variables -> Manage variables -> Save

**Comment by Jay2113** [comment]
Hi @rammanokar-plateron, can you please provide the following:
- The Amplify app id 
- A HAR file capturing the network requests and responses. [Steps to capture the HAR file](https://repost.aws/knowledge-center/support-case-browser-har-file)
- Detailed steps to reproduce the issue, as we are unable to replicate it.

**Comment by Jay2113** [comment]
Hi @michaeltrestianu23 @mattrout92 @rammanokar-plateron 👋 , thanks for your continued patience. We have deployed a fix for this issue. I will go ahead and close this thread but please feel free to reopen it or create a new thread if you are still experiencing this issue.

**Comment by yaakovh-eyecontact** [comment]
this bug still exists in the console. it just happened to us.
