### ISSUE TITLE
There is already a Construct with name 'storageRegion' in AmplifyStack

### ISSUE THREAD

**Issue by OperationalFallacy** [aws-amplify/amplify-backend#1699]
### Environment information

```plain text
npx ampx info
System:
  OS: macOS 14.5
  Shell: /bin/zsh
Binaries:
  Node: 20.15.0 - ~/.n/bin/node
  Yarn: 4.0.1 - ~/.n/bin/yarn
  npm: 10.7.0 - ~/.n/bin/npm
  pnpm: undefined - undefined
NPM Packages:
  @aws-amplify/backend: 1.0.4
  @aws-amplify/backend-cli: 1.1.0
  aws-amplify: 6.3.8
  aws-cdk: 2.147.2
  aws-cdk-lib: 2.147.2
  typescript: 5.5.2
AWS environment variables:
  AWS_STS_REGIONAL_ENDPOINTS = regional
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
No CDK environment variables
```

### Description

If I add multiple defineStorage, the synth fails with the above error.

This is a use case for a lambda function in the backend that has access to data and needs to access storage buckets that the external stack creates. 

If I create buckets in the external (nested) stacks and try to grant access to lambda from the backend, there is a circular dependency error.

There are name conflicts if I try to create a bucket as storage in the backend.

**Comment by josefaidt** [comment]
Hey @OperationalFallacy :wave: thanks for raising this! We do not currently support defining multiple buckets with `defineStorage` but it is top of mind to address! Marking this as a feature request

**Comment by OperationalFallacy** [comment]
No problem

There is a simple workaround if anybody needs it.
It adds buckets to the storage stack (without auth, of course).
 
```
// Add extra buckets
const env = backend.data.node.tryGetContext("amplify-backend-name")
const outputBucket = new Bucket(backend.storage.resources.cfnResources.cfnBucket.stack, "output", {
  bucketName: `output-${Aws.ACCOUNT_ID}-${Aws.REGION}-${env}`
})
```
