### ISSUE TITLE
The new console in AWS just looks bad and confusing

### ISSUE THREAD

**Issue by ccks01** [aws-amplify/amplify-backend#1710]
### Amplify CLI Version

x

### Question

The new console in AWS just looks bad and confusing. <REDACTED>Why is the look and feel of all the other consoles not maintained?

**Comment by Jay2113** [comment]
Hi @ccks01,

We have redacted a portion of your original comment as it violated our community's code of conduct. We kindly request you review the [Amazon Open Source Code of Conduct](https://aws.github.io/code-of-conduct) to help foster a positive and constructive environment for all.

We would appreciate if you could provide specific feedback on the areas you found confusing or challenging, as it will help us improve the user experience.

**Comment by Jay2113** [comment]
Closing this thread due to inactivity and feel free to open a new GitHub issue with us if you have any feedback or are experiencing issues. Thanks!
