### ISSUE TITLE
"Build container ran out of memory" when deploying a spa react app

### ISSUE THREAD

**Issue by GiancarlosIO** [aws-amplify/amplify-backend#1727]
### Environment information

```plain text
I'm using the amplify gitlab-integration

This is my `amplify.yml`

`
version: 1
frontend:
  env:
    variables:
      NODE_ENV: 'production'
  phases:
    preBuild:
      commands:
        - nvm install 20.15.1
        - nvm use 20.15.1
        - node -v 
        - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
        - echo "save-prefix=\"\"" >> .npmrc
        - echo "link-workspace-packages=false" >> .npmrc
        - echo "dedupe-injected-deps=true" >> .npmrc
        - echo "resolution-mode=highest" >> .npmrc
        - echo "hoist-workspace-packages=true" >> .npmrc
        - echo "enable-pre-post-scripts=true" >> .npmrc
        - npm install -g pnpm
        - pnpm install
    build:
      commands:
        - pnpm run build
  artifacts:
    baseDirectory: dist
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
      - .pnpm-store/**/*
  resources:
    build:
      spec: large

`
```

### Description

Hi there

I'm trying to deploy a new only-frontend application but I'm getting this error: Build container ran out of memory

![image](https://github.com/aws-amplify/amplify-backend/assets/17274950/d29dec61-266f-450c-b54b-f72c61709ed2)

The application is just a simple react app. So there is no way to use more than 4ram when building.
Also, I'm using `rspack/rsbuild`.

**Comment by Jay2113** [comment]
Hi @GiancarlosIO 👋 , thanks for reaching out. Based on the `amplify.yml` file, it appears that you're using the pnpm package manager during the build process. However, the build logs do not clearly indicate whether the `pnpm run build` command executed successfully. It's possible that it succeeded but the build process ran out of memory when creating the `node_modules` cache artifact.

For projects using pnpm specifically, you can utilize the following cache path:
```
cache:
  paths:
    - $(pnpm store path)
```

The pnpm store acts as a central cache for all dependencies, as documented here: https://pnpm.io/cli/store#path. Can you update the cache path in the `amplify.yml` file and then retry the build?

**Comment by GiancarlosIO** [comment]
oh wow
@Jay2113 that works!

Thankss!
