### ISSUE TITLE
Model introspection is not adding userPools provider when reusing existing cognito resources

### ISSUE THREAD

**Issue by caioquirino** [aws-amplify/amplify-backend#1735]
### Environment information

```plain text
$ npx ampx info
System:
  OS: Linux 5.15 Arch Linux
  CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
  Memory: 26.61 GB / 31.30 GB
  Shell: /bin/bash
Binaries:
  Node: 20.13.0 - ~/.nvm/versions/node/v20.13.0/bin/node
  Yarn: undefined - undefined
  npm: 10.5.2 - ~/.nvm/versions/node/v20.13.0/bin/npm
  pnpm: 9.4.0 - ~/.nvm/versions/node/v20.13.0/bin/pnpm
NPM Packages:
  @aws-amplify/backend: 1.0.4
  @aws-amplify/backend-cli: 1.1.0
  aws-amplify: 6.3.8
  aws-cdk: Not Found
  aws-cdk-lib: Not Found
  typescript: 5.5.3
AWS environment variables:
  AWS_STS_REGIONAL_ENDPOINTS = regional
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
No CDK environment variables
```

### Description

Hi, my end goal is to reuse the main cognito user pool for the sandbox environment, since I am using Discord OIDC / SSO, and that requires hard-coding some redirect URLs, so it's not really doable if I create one user pool per sandbox.

I am following this guide to do the override: https://docs.amplify.aws/nextjs/build-a-backend/auth/use-existing-cognito-resources/

The issue is that when I do this, I cannot authenticate using the userPool, as the metadata of the amplify_outputs.json does not include any information for the model introspection attributes.

This is what needs to be shown:
![image](https://github.com/user-attachments/assets/d0b47119-15b8-4ca3-89ff-2bf6495791c1)

But instead, the rules are simply not there. And that causes the project to fail to run or deploy, since I am trying to use an auth mechanism that "is not available".

* Am I doing it wrong? - Does anybody had a success case when doing this?
* Should I instead open a feature request, to: 
  * Allow sandbox for reusing cognito (or resources) from the main branch/stack; Or
  * Allow this proposal from the guide to reflect also on the model introspection; Or
  * Something else?

I am happy to contribute with a Pull request if I can get some direction :) thanks!

**Comment by ykethan** [comment]
Hey @caioquirino, thank you for reaching. Reusing existing Auth resource is currently being tracked on this
 RFC(request for comment): https://github.com/aws-amplify/amplify-backend/issues/1548. Do add your use case to the issue linked as this enable us in capturing your requirements. 
 Closing this as duplicate.
