### ISSUE TITLE
Auto branch detection is not working for one app but not another

### ISSUE THREAD

**Issue by erm-an** [aws-amplify/amplify-backend#1747]
### Environment information

```plain text
Irrelevant
```

### Description

I've deployed a new app (da73h1spqjnj3) where auto branch detection is not working. I use branch detection for deploying merge requests (PRs) on Gitlab. Fwiw, it works on my another app. (d1vt3yprnq72ok).

**Comment by Jay2113** [comment]
Hi @erm-an 👋 , thanks for reaching out. Can you clarify if you're referring to the [pattern based branch deployments feature](https://docs.aws.amazon.com/amplify/latest/userguide/pattern-based-feature-branch-deployments.html) or the [web previews feature](https://docs.aws.amazon.com/amplify/latest/userguide/pr-previews.html)? 

If it's regarding one of these features, I haven't been able to replicate the issue you mentioned when using Amplify with GitLab. Can you share detailed steps to reproduce the issue?

**Comment by erm-an** [comment]
Hey @Jay2113, I was indeed trying out pattern based branch deployments feature, which worked without any issues on my other app I deployed. I've just tested web preview feature and it seems to work without issues. I still don't know why pattern based matching (I use pr-* on my other app, but also tested *) is not working on this project, however, using previews would solve my immediate issue. Thanks for pointing that out.

**Comment by Jay2113** [comment]
Thanks @erm-an for the clarification regarding your use case. If you require auto-creation of PR branches, we highly recommend utilizing the Web Previews feature, as it is well-suited for this purpose.

Regarding the issue you're facing, I wasn't able to reproduce it when using the `pr-*` or `*` as the detection pattern. However, here are a couple of steps you can try to resolve the problem:
- Navigate to the App Settings > Branch Settings section and select the "Reconnect Repository" button. This should re-establish the connection between your repository and Amplify.
- After enabling the Pattern-Based Branch Deployment feature, any newly created branch will not be immediately reflected in the Amplify console. To trigger the detection, you'll need to push a change to the new branch.

**Comment by erm-an** [comment]
Thanks for the responses, I'll go ahead with web previews for my use case as you mentioned.

**Comment by Jay2113** [comment]
Sounds great! Closing the thread and feel free to open a new one if you are experiencing issues with Amplify.
