### ISSUE TITLE
Parce amplfy_outputs.json on IOS

### ISSUE THREAD

**Issue by yegenpres** [aws-amplify/amplify-backend#1749]
### Describe the bug

It to redefine auth password cfnUserPool.policies like in official documentation.
```
cfnUserPool.policies = {
  passwordPolicy: {
    minimumLength: 6,
    requireLowercase: false,
    requireNumbers: false,
    requireSymbols: false,
    requireUppercase: false,
  },
};
```

json looks like this: 
```
   "password_policy": {
      "min_length": 6,
    },
```

amplify_outputs.json does not contain property name of passwordPolicy object if value is set to false.
Then Swift Coding fail to decode this object as result initAmplify just fails, because official library expects this fields like required.

    public struct PasswordPolicy: Codable {
            public let minLength: UInt
            public let requireNumbers: Bool
            public let requireLowercase: Bool
            public let requireUppercase: Bool
            public let requireSymbols: Bool
        }
        
   So we can every boolean value should be set to try or else it just miss in json file, and fail to parse it.
   
   It means that output json should always generate fields with values set to false, or Codable struct accept optional parameters.

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. Go to backend.st
2. add this code: 
const { cfnUserPool } = backend.auth.resources.cfnResources

cfnUserPool.policies = {
  passwordPolicy: {
    minimumLength: 6,
    requireLowercase: true,
    requireNumbers: true,
    requireSymbols: true,
    requireUppercase: true,
    temporaryPasswordValidityDays: 20,
  },
};
3. Run app
```

### Expected behavior

Amplify should init success.

### Amplify Framework Version

6.3.7

### Amplify Categories

Auth

### Dependency manager

Swift PM

### Swift version

5.9

### CLI version

12.12.4

### Xcode version

15.4

### Relevant log output

```shell
<details>
<summary>Log Messages</summary>

Fail initialize amplify, because missed key in amplify_output.json
INSERT LOG MESSAGES HERE

</details>
```

### Is this a regression?

Yes

### Regression additional context

Amplify gen 2

### Platforms

iOS

### OS Version

iOS 17+

### Device

Any iOS device

### Specific to simulators

Iphone 15 pro max

**Comment by josefaidt** [comment]
Hey @yegenpres :wave: thanks for raising this! I was able to confirm this behavior and have marked this as a bug

**Comment by josefaidt** [comment]
note: these properties should also be marked as required in the outputs schema for the password policy block https://github.com/aws-amplify/amplify-backend/blob/main/packages/client-config/src/client-config-schema/schema_v1.json#L59-L82

**Comment by yegenpres** [comment]
> Answering my own question. I think you are trying to mention this [documentation](https://docs.amplify.aws/swift/build-a-backend/auth/modify-resources-with-cdk/). 
> 
> It seems to be a bug in Gen2. Will transfer the issue

Yes, this doc. 
Please let me know when You will fix it, or give some advice haw to work around

**Comment by sobolk** [comment]
This was fixed in https://github.com/aws-amplify/amplify-backend/releases/tag/%40aws-amplify%2Fclient-config%401.1.0
