### ISSUE TITLE
next-sitemap does not generate any sitemap on Amplify build stage despite working without issues locally and gitlab runners 

### ISSUE THREAD

**Issue by erm-an** [aws-amplify/amplify-backend#1754]
### Environment information

```plain text
Frontend deployment
```

### Description

I'm having an issue while generating sitemaps via next-sitemap on Amplify as postbuild step. (App ID: `da73h1spqjnj3`) It works locally without issues as well as on gitlab runners as the site was static exported to S3/Cloudfrount previously. As I have limited visibility to the build env, I'd appreciate any help that may point me to the right direction.   

In case that you're not familar with next-sitemap, it utilizes build-manifest.json to construct sitemap xml files as well as generates a robots.txt for search engines to utilize. 

Successful output when ran locally
```
$ next-sitemap
✨ [next-sitemap] Loading next-sitemap config: file:///Users/erman/dev/ruuf/landing/packages/_catigyf/next-sitemap.config.js
✅ [next-sitemap] Generation completed
┌───────────────┬────────┐
│ (index)       │ Values │
├───────────────┼────────┤
│ indexSitemaps │ 0      │
│ sitemaps      │ 1      │
```
Output on Amplify:
```
> next-sitemap
2024-07-17T22:38:53.370Z [INFO]: ✨ [next-sitemap] Loading next-sitemap config: file:///codebuild/output/src2808412550/src/appf/next-sitemap.config.js

2024-07-17T22:38:53.375Z [INFO]: ✅ [next-sitemap] Generation completed
2024-07-17T22:38:53.376Z [INFO]: ┌───────────────┬────────┐
│ (index) │ Values │

├───────────────┼────────┤

│ indexSitemaps │ 0 │
│ sitemaps │ 0 │

└───────────────┴────────┘

2024-07-17T22:38:53.383Z [INFO]: # Completed phase: build
```

**Comment by Jay2113** [comment]
Hi @erm-an 👋 , thanks for reaching out. I noticed that a couple of sitemap files were being generated for your domain, specifically https://www.invest.ruuf.com.tr/sitemap.xml and https://www.invest.ruuf.com.tr/server-sitemap-index.xml. Are you still experiencing issues related to these sitemaps? If so, could you provide details on how the sitemap is configured in your Next.js application and which version of Next.js you're using? This information will help us reproduce and investigate the issue more effectively.

**Comment by erm-an** [comment]
Just figured out that it was fully my mistake. Sorry for inconvenience.

**Comment by Jay2113** [comment]
Np @erm-an! Glad to hear that you are unblocked. Closing the thread.
