### ISSUE TITLE
post-confirmation lambda doesn't get generated properly in sandbox (NextJS)

### ISSUE THREAD

**Issue by roguewindrunner** [aws-amplify/amplify-backend#1755]
### Environment information

```plain text
System:
  OS: Windows 11 10.0.22621
  CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Memory: 6.80 GB / 15.85 GB
Binaries:
  Node: 20.15.1 - C:\Program Files\nodejs\node.EXE
  Yarn: 1.22.22 - C:\Program Files\nodejs\yarn.CMD
  npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD
  pnpm: 9.5.0 - C:\Program Files\nodejs\pnpm.CMD
NPM Packages:
  @aws-amplify/backend: 1.0.4
  @aws-amplify/backend-cli: 1.1.1
  aws-amplify: 6.4.0
  aws-cdk: 2.149.0
  aws-cdk-lib: 2.149.0
  typescript: 5.5.3
AWS environment variables:
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
  AWS_STS_REGIONAL_ENDPOINTS = regional
No CDK environment variables
```

### Description

I tried following the documentation for creating a user profile record with post-confirmation trigger with some modification to the data to conform to what I need. The sandbox showed no error during deployment, but when after signing up and confirming it showed the following error:

![image](https://github.com/user-attachments/assets/123554ab-fbb6-433f-b428-896be965de91)

So I checked the lambda function associated with the trigger and found that these were generated inside the index.mjs file:

index.mjs:
![image](https://github.com/user-attachments/assets/44a75f19-8ecc-439b-a9d8-c20471195d22)

index.mjs.map:
![image](https://github.com/user-attachments/assets/9d79735e-3c57-43e7-a618-6148c895561a)

Those doesn't seem like something that should be inside an .mjs file.

Thank you in advance for the assistance

## Folder Structure

```
amplify
├───auth
│       ├───post-confirmation
│       │        ├───graphql
│       │        │        ├───API.ts
│       │        │        ├───mutations.ts
│       │        │        ├───queries.ts
│       │        │        └───mutations.ts         
│       │        ├───handler.ts
│       │        └───resource.ts
│       └───resource.ts
├───data
│       └───resource.ts
│      
├───backend.ts
└───tsconfig.json
```

**Comment by sobolk** [comment]
@roguewindrunner 
The content of `index.mjs` looks like that because under the hood `esbuild` is used to minify the code and bundle dependencies. This is expected.
The error you're observing is most likely due to some bug in post confirmation lambda code or wrong configuration of that lambda (permissions?).
It might be worth to inspect that lambda's logs in AWS Console to see what actual error is.
If this doesn't help please share zip with an app that reproduces your problem if possible.

**Comment by roguewindrunner** [comment]
I see. I ended up playing around with the Node runtime version and got it working. Thank you for the guidance and help.

**Comment by ykethan** [comment]
Hey @roguewindrunner, glad to hear you were able to mitigate the issue. Wanted to get some additional information on the issue.
Did you observe any error messages in the CloudWatch function logs?
New runtime the function was updated to?

**Comment by ykethan** [comment]
Closing the issue due to inactivity. Do reach out if you are still experiencing this issue.
