### ISSUE TITLE
Infinite loading on Amplify's page on AWS

### ISSUE THREAD

**Issue by gnals-at** [aws-amplify/amplify-backend#1819]
### Environment information

```plain text
-
```

### Description

Attempting to access https://ap-southeast-1.console.aws.amazon.com/amplify/apps shows an infinite loader.

![image](https://github.com/user-attachments/assets/4f196a09-bc65-4827-903c-1ffab6ec3d2b)

This has been the second time in one month that this has happened. The last time it happened, it resolved itself within two working days.

The following didn't work as well:
- Changing the region to something else like "us-west-2"
- Using another browser (without extension)
- Using another computer
- Using another Wifi network
- Waiting for more than an hour

**Comment by Jay2113** [comment]
Hi @gnals-at, just checking in to see if you are still experiencing this issue? If so, can you share the above requested information?

**Comment by Jay2113** [comment]
Closing the thread due to inactivity.

**Comment by gnals-at** [comment]
Hello,

I will send it here when I notice this again. 

Thanks

**Comment by Moran1324** [comment]
I have the same issue with no success fixing it

**Comment by talaviya121** [comment]
Hi @Jay2113 ,

I am experiencing same issue. Here is the  HAR file.

[ap-south-1.console.aws.amazon.com.har.zip](https://github.com/user-attachments/files/18515099/ap-south-1.console.aws.amazon.com.har.zip)

**Comment by enricodvn** [comment]
This is happening for me rn
