### ISSUE TITLE
Using python for lambda functions

### ISSUE THREAD

**Issue by cookiejest** [aws-amplify/amplify-backend#1823]
### Environment information

```plain text
using amplify v2
```

### Description

hi would like to use python for some of the lambda functions. It looks like this is not supported yet but can see this.

https://github.com/aws-amplify/amplify-backend/issues/1543

Assuming this issue will not be supported soon - What would be the next best approach to do this? Is it to create an API gateway and cognito auth and run the queries that way or is there a better approach?

**Comment by ykethan** [comment]
Hey @cookiejest, thank you for reaching. As the RFC: https://github.com/aws-amplify/amplify-backend/issues/1543 provides this is currently not supported. But wanted to provide some information on this.

To create a python function you can utilize the CDK Lambda construct: https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_lambda-readme.html 
and build the function using local commands as the construct will default to docker to build the function and the CICD deploy may fail.
Also, CDK does provide a [pythonFunction](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-lambda-python-alpha-readme.html) construct but do note this is experimental.

Additionally, you can create the function on the console or a tool and reference the function for your use cases using the [fromFunctionArn](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_lambda.Function.html#static-fromwbrfunctionwbrarnscope-id-functionarn) method. 
But do note that functions created or referenced by CDK cannot be used with the Data schema or use other attributes such as the access property to provide access to the function directly.

**Comment by cookiejest** [comment]
Ok, as I am not able to use experimental approach, I decided to deploy python lambda functions separately in another repo and keep amplify updated via graphQL. However I havn't figured out a clean way to add custom graphql yet within the amplify v2.

I listed this seperately under #1838

**Comment by misha-slyusarev** [comment]
You can try this simple approach to create a custom python lambda resource https://medium.com/@misha.slyusarev/amplify-gen-2-custom-python-function-with-cdk-5e5b79b91b10

**Comment by cookiejest** [comment]
cool! What user will the custom function run under? If want to add the equivilent of only authenticated, is it possible?

**Comment by MarlonJD** [comment]
> cool! What user will the custom function run under? If want to add the equivilent of only authenticated, is it possible?

#1602 You can check my pr, it's allowing to use custom runtimes in data resources.ts, you can use go, python functions in graphql query and mutations

**Comment by cookiejest** [comment]
> > cool! What user will the custom function run under? If want to add the equivilent of only authenticated, is it possible?
> 
> #1602 You can check my pr, it's allowing to use custom runtimes in data resources.ts, you can use go, python functions in graphql query and mutations

i saw it. I can see it's blocked at the moment as the AWS team would need to do additional house keeping to support it properly, I cannot risk using the separate branch for my project unfortunately!






> You can try this simple approach to create a custom python lambda resource https://medium.com/@misha.slyusarev/amplify-gen-2-custom-python-function-with-cdk-5e5b79b91b10

Thanks, this looks more stable but has to introduce docker complexity. Maybe it would be better if had an example deploying amplify app and associated resources via SAM so amplify can be adopted by people already with a deployment pipeline and just using amplify for the front end auth with cognito?

Thanks!

**Comment by MarlonJD** [comment]
> > > cool! What user will the custom function run under? If want to add the equivilent of only authenticated, is it possible?
> > 
> > 
> > #1602 You can check my pr, it's allowing to use custom runtimes in data resources.ts, you can use go, python functions in graphql query and mutations
> 
> i saw it. I can see it's blocked at the moment as the AWS team would need to do additional house keeping to support it properly, I cannot risk using the separate branch for my project unfortunately!
> 
> > You can try this simple approach to create a custom python lambda resource https://medium.com/@misha.slyusarev/amplify-gen-2-custom-python-function-with-cdk-5e5b79b91b10
> 
> Thanks, this looks more stable but has to introduce docker complexity. Maybe it would be better if had an example deploying amplify app and associated resources via SAM so amplify can be adopted by people already with a deployment pipeline and just using amplify for the front end auth with cognito?
> 
> Thanks!

You don't need to use docker, you can bypass this

**Comment by cookiejest** [comment]
@MarlonJD any example of how?

**Comment by MarlonJD** [comment]
Hey @cookiejest,

You can check this https://github.com/aws-amplify/amplify-backend/pull/1602#issuecomment-2209424964 for more context.

Additionally, you'll need the changes from PR #1602. You can cherry-pick and use them as needed. I've also added related documentation [here](https://github.com/aws-amplify/docs/pull/8176), but it's not merged yet.

**Comment by cookiejest** [comment]
ok cool that looks more clear, i would start using this when it gets merged into the main!

**Comment by MarlonJD** [comment]
@cookiejest it's merged now, you can check [here](https://docs.amplify.aws/flutter/build-a-backend/functions/custom-functions/)
