### ISSUE TITLE
access Lambda generated role for a function behind a data custom query (gql) (gen2)

### ISSUE THREAD

**Issue by bogris** [aws-amplify/amplify-backend#1844]
### Environment information

```plain text
System:
  OS: macOS 14.0
  CPU: (8) arm64 Apple M1 Pro
  Memory: 198.34 MB / 16.00 GB
  Shell: /bin/zsh
Binaries:
  Node: 22.3.0 - ~/.nvm/versions/node/v22.3.0/bin/node
  Yarn: undefined - undefined
  npm: 10.8.1 - ~/.nvm/versions/node/v22.3.0/bin/npm
  pnpm: 8.9.0 - ~/.npm-packages/bin/pnpm
NPM Packages:
  @aws-amplify/auth-construct: Not Found
  @aws-amplify/backend: 1.0.4
  @aws-amplify/backend-auth: Not Found
  @aws-amplify/backend-cli: 1.2.2
  @aws-amplify/backend-data: Not Found
  @aws-amplify/backend-deployer: Not Found
  @aws-amplify/backend-function: Not Found
  @aws-amplify/backend-output-schemas: Not Found
  @aws-amplify/backend-output-storage: Not Found
  @aws-amplify/backend-secret: Not Found
  @aws-amplify/backend-storage: Not Found
  @aws-amplify/cli-core: Not Found
  @aws-amplify/client-config: Not Found
  @aws-amplify/deployed-backend-client: Not Found
  @aws-amplify/form-generator: Not Found
  @aws-amplify/model-generator: Not Found
  @aws-amplify/platform-core: Not Found
  @aws-amplify/plugin-types: Not Found
  @aws-amplify/sandbox: Not Found
  @aws-amplify/schema-generator: Not Found
  aws-amplify: 6.4.4
  aws-cdk: 2.151.0
  aws-cdk-lib: 2.151.0
  typescript: 5.5.3
AWS environment variables:
  AWS_STS_REGIONAL_ENDPOINTS = regional
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
No CDK environment variables
npm notice
npm notice New patch version of npm available! 10.8.1 -> 10.8.2
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.8.2
npm notice To update run: npm install -g npm@10.8.2
npm notice
npm notice
npm notice New patch version of npm available! 10.8.1 -> 10.8.2
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.8.2
npm notice To update run: npm install -g npm@10.8.2
npm notice
```

### Description

i have a lambda function defined as resolver for a data query. 

how can I update the IAM role in order to give it access to an S3 arn (external)

```
const echoHandler = defineFunction({
  entry: "./echo-handler/handler.ts",
});

const schema = a.schema({
  EchoResponse: a.customType({
    content: a.string(),
    executionDuration: a.float(),
  }),

  echo: a
    .query()
    .arguments({ content: a.string() })
    .returns(a.ref("EchoResponse"))
    .authorization((allow) => [allow.guest(), allow.authenticated()])
    // 3. set the function has the handler
    .handler(a.handler.function(echoHandler)),

});

export type Schema = ClientSchema<typeof schema>;

export const data = defineData({
  schema,
  authorizationModes: {
    defaultAuthorizationMode: "iam",
  },
});
```

i know we can get the lambda resource for functions defined under backend directly, but I see no way to access the lambda behind a custom resolver. 

Thanks

**Comment by ykethan** [comment]
Hey @bogris, thank you for reaching out. From the information provided, you would like a create a custom query, with a function as resolver which also interacts with an S3 bucket that was defined externally. Do let us know if i may have misunderstood this.
As you have indicated you should be able to import the function `resource.ts` and attach it to the defineBackend. The override the function and add a inline policy to grant s3 permissions to the function.
Refer to this comment providing an example to add permissions as inline: https://github.com/aws-amplify/amplify-backend/issues/1375#issuecomment-2079388509

**Comment by bogris** [comment]
I kind of discarded the attached comment because the function is attached to the resolver. 

I am under the assumption that if i add it to the backend object, it will create another instance of the function as a standalone lambda. 

basicalli the comment will have the defined function in 2 places within amplify. 

Am I interpreting it wrong? 

Thanks

**Comment by ykethan** [comment]
@bogris from my testing, this should only deploy 1 instance of the function. 

Example used for testing:
```
const myApiFunction = defineFunction({
  entry: "../functions/test-function/resource.ts",
});

export const schema = a.schema({
  EchoResponse: a.customType({
    content: a.string(),
    executionDuration: a.float(),
  }),

  echo: a
    .query()
    .arguments({ content: a.string() })
    .returns(a.ref("EchoResponse"))
    .authorization((allow) => [allow.guest(), allow.authenticated()])
    .handler(a.handler.function(myApiFunction)),
});
```

then attaching the function to the backend 

```
import { myApiFunction } from "./functions/test-function/resource";
const backend = defineBackend({
  auth,
  data,
  myApiFunction,
});

```

**Comment by paulochagass** [comment]
Hello guys! I have exactly the same problem here. I created a custom query and can't grant access to it in my DynamoDB tables. I followed what @ykethan suggested, but it didn't work.

**Comment by bogris** [comment]
> @bogris from my testing, this should only deploy 1 instance of the function.
> 
> Example used for testing:
> 
> ```
> const myApiFunction = defineFunction({
>   entry: "../functions/test-function/resource.ts",
> });
> 
> export const schema = a.schema({
>   EchoResponse: a.customType({
>     content: a.string(),
>     executionDuration: a.float(),
>   }),
> 
>   echo: a
>     .query()
>     .arguments({ content: a.string() })
>     .returns(a.ref("EchoResponse"))
>     .authorization((allow) => [allow.guest(), allow.authenticated()])
>     .handler(a.handler.function(myApiFunction)),
> });
> ```
> 
> then attaching the function to the backend
> 
> ```
> import { myApiFunction } from "./functions/test-function/resource";
> const backend = defineBackend({
>   auth,
>   data,
>   myApiFunction,
> });
> ```

thank you! i will give it a spin tomorrow. For some reason I did not think about spending the extra 10 minutes :|

**Comment by bogris** [comment]
> Hello guys! I have exactly the same problem here. I created a custom query and can't grant access to it in my DynamoDB tables. I followed what @ykethan suggested, but it didn't work.

in order to give it access to the dynamo tables created by the gql api, I wrote this:

```
type CapitalizedTables = {
  [K in keyof Schema]: K extends Capitalize<K> ? K : never;
}[keyof Schema];
//type Tables = "Todo" | "EchoResponse" | "echo"
const getTableName = (table: CapitalizedTables) =>
  backend.data.resources.tables[table].tableName;

const todoTable = backend.data.resources.tables.Todo;
const commentsTable = backend.data.resources.tables.Comment;
```

or are you referring to some other tables custom created?

I am using getTableName to pass them as strings in env vars so the sdk knows where to go.

**Comment by bogris** [comment]
> @bogris from my testing, this should only deploy 1 instance of the function.
> 
> Example used for testing:
> 
> ```
> const myApiFunction = defineFunction({
>   entry: "../functions/test-function/resource.ts",
> });
> 
> export const schema = a.schema({
>   EchoResponse: a.customType({
>     content: a.string(),
>     executionDuration: a.float(),
>   }),
> 
>   echo: a
>     .query()
>     .arguments({ content: a.string() })
>     .returns(a.ref("EchoResponse"))
>     .authorization((allow) => [allow.guest(), allow.authenticated()])
>     .handler(a.handler.function(myApiFunction)),
> });
> ```
> 
> then attaching the function to the backend
> 
> ```
> import { myApiFunction } from "./functions/test-function/resource";
> const backend = defineBackend({
>   auth,
>   data,
>   myApiFunction,
> });
> ```

worked like a charm! For me the issue is solved

thanks! 

@paulochagass i'm leaving it open for a bit to see if your problem is also solved.

**Comment by ykethan** [comment]
@bogris thank you for the confirmation. 

@paulochagass as @bogris provided the access prop provides access to the Data API which interacts with the DynamoDB tables using a query. If you could provide us your use case this would help us in assisting you.

**Comment by ykethan** [comment]
Closing the issue due to inactivity. Do reach out to us if you are still experiencing this issue
