### ISSUE TITLE
Setup Sandbox Environment Fails for eu-central-1

### ISSUE THREAD

**Issue by Flippittiflop** [aws-amplify/amplify-backend#1860]
### Environment information

```plain text
System:
  OS: macOS 14.5
  CPU: (8) arm64 Apple M1 Pro
  Memory: 1.31 GB / 16.00 GB
  Shell: /bin/zsh
Binaries:
  Node: 20.11.1 - /usr/local/bin/node
  Yarn: undefined - undefined
  npm: 10.2.4 - /usr/local/bin/npm
  pnpm: undefined - undefined
NPM Packages:
  @aws-amplify/backend: 1.0.4
  @aws-amplify/backend-cli: 1.1.1
  aws-amplify: 6.4.0
  aws-cdk: 2.149.0
  aws-cdk-lib: 2.149.0
  typescript: 5.5.3
AWS environment variables:
  AWS_STS_REGIONAL_ENDPOINTS = regional
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
No CDK environment variables
```

### Description

Followed the amplify tutorial and when creating the sandbox environment, it repeatedly loops back to 
"The given region has not been bootstrapped. Sign in to console as a Root user or Admin to complete the bootstrap process, then restart the sandbox."
The sandbox can never be started. 
I run the command
`npx ampx sandbox --profile amplify-policy`
The region for my profile is set to eu-central-1 and the user I log in as has Adminsitrator rights. 
Please see attached screenshots
![Amplify_Issue](https://github.com/user-attachments/assets/ff41e0a5-7cae-4b6b-804c-daa76acc0693)
![Amplify_CLI](https://github.com/user-attachments/assets/4bb40a4d-31cc-44a6-9390-4ceedb2b7b84)

**Comment by Flippittiflop** [comment]
Briefly I see other options when trying the sandbox, but it is quickly replaced by the pop-up. 
`CDKToolkit is already setup successfully in eu-central-1 Region. You may now close this browser window.`

**Comment by ykethan** [comment]
Hey @Flippittiflop, thank you for reaching out. Could you verify if the profiles stored in `~/.aws/config` and `~/.aws/credentials` may have a profile with a duplicate name?
As error appears to be similar to https://github.com/aws-amplify/amplify-backend/issues/1573

**Comment by Flippittiflop** [comment]
Yes, I saw that issue and I completely removed config and credentials files, then redid the sso config and the same problem occurs

**Comment by ykethan** [comment]
Hey @Flippittiflop, Could you run `npx aws-cdk@latest bootstrap aws://<your-aws-account-id>/<your-aws-region>` locally? Then re-run the sandbox command, does this show a similar error?

**Comment by alberto-anelli** [comment]
hi, im receiving a similar error following this tutorial https://docs.amplify.aws/react/start/account-setup/

The only AWS account available to you is: 717279690001
Using the account ID 717279690001
The only role available to you is: amplify-policy
Using the role name "amplify-policy"
CLI default client Region [None]: eu-central-1
CLI default output format [None]:
CLI profile name [amplify-policy-717279690001]: default

To use this profile, specify the profile name using --profile, as shown:

aws s3 ls --profile default


then i launch $ npx ampx sandbox --profile default
and i get 
InvalidCredentialError: Failed to load AWS credentials for profile 'default'
Resolution: To configure a new Amplify profile, use npx ampx configure profile.
Cause: Could not load credentials from any providers


the user i log in has AdministrativeAccess policies.

Could you help?

**Comment by alberto-anelli** [comment]
i run the command above npx aws-cdk@latest bootstrap aws://<your-aws-account-id>/<your-aws-region> and i get this error...

  Bootstrapping environment aws://717279690001/eu-central-1...
 ❌  Environment aws://717279690001/eu-central-1 failed bootstrapping: Error: Need to perform AWS calls for account 717279690001, but no credentials have been configured
 
 seems in the .aws folder i don't have credentials file, which commands was supposed to generate it?

thanks again

**Comment by Flippittiflop** [comment]
> Hey @Flippittiflop, Could you run `npx aws-cdk@latest bootstrap aws://<your-aws-account-id>/<your-aws-region>` locally? Then re-run the sandbox command, does this show a similar error?

Yeah, I get the credentials not configured because they for a separate account. 
`Need to perform AWS calls for account XXX36, but the current credentials are for XXX44`
This is how I structured my accounts, to run the command, does it have to be an SSO user inside the management account and not child accounts? 
![image](https://github.com/user-attachments/assets/2493656e-fe4e-4303-a1db-7cb343d52d0d)

**Comment by Flippittiflop** [comment]
> i run the command above npx aws-cdk@latest bootstrap aws:/// and i get this error...
> 
> Bootstrapping environment aws://717279690001/eu-central-1... ❌ Environment aws://717279690001/eu-central-1 failed bootstrapping: Error: Need to perform AWS calls for account 717279690001, but no credentials have been configured
> 
> seems in the .aws folder i don't have credentials file, which commands was supposed to generate it?
> 
> thanks again

Follow this @alberto-anelli 
[SSO Configuration](https://docs.amplify.aws/react/start/account-setup/)

![image](https://github.com/user-attachments/assets/4c066891-436c-4958-8d48-674bf2ff7c35)
