### ISSUE TITLE
'npx ampx sandbox' command throws error as 'unable to get local issuer certificate'

### ISSUE THREAD

**Issue by venkat-nscorp** [aws-amplify/amplify-backend#1880]
### Environment information

```plain text
Windows
```

### Description

Does anyone know why the 'npx ampx sandbox' command throws error as 'unable to get local issuer certificate'?
Whereas the 'npx create next-app' command doesn't have any problem. 

Also, the other AWS CLI commands like "aws s3 ls" working fine without any certificate error.

I know my network is behind the zscaler proxy and hence I created the environment variable 'AWS_CA_BUNDLE' and also updated the aws\.config file with the ca_bundle pointing to the zscaler pem certificate.

In spite of doing all these, it still complains of certificate error.

**Comment by ykethan** [comment]
Hey @venkat-nscorp, the support for proxy network is currently being tracked on https://github.com/aws-amplify/amplify-backend/issues/1555 as a feature request. Closing this issue as duplicate to prevent any miscommunication between issues. 
Do add a 👍 on the issue for help us prioritize this.
