### ISSUE TITLE
simpler cross-account deployment

### ISSUE THREAD

**Issue by neil-rubens** [aws-amplify/amplify-backend#1921]
### Environment information

```plain text
NA
```

### Description

Is there a **simpler** way to do cross-account deployment (am ok if it is less powerful); besides what is mentioned in the official [guide](https://docs.amplify.aws/react/deploy-and-host/fullstack-branching/cross-account-deployments/).

e.g. 
having the same setup on both accounts (dev, prod): repo and the connected amplify project
then to deploy to prod; I'd simply merging in changes from dev repo into prod repo

Are there any major limitation to the proposed approach.
Other **simpler** alternatives?

**Comment by ykethan** [comment]
Hey @neil-rubens, thank you for reaching. I would suggest posting this in our [Amplify discord community](https://discord.gg/amplify) as the community of developers using Amplify may suggest alternatives and their implementation on your use case.

**Comment by neil-rubens** [comment]
@ykethan  thank you for the advice; I've posted the same question on the discord:
https://discord.com/channels/705853757799399426/1286298818446495797/1286298818446495797

**Comment by Jay2113** [comment]
I am going to close this thread since we are tracking it on our community discord server. @neil-rubens I'll follow up with you on discord with suggestions to achieve the cross account workflow.
