### ISSUE TITLE
Custom SSL not showing for select it

### ISSUE THREAD

**Issue by karangoauto** [aws-amplify/amplify-backend#1928]
### Environment information

```plain text
-- nothing
```

### Describe the bug

When i try to select an certificated created for my custom domain, that already register on Route 53, it shows on network at list, but not show on select. I already tried click on refresh button but i still continue with this problem.

![image](https://github.com/user-attachments/assets/e0069e3d-825a-4817-8c69-8cabcce9bbd6)

### Reproduction steps

When i try to select an certificated created for my custom domain, that already register on Route 53, it shows on network at list, but not show on select. I already tried click on refresh button but i still continue with this problem.

**Comment by Jay2113** [comment]
Hi @karangoauto 👋 , thanks for raising this! Can you share the following information?
- Have you requested the custom certification from Amazon Certificate Manager (ACM) or have you imported it into ACM?
- Is the custom certificate requested or imported in the US East (N. Virginia) (us-east-1) Region?
- What is the key algorithm used by the certificate? (For example: RSA 2048, ECDSA P 256, ECDSA P 384)

**Comment by karangoauto** [comment]
Hi,

1- Have you requested the custom certification from Amazon Certificate Manager (ACM) or have you imported it into ACM?
- I imported it into ACM with my key and certificate.
![image](https://github.com/user-attachments/assets/9cb16ae6-d948-401c-a97a-205f1734b0b8)

2- Is the custom certificate requested or imported in the US East (N. Virginia) (us-east-1) Region?
- I checked in two regions. First, i used my amplify application in sa-east-1 and my certificated in sa-east-1. But i notice that the request always (whenever region) us-east-1. So, because this, i change my amplify application for sa-east-1 and my certificated too. But, i still facing same problem, not showing in select options.

3- What is the key algorithm used by the certificate? (For example: RSA 2048, ECDSA P 256, ECDSA P 384)
- RSA 2048


In my opinion, look more as frontend problem, because my certificated come in response request, but not show in select.

I wait your response @Jay2113

**Comment by karangoauto** [comment]
Good news. I found the problem. I created my route 53 subdomain different of my domain certificated. I have two similiars, and make me this mistake. Sorry about that, now works in amplify. @Jay2113

**Comment by karangoauto** [comment]
Good news. I found the problem. I created my route 53 subdomain different of my domain certificated. I have two similiars, and make me this mistake. Sorry about that, now works in amplify. @Jay2113

**Comment by Jay2113** [comment]
@karangoauto Thanks for sharing that information. I tried to recreate a similar setup in `sa-east-1` region and wasn't able to reproduce this issue. Do you observe any errors in the browser's developer console? Also, can you capture a HAR file and share it with us? This will be helpful for us to investigate the network requests and responses. Steps to capture the HAR file are outlined here: https://repost.aws/knowledge-center/support-case-browser-har-file.
