### ISSUE TITLE
Build Failed  - lockfile needs to be updated, but yarn was run with `--frozen-lockfile`.

### ISSUE THREAD

**Issue by suyesnet** [aws-amplify/amplify-backend#1930]
### Environment information

```plain text
[INFO]: yarn install v1.22.22

[INFO]: [1/4] Resolving packages...

[WARNING]: error Your lockfile needs to be updated, but yarn was run with `--frozen-lockfile`.
```

### Describe the bug

Build failed

### Reproduction steps

Build failed

**Comment by ykethan** [comment]
Hey @suyesnet, could you provide us some additional information on this? Is this occurring on our starter template? 
but to mitigate the error you will need to run `yarn install` locally and push the newly updated lock file to your repository.

**Comment by Jay2113** [comment]
Closing the thread due to inactivity. Feel free to reopen the thread if you are still running into this issue.
