### ISSUE TITLE
Build Error App built with Angular using Yarn Amplify Gen 2

### ISSUE THREAD

**Issue by moneeb0930** [aws-amplify/amplify-backend#1936]
### Environment information

```plain text
Amplify app id = du4dl9mwnya02
```

### Describe the bug

I'm encountering an error with a couple of builds, master and develop branches.  

Master is encountering this error, where it appears to not find the latest update to Amplify Gen 2.
![image](https://github.com/user-attachments/assets/f9cce137-3c17-4095-98f1-69bbe33fb2ed)

Develop 
![image](https://github.com/user-attachments/assets/4b8941bb-c6b9-43e8-9bc7-59ef15826ae7)

<details open>
  <summary>build settings</summary>
 
![image](https://github.com/user-attachments/assets/fddb1faa-1b75-4ca2-ace7-046135000953)

</details>

### Reproduction steps

deploy angular app using yarn

**Comment by Jay2113** [comment]
Hi @moneeb0930 👋 , thanks for reaching out! The Amplify app `du4dl9mwnya02` seems to be a Gen 1 app. Are you trying to migrate an existing Gen 1 app to Gen 2? 

Since Amplify Gen 1 and Gen 2 follow different architectural and tooling paradigms, you will need to use our upcoming migration tooling to move from a Gen 1 to Gen 2 app. You cannot use Amplify Gen 1 (Studio/CLI) in the same app as Gen 2.

**Comment by moneeb0930** [comment]
Hey, thanks for responding! I followed the instructions from the AWS Gen 2 upgrade webpage and was under the impression all went well with upgrade especially since I’m able to successfully build/run the app locally.

Is the migration tool is not ready for use currently? When it’s available, will it there be a notification sent? I’m guessing I’ll have to revert my project back to Gen 1 in order for deployments to work again.

**Comment by ykethan** [comment]
Hey @moneeb0930, we currently do not have a ETA on when the tool would be available but once this is out we will update our [documentation](https://docs.amplify.aws/) and [AWS announcements](https://aws.amazon.com/new/?whats-new-content-all.sort-by=item.additionalFields.postDateTime&whats-new-content-all.sort-order=desc&awsf.whats-new-categories=*all).

Closing the issue, do reach out if you require any assistance.
