### ISSUE TITLE
Rewrites and redirects do not work according to the documentation configuration for single pages.

### ISSUE THREAD

**Issue by faramir07** [aws-amplify/amplify-backend#1989]
### Environment information

```plain text
N/A
```

### Describe the bug

I encountered an issue with the configuration of rewrites and redirects in my single-page application (SPA). Despite following the documentation, the routes are not handled correctly, leading to a 404 error when directly accessing any URL other than the root. The app is using React Router, and it should handle all routes client-side, but the server is not redirecting requests properly to the index.html file as expected.

This is how the project routes are configured
![image](https://github.com/user-attachments/assets/7e916542-3425-4bd8-a98c-f7bc22e97bf8)

### Reproduction steps

and this is the configuration that must be done according to the documentation
![image](https://github.com/user-attachments/assets/fa5cbc5a-ec80-420b-b08a-7e8888004689).

Framework: React
Router: React Router v6.22.2
Hosting: AWS Amplify 
Build Tool: Vite v5.0.8
Node.js Version:  20.11.1
Operating System: Windows

**Comment by faramir07** [comment]
My co-worker restructured the routes and the problem was solved, I can not identify where the origin of the problem arose, I guess the problem arose from our side because I have not found a similar case. We will investigate a little more in depth to find out where the error is, after a week we could fix this case as a result.

**Comment by Jay2113** [comment]
@faramir07 I am closing this thread, as the issue has been resolved. Feel free to open a new GitHub issue if you encounter any other problems. Thanks!
