### ISSUE TITLE
Not able to connect DNS and host new app on amplify

### ISSUE THREAD

**Issue by Stratava-solutions** [aws-amplify/amplify-backend#2008]
### Environment information

```plain text
Next js application
```

### Describe the bug

Hi, i have hosted a app on AWS amplify, using godaddy purchased domain,  3-5 months back and the account got deactivated as it was unused, last week i activated the account and deleted all the previous hosted website and created new app using amplify but when i added dns to godaddy, but its taking old app and not able to create SSL on amplify its getting rejected, request customer support but not response, 

### Reproduction steps

Create a app on AWS amplify 
Dont pay the bill -> account deactivation
Pay bill and come back and host new app and delete all previous instances 
Add new DNS to godaddy 
Hurray old app gets hosted even after deleting Repo from github

**Comment by Jay2113** [comment]
Hi @Stratava-solutions 👋 , thanks for reaching out! Have you tried deleting the custom domain from the older Amplify app and then tried connecting it to a new Amplify app? Additionally, you will also need to delete the older DNS records (CNAME) for your domain from the GoDaddy DNS settings.

You can refer to this documentation to learn more about setting up a GoDaddy domain with Amplify Hosting: https://docs.aws.amazon.com/amplify/latest/userguide/to-add-a-custom-domain-managed-by-godaddy.html.
