### ISSUE TITLE
The service limit for number of GraphQL APIs has been reached

### ISSUE THREAD

**Issue by vinothj-aa** [aws-amplify/amplify-backend#2050]
### Environment information

```plain text
System:
  OS: macOS 14.5
  CPU: (10) arm64 Apple M1 Pro
  Memory: 132.98 MB / 16.00 GB
  Shell: /bin/zsh
Binaries:
  Node: 22.6.0 - ~/.nvm/versions/node/v22.6.0/bin/node
  Yarn: undefined - undefined
  npm: 10.8.2 - ~/.nvm/versions/node/v22.6.0/bin/npm
  pnpm: undefined - undefined
NPM Packages:
  @aws-amplify/auth-construct: 1.2.1
  @aws-amplify/backend: 1.0.5
  @aws-amplify/backend-auth: 1.1.1
  @aws-amplify/backend-cli: 1.2.3
  @aws-amplify/backend-data: 1.1.0
  @aws-amplify/backend-deployer: 1.0.4
  @aws-amplify/backend-function: 1.3.1
  @aws-amplify/backend-output-schemas: 1.1.0
  @aws-amplify/backend-output-storage: 1.0.2
  @aws-amplify/backend-secret: 1.0.1
  @aws-amplify/backend-storage: 1.0.4
  @aws-amplify/cli-core: 1.1.2
  @aws-amplify/client-config: 1.1.3
  @aws-amplify/deployed-backend-client: 1.3.0
  @aws-amplify/form-generator: 1.0.1
  @aws-amplify/model-generator: 1.0.4
  @aws-amplify/platform-core: 1.0.5
  @aws-amplify/plugin-types: 1.1.1
  @aws-amplify/sandbox: 1.1.2
  @aws-amplify/schema-generator: 1.2.1
  aws-amplify: 6.3.7
  aws-cdk: 2.147.0
  aws-cdk-lib: 2.147.0
  typescript: 5.5.2
AWS environment variables:
  AWS_STS_REGIONAL_ENDPOINTS = regional
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
No CDK environment variables
```

### Describe the bug

Amplify build fails with the following error:
The service limit for number of GraphQL APIs has been reached. (Service: AWSAppSync; Status Code: 400; Error Code: ApiLimitExceededException)

I'm unable to find appropriate information in Amplify or AppSync documents regarding ApiLimitExceededException.

### Reproduction steps

1. Create many custom types, custom queries & mutations with custom javascript resolvers.
2. The template size must be less than 1000000 bytes
3. Deploy a branch (feature/bug fix) and this error is encountered. (Even without any backend changes)

**Comment by Jay2113** [comment]
Hi @vinothj-aa 👋 , thanks for raising this! This particular error can occur if you have reached the APIs per region limit in AppSync. The default limit is 25 and you can request a higher limit from [here](https://console.aws.amazon.com/servicequotas/home/services/appsync/quotas/L-4DFA3D2F).

Docs: https://docs.aws.amazon.com/general/latest/gr/appsync.html#limits_appsync

**Comment by vinothj-aa** [comment]
> Hi @vinothj-aa 👋 , thanks for raising this! This particular error can occur if you have reached the APIs per region limit in AppSync. The default limit is 25 and you can request a higher limit from [here](https://console.aws.amazon.com/servicequotas/home/services/appsync/quotas/L-4DFA3D2F).
> 
> Docs: https://docs.aws.amazon.com/general/latest/gr/appsync.html#limits_appsync

Thank you

**Comment by ykethan** [comment]
Closing the issue, do reach out if you need any assistance.
