### ISSUE TITLE
npx ampx sandbox add auth 

### ISSUE THREAD

**Issue by yotchoun** [aws-amplify/amplify-backend#2068]
### Environment information

```plain text
System:
  OS: macOS 13.7
  CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Memory: 22.11 MB / 16.00 GB
  Shell: /bin/zsh
Binaries:
  Node: 18.20.3 - ~/.nvm/versions/node/v18.20.3/bin/node
  Yarn: 1.22.22 - /usr/local/bin/yarn
  npm: 10.7.0 - ~/.nvm/versions/node/v18.20.3/bin/npm
  pnpm: 9.11.0 - ~/.nvm/versions/node/v18.20.3/bin/pnpm
NPM Packages:
  @aws-amplify/auth-construct: 1.3.1
  @aws-amplify/backend: 1.3.0
  @aws-amplify/backend-auth: 1.2.0
  @aws-amplify/backend-cli: 1.2.8
  @aws-amplify/backend-data: 1.1.4
  @aws-amplify/backend-deployer: 1.1.4
  @aws-amplify/backend-function: 1.5.0
  @aws-amplify/backend-output-schemas: 1.2.0
  @aws-amplify/backend-output-storage: 1.1.2
  @aws-amplify/backend-secret: 1.1.3
  @aws-amplify/backend-storage: 1.2.0
  @aws-amplify/cli-core: 1.1.3
  @aws-amplify/client-config: 1.3.2
  @aws-amplify/deployed-backend-client: 1.4.1
  @aws-amplify/form-generator: 1.0.3
  @aws-amplify/model-generator: 1.0.8
  @aws-amplify/platform-core: 1.1.0
  @aws-amplify/plugin-types: 1.3.0
  @aws-amplify/sandbox: 1.2.2
  @aws-amplify/schema-generator: 1.2.4
  aws-amplify: 6.6.2
  aws-cdk: 2.160.0
  aws-cdk-lib: 2.160.0
  typescript: 5.6.2
AWS environment variables:
  AWS_STS_REGIONAL_ENDPOINTS = regional
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
No CDK environment variables
```

### Describe the feature

With amplify 1, I can give the names, I want for my resources in Cogito , AppSync, etc with the command **amplify add auth**
What is this command with Amplify 2? With **npx ampx sandbox** I do not control the name of my resources. 

### Use case

I would like something like **npx ampx sandbox add auth** or **npx ampx sandbox add api** or **npx ampx sandbox add storage**

**Comment by ykethan** [comment]
Hey @yotchoun, thank you for reaching out. The define methods provided in Amplify Gen 2, does provide the `name` property which should allow you to add a name for the resource.

For example on function and storage:
https://docs.amplify.aws/react/build-a-backend/functions/configure-functions/#name
https://docs.amplify.aws/react/build-a-backend/storage/set-up-storage/#building-your-storage-backend
