### ISSUE TITLE
Bootstrapping local sandbox to Amplify Console fails the CDKBuild stack, preventing new development. Says "The given region has not been bootstrapped."

### ISSUE THREAD

**Issue by bebopinbebop** [aws-amplify/amplify-backend#2082]
### Environment information

```plain text
System:
  OS: macOS 14.7
  CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Memory: 20.99 GB / 64.00 GB
  Shell: /bin/zsh
Binaries:
  Node: 18.20.4 - ~/.nvm/versions/node/v18.20.4/bin/node
  Yarn: undefined - undefined
  npm: 10.7.0 - ~/.nvm/versions/node/v18.20.4/bin/npm
  pnpm: undefined - undefined
NPM Packages:
  @aws-amplify/auth-construct: 1.3.1
  @aws-amplify/backend: 1.3.1
  @aws-amplify/backend-auth: 1.2.0
  @aws-amplify/backend-cli: 1.2.9
  @aws-amplify/backend-data: 1.1.4
  @aws-amplify/backend-deployer: 1.1.4
  @aws-amplify/backend-function: 1.5.0
  @aws-amplify/backend-output-schemas: 1.2.1
  @aws-amplify/backend-output-storage: 1.1.2
  @aws-amplify/backend-secret: 1.1.3
  @aws-amplify/backend-storage: 1.2.1
  @aws-amplify/cli-core: 1.1.3
  @aws-amplify/client-config: 1.4.0
  @aws-amplify/deployed-backend-client: 1.4.1
  @aws-amplify/form-generator: 1.0.3
  @aws-amplify/model-generator: 1.0.8
  @aws-amplify/platform-core: 1.1.0
  @aws-amplify/plugin-types: 1.3.0
  @aws-amplify/sandbox: 1.2.2
  @aws-amplify/schema-generator: 1.2.4
  aws-amplify: 6.6.3
  aws-cdk: 2.160.0
  aws-cdk-lib: 2.160.0
  typescript: 5.6.2
AWS environment variables:
  AWS_STS_REGIONAL_ENDPOINTS = regional
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
No CDK environment variables
```

### Describe the bug

I am following the Amplify Documentation for React Native here:
https://docs.amplify.aws/react-native/start/quickstart/

and I am on the step where I build a sandbox with:

```
npx ampx sandbox
```

and my terminal opens a webpage for me to login to my AWS console

<img width="693" alt="image" src="https://github.com/user-attachments/assets/f50529c6-00ec-49d2-b178-015494741596">

When I click to run it, it begins, then crashes on 2% here:
<img width="1259" alt="image" src="https://github.com/user-attachments/assets/0bc65f06-2d44-4b24-b290-8a1c226809b1">

I have tried everything that I could think of, but I do not know why its happening.

1.  I've created a user in IAM with admin privileges that I used to sign in to the aws cli using its Access Key and Secret Key.

2. I've made a local sso in the cli called "amplify-admin" from here: https://docs.amplify.aws/react-native/start/account-setup/ and ran 
```
npx ampx sandbox --profile amplify-admin
```
but it still fails and delivers a ROLLBACK_IN_PROGRESS

3. I even pushed my code to github and tried deploying it on the Amplify GUI online so that I can then pull the resources filed down into my project but that didn't do anything.

I tried following the suggestions here:
https://github.com/aws-amplify/amplify-backend/issues/1510

- I've tried removing the .credentials file
- changed the profile from sandbox to default, an access key profile and a SSO profile
- I installed the CDK CLI
- I've deleted all my old projects on Amplify in case there was some reproduction clashes

I mean, I do not think it has anything to do with the region, I think it has to do with the Gen2 upgrade with AWS and some legacy expectations not being fulfilled here.

I just want to start developing with QuickStart guide so I can move my project over, and this is preventing me from doing so. Any help would be appreciated.

### Reproduction steps

run

```
npx ampx sandbox
```

and you will be asked to sign in to your profile to bootstrap the account. Mine does not work.

**Comment by josefaidt** [comment]
Hey @bebopinbebop :wave: thanks for raising this! While we work to improve the error messaging in the console, can you navigate to the CloudFormation console and poke through the "Events" tab for the `CDKToolkit` stack? This error can surface if the stack was previously deleted, where the corresponding IAM roles and S3 bucket created for assets are not also deleted.

**Comment by ykethan** [comment]
Glad to hear you were able to mitigate the issue. Closing the thread, do let us know if you are still experiencing this.
