### ISSUE TITLE
Getting Empty Array from list() on my localhost, but when I deploy the app the same code fetches data.

### ISSUE THREAD

**Issue by navneetsingh-cpu** [aws-amplify/amplify-backend#2088]
### Environment information

```plain text
System:
  OS: Windows 10 10.0.19045
  CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Memory: 2.25 GB / 15.89 GB
Binaries:
  Node: 20.18.0 - C:\Program Files\nodejs\node.EXE      
  Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD        
  npm: 10.9.0 - C:\Program Files\nodejs\npm.CMD
  pnpm: undefined - undefined
NPM Packages:
  @aws-amplify/auth-construct: 1.3.1
  @aws-amplify/backend: 1.3.2
  @aws-amplify/backend-auth: 1.2.0
  @aws-amplify/backend-cli: 1.2.9
  @aws-amplify/backend-data: 1.1.4
  @aws-amplify/backend-deployer: 1.1.4
  @aws-amplify/backend-function: 1.5.0
  @aws-amplify/backend-output-schemas: 1.3.0
  @aws-amplify/backend-output-storage: 1.1.2
  @aws-amplify/backend-secret: 1.1.3
  @aws-amplify/backend-storage: 1.2.1
  @aws-amplify/cli-core: 1.1.3
  @aws-amplify/client-config: 1.4.0
  @aws-amplify/deployed-backend-client: 1.4.1
  @aws-amplify/form-generator: 1.0.3
  @aws-amplify/model-generator: 1.0.8
  @aws-amplify/platform-core: 1.1.0
  @aws-amplify/plugin-types: 1.3.0
  @aws-amplify/sandbox: 1.2.3
  @aws-amplify/schema-generator: 1.2.4
  aws-amplify: 6.6.4
  aws-cdk: 2.161.1
  aws-cdk-lib: 2.161.1
  typescript: 5.5.4
AWS environment variables:
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_REGION = us-east-1
  AWS_SDK_LOAD_CONFIG = 1
  AWS_STS_REGIONAL_ENDPOINTS = regional
No CDK environment variables
```

### Describe the bug

In my angular app I am trying to just fetch the data locally, but it returns an empty array to me 

**resource.ts**

```
const schema = a.schema(
  {
    Services: a
      .model({
        id: a.id(),
        service_id: a.string(),
        name: a.string(),
        description: a.string(),
        isNew: a.boolean(),
        orignal_price: a.float(),
        discounted_price: a.float(),
        icon: a.string(),
        num_of_listings: a.integer()
      })
      .authorization((allow) => [allow.publicApiKey()]),
  }
);

export type Schema = ClientSchema<typeof schema>;

export const data = defineData({
  schema,
  authorizationModes: {
    defaultAuthorizationMode: 'apiKey',
    apiKeyAuthorizationMode: { expiresInDays: 30 }
  },
});
```
**Angular Typescript code**
 ```
import type { Schema } from '../../../../../amplify/data/resource'
import { generateClient } from 'aws-amplify/data'

const client = generateClient<Schema>({
  authMode: 'apiKey',
});

   const { data, errors } = await client.models.Services.list({
      authMode: 'apiKey',
    });
    console.log('data', data); // []   // Only on localhost:4200
    console.log('errors', errors); // undefined
    this.services = data;
```
**main.ts**
```
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

import { AppModule } from './app/app.module';

import { Amplify } from 'aws-amplify';
import outputs from '../amplify_outputs.json';


platformBrowserDynamic().bootstrapModule(AppModule)
  .catch(err => console.error(err));

Amplify.configure(outputs);
```

**Graphql response**

```
{
    "data": {
        "listServices": {
            "items": [],
            "nextToken": null,
            "__typename": "ModelServicesConnection"
        }
    }
}
```

however on building the app and hosting it on amplify I see the same source code fetching the data
on https://main.*.amplifyapp.com/

### Reproduction steps

![image](https://github.com/user-attachments/assets/969ff35f-9019-45f3-ae58-4ee46a35f9b3)
![image](https://github.com/user-attachments/assets/e1b2431a-5975-491d-9e87-58d0e0b14aaa)

**Comment by stocaaro** [comment]
Hello @navneetsingh-cpu,

Sorry your having trouble. If you are using the `npx ampx sandbox` command to run your local environment, then the resources your accessing locally are connected to a different backend than you production deployed resources.

If you are not using the sandbox pattern, can you describe how you generated the `amplify_outputs.json` file that you're using locally?

If you are using sandbox, is there something about your application that would lead you to expect that it would have the records your seeing in the production backend?

I've seen similar issues on a shared backend because of permissions differences, but using an API key for permissions, I would not expect that to be the case here.

Thanks,
Aaron

**Comment by navneetsingh-cpu** [comment]
hi @stocaaro ,
Thanks for your reply, I generated `amplify_outputs.json` using `npx ampx sandbox` .

I was under the impression that sandbox would have the same records that are on amplify. So that I can debug and see it locally too, 
![image](https://github.com/user-attachments/assets/606cb375-3ba0-4bb3-b27a-395eebd4ea6c)

Is there a way to populate the data on sandbox or use a shared backend ? can you please share documentation link ?

Also, when i run sandbox I see this in console
```

✨  Total time: 5.73s

[Sandbox] Watching for file changes...
File written: amplify_outputs.json
```
But I dont see a cloud formation stack in aws console.

Thanks,
Navneet

**Comment by stocaaro** [comment]
Hi @navneetsingh-cpu,

Each of your backends has its own data. This isolation is meant to make your local development safe so your not introducing test/dev data into your production application.

In the [Quickstart guide](https://docs.amplify.aws/react/start/quickstart/#4-set-up-local-environment) there's an example of downloading the `amplify_outputs.json` from the AWS Console and using it to connect your local environment to the backend built by the hosting build process.

If your using a sandbox for local development, when you look at your [sandbox environments](https://docs.amplify.aws/react/deploy-and-host/sandbox-environments/setup/#manage-sandbox-environments) in the console, there's not a strong link across to the AppSync backend that supports your sandbox, but you can look at AppSync and select the endpoint that corresponds to the AppSync endpoint configured in the `amplify_outputs.json` generated by the sandbox command.

You could write a script to bootstrap a backend with data, calling the API to fill in data, or write a script to sync data from one backend to another.

Hope this helps.

Thanks,
Aaron

**Comment by navneetsingh-cpu** [comment]
Great! downloading the amplify_outputs.json , was what I needed. Thanks!
