### ISSUE TITLE
Stack [CDKToolkit] already exists

### ISSUE THREAD

**Issue by regularuserrr** [aws-amplify/amplify-backend#2092]
### Environment information

```plain text
{
  "name": "aws-amplify-gen2",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@aws-amplify/ui-react": "^6.1.13",
    "aws-amplify": "^6.4.0",
    "next": "14.1.1",
    "react": "^18",
    "react-dom": "^18"
  },
  "devDependencies": {
    "@aws-amplify/backend": "^1.2.1",
    "@aws-amplify/backend-cli": "^1.2.6",
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "aws-cdk": "^2",
    "aws-cdk-lib": "^2",
    "constructs": "^10.3.0",
    "esbuild": "^0.23.1",
    "tsx": "^4.19.0",
    "typescript": "^5.6.2"
  }
}
```

### Describe the bug

When tying to deploy amplify template https://github.com/aws-samples/amplify-next-template, got build error Stack [CDKToolkit] already exists.
![Знімок екрана (411)](https://github.com/user-attachments/assets/15b1c977-71f4-41dd-8bce-0f15f4630e25)

### Reproduction steps

1.Go to https://eu-central-1.console.aws.amazon.com/amplify/create.
2.Select Github and also select repo with template and branch
3.In app settings don't do anything
4.Click Save and deploy

**Comment by ykethan** [comment]
Hey @regularuserrr, could you try running one of the commands provided in this document and let us know if this mitigated the issue. https://docs.amplify.aws/react/build-a-backend/troubleshooting/stack-cdktoolkit-already-exists/

**Comment by regularuserrr** [comment]
> Hey @regularuserrr, could you try running one of the commands provided in this document and let us know if this mitigated the issue. https://docs.amplify.aws/react/build-a-backend/troubleshooting/stack-cdktoolkit-already-exists/

I used this in Cloud Shell cdk bootstrap aws://$(aws sts get-caller-identity --query Account --output text)/$AWS_REGION
and I got this error
⏳  Bootstrapping environment aws://654654329462/eu-central-1...
Trusted accounts for deployment: (none)
Trusted accounts for lookup: (none)
Using default execution policy of 'arn:aws:iam::aws:policy/AdministratorAccess'. Pass '--cloudformation-execution-policies' to customize.
CDKToolkit: creating CloudFormation changeset...
7:40:07 AM | CREATE_FAILED        | AWS::S3::Bucket         | StagingBucket
Resource handler returned message: "cdk-hnb659fds-assets-654654329462-eu-central-1 already exists (Service: S3, Status Code: 0, Request ID: null)" (RequestToken: bb187aab-7eaf-6b59-37d
9-41dfd3c832dc, HandlerErrorCode: AlreadyExists)
 
❌  Environment aws://654654329462/eu-central-1 failed bootstrapping: Error: The stack named CDKToolkit failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Resource handler returned message: "cdk-hnb659fds-assets-654654329462-eu-central-1 already exists (Service: S3, Status Code: 0, Request ID: null)" (RequestToken: bb187aab-7eaf-6b59-37d9-41dfd3c832dc, HandlerErrorCode: AlreadyExists)
    at FullCloudFormationDeployment.monitorDeployment (/usr/local/lib/node_modules/aws-cdk/lib/index.js:455:10568)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /usr/local/lib/node_modules/aws-cdk/lib/index.js:460:2329
    at async Promise.all (index 0)
    at async CdkToolkit.bootstrap (/usr/local/lib/node_modules/aws-cdk/lib/index.js:460:2174)
    at async exec4 (/usr/local/lib/node_modules/aws-cdk/lib/index.js:513:54331)
 
The stack named CDKToolkit failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Resource handler returned message: "cdk-hnb659fds-assets-654654329462-eu-central-1 already exists (Service: S3, Status Code: 0, Request ID: null)" (RequestToken: bb187aab-7eaf-6b59-37d9-41dfd3c832dc, HandlerErrorCode: AlreadyExists)

**Comment by regularuserrr** [comment]
6:42:27 AM | CREATE_FAILED        | AWS::IAM::Role          | LookupRole
Resource handler returned message: "User: arn:aws:sts::654654329462:assumed-role/AWSReservedSSO_PowerUserAccess_48601e0c275c936b/r_didusenko is not authorized to perform: iam:PutRolePo
licy on resource: role cdk-hnb659fds-lookup-role-654654329462-eu-central-1 because no identity-based policy allows the iam:PutRolePolicy action (Service: Iam, Status Code: 403, Request
ID: 509ab278-d542-4603-bce4-10fd047bc7cf)" (RequestToken: c3c0f37d-8007-3cae-41c5-cd852bb08a82, HandlerErrorCode: AccessDenied)

 ❌  Environment aws://654654329462/eu-central-1 failed bootstrapping: Error: The stack named CDKToolkit failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Resource handler returned message: "User: arn:aws:sts::654654329462:assumed-role/AWSReservedSSO_PowerUserAccess_48601e0c275c936b/r_didusenko is not authorized to perform: iam:PutRolePolicy on resource: role cdk-hnb659fds-lookup-role-654654329462-eu-central-1 because no identity-based policy allows the iam:PutRolePolicy action (Service: Iam, Status Code: 403, Request ID: 509ab278-d542-4603-bce4-10fd047bc7cf)" (RequestToken: c3c0f37d-8007-3cae-41c5-cd852bb08a82, HandlerErrorCode: AccessDenied)
    at FullCloudFormationDeployment.monitorDeployment (/usr/lib/node_modules/aws-cdk/lib/index.js:458:10567)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /usr/lib/node_modules/aws-cdk/lib/index.js:463:2348
    at async Promise.all (index 0)
    at async CdkToolkit.bootstrap (/usr/lib/node_modules/aws-cdk/lib/index.js:463:2193)
    at async exec4 (/usr/lib/node_modules/aws-cdk/lib/index.js:516:54490)

The stack named CDKToolkit failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Resource handler returned message: "User: arn:aws:sts::654654329462:assumed-role/AWSReservedSSO_PowerUserAccess_48601e0c275c936b/r_didusenko is not authorized to perform: iam:PutRolePolicy on resource: role cdk-hnb659fds-lookup-role-654654329462-eu-central-1 because no identity-based policy allows the iam:PutRolePolicy action (Service: Iam, Status Code: 403, Request ID: 509ab278-d542-4603-bce4-10fd047bc7cf)" (RequestToken: c3c0f37d-8007-3cae-41c5-cd852bb08a82, HandlerErrorCode: AccessDenied)

**Comment by regularuserrr** [comment]
Now I got this
