### ISSUE TITLE
Can I use next js api to have streaming responses 

### ISSUE THREAD

**Issue by regularuserrr** [aws-amplify/amplify-backend#2112]
### Environment information

```plain text
next 14
```

### Describe the bug

Can I use next js api to have streaming responses without lambda?

### Reproduction steps

none

**Comment by Jay2113** [comment]
Hi @regularuserrr 👋 thanks for reaching out. Amplify Hosting currently does not support streaming with Next.js and we are tracking it as a feature request here: https://github.com/aws-amplify/amplify-hosting/issues/3843.

I'd recommend upvoting and sharing your use case on it as it will help our team prioritize the feature.

Additionally, Amplify Hosting provides a fully managed hosting infrastructure and thus the compute functions cannot be modified or removed to support the use case of streaming responses.
