### ISSUE TITLE
Trigger graphql subscription without graphql mutation

### ISSUE THREAD

**Issue by nam-truong-le** [aws-amplify/amplify-backend#2114]
### Environment information

```plain text
System:
  OS: macOS 15.0.1
  CPU: (8) arm64 Apple M3
  Memory: 83.11 MB / 24.00 GB
  Shell: /bin/zsh
Binaries:
  Node: 20.17.0 - ~/.nvm/versions/node/v20.17.0/bin/node
  Yarn: undefined - undefined
  npm: 10.8.2 - ~/.nvm/versions/node/v20.17.0/bin/npm
  pnpm: 9.12.1 - ~/.nvm/versions/node/v20.17.0/bin/pnpm
NPM Packages:
  @aws-amplify/auth-construct: 1.3.1
  @aws-amplify/backend: 1.4.0
  @aws-amplify/backend-auth: 1.2.0
  @aws-amplify/backend-cli: 1.2.9
  @aws-amplify/backend-data: 1.1.4
  @aws-amplify/backend-deployer: 1.1.4
  @aws-amplify/backend-function: 1.6.0
  @aws-amplify/backend-output-schemas: 1.3.0
  @aws-amplify/backend-output-storage: 1.1.2
  @aws-amplify/backend-secret: 1.1.3
  @aws-amplify/backend-storage: 1.2.1
  @aws-amplify/cli-core: 1.1.3
  @aws-amplify/client-config: 1.4.0
  @aws-amplify/deployed-backend-client: 1.4.1
  @aws-amplify/form-generator: 1.0.3
  @aws-amplify/model-generator: 1.0.8
  @aws-amplify/platform-core: 1.1.0
  @aws-amplify/plugin-types: 1.3.0
  @aws-amplify/sandbox: 1.2.2
  @aws-amplify/schema-generator: 1.2.4
  aws-amplify: 6.6.4
  aws-cdk: 2.162.1
  aws-cdk-lib: 2.158.0
  typescript: 5.6.3
AWS environment variables:
  AWS_STS_REGIONAL_ENDPOINTS = regional
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
No CDK environment variables
```

### Describe the feature

Notifying Frontend Subscribers After Lambda Trigger

### Use case

Let's say I've got an event source that triggers my Lambda (like a webhook from an external service). After that, I update some data in DynamoDB. How can I let subscribers on the frontend know about the changes? Thanks!

**Comment by ykethan** [comment]
Hey @nam-truong-le, thank you for reaching. You may have to use [DynamoDB streams](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/streamsmain.html) with a trigger to Lambda that contains your notification mechanism or you could setup the DynamoDB streams to trigger a lambda that invokes a GraphQL mutation(set to datasource as NONE) this would essentially pass the data to subscriptions without performing any actions on a DynamoDB table.

**Comment by nam-truong-le** [comment]
>a lambda that invokes a GraphQL mutation

How to invoke a GraphQL mutation (created by amplify) in lambda?

**Comment by ykethan** [comment]
Hey, the [Grant Lambda function access to API and Data](https://docs.amplify.aws/react/build-a-backend/data/customize-authz/grant-lambda-function-access-to-api/) documentation should provide an example.

**Comment by nam-truong-le** [comment]
Hi, I'm following the documentation but looks like attributes that reference to `a.customType` aren't added to client code:

<img width="1160" alt="Bildschirmfoto 2024-10-19 um 09 43 24" src="https://github.com/user-attachments/assets/c1bf6b95-a628-4719-8b6d-a6b16ba85469">

**Comment by chrisbonifacio** [comment]
Hi @nam-truong-le 👋 thanks for raising this issue. Currently it's not possible to trigger an AppSync subscription without executing a graphql mutation through AppSync.

Also, in the interest of organization and tracking issues, can you please create a separate github issue in the [amplify-category-api](https://github.com/aws-amplify/amplify-category-api/issues?q=is:issue+is:open) for your schema issue?

We want to keep this thread focused on the original issue

**Comment by nam-truong-le** [comment]
Create https://github.com/aws-amplify/amplify-category-api/issues/2974 to report the issue that null data is sent to subscriber.

**Comment by nam-truong-le** [comment]
Created https://github.com/aws-amplify/amplify-cli/issues/13987 to report the issue that attributes are missing in generated client code.
