### ISSUE TITLE
Fix AWS Amplify console resource hog

### ISSUE THREAD

**Issue by ccks01** [aws-amplify/amplify-backend#2125]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have removed any sensitive information from my code snippets and submission.

### Amplify Hosting feature

Not Applicable

### Is your feature request related to a problem? Please describe:

It eats 100% of my CPU and why the hell you are query the same resource four times in a second?

### Describe how you'd like this feature to work

<img width="746" alt="Screenshot 2024-10-07 at 08 25 28" src="https://github.com/user-attachments/assets/da017cc7-ee53-4302-a5bb-585fd3c3dad2">
<img width="685" alt="Screenshot 2024-10-09 at 10 10 32" src="https://github.com/user-attachments/assets/22a08f92-6153-4fa2-90b3-da0112a0ef1e">

**Comment by Jay2113** [comment]
@ccks01 👋 , we have deployed a fix for this issue. Can you please verify if the CPU utilization metric has improved?

**Comment by Jay2113** [comment]
@ccks01 👋 A quick update here, this issue is persistent and we are tracking it as a bug here #1180 . Please subscribe to it to monitor and track status updates. Thank you.
