### ISSUE TITLE
Amplify Console Gen 2 Data Manager shows "Unexpected Application Error!"

### ISSUE THREAD

**Issue by MagiciMan** [aws-amplify/amplify-backend#2130]
### Environment information

```plain text
System:
  OS: macOS 14.6.1
  CPU: (8) arm64 Apple M1
  Memory: 113.64 MB / 16.00 GB
  Shell: /bin/zsh
Binaries:
  Node: 21.5.0 - ~/.nvm/versions/node/v21.5.0/bin/node
  Yarn: undefined - undefined
  npm: 10.8.3 - ~/.nvm/versions/node/v21.5.0/bin/npm
  pnpm: undefined - undefined
NPM Packages:
  @aws-amplify/auth-construct: 1.3.0
  @aws-amplify/backend: 1.1.1
  @aws-amplify/backend-auth: 1.1.3
  @aws-amplify/backend-cli: 1.2.5
  @aws-amplify/backend-data: 1.1.2
  @aws-amplify/backend-deployer: 1.1.0
  @aws-amplify/backend-function: 1.3.4
  @aws-amplify/backend-output-schemas: 1.2.0
  @aws-amplify/backend-output-storage: 1.1.1
  @aws-amplify/backend-secret: 1.1.0
  @aws-amplify/backend-storage: 1.1.2
  @aws-amplify/cli-core: 1.1.2
  @aws-amplify/client-config: 1.2.1
  @aws-amplify/deployed-backend-client: 1.4.0
  @aws-amplify/form-generator: 1.0.1
  @aws-amplify/model-generator: 1.0.5
  @aws-amplify/platform-core: 1.0.6
  @aws-amplify/plugin-types: 1.2.1
  @aws-amplify/sandbox: 1.2.0
  @aws-amplify/schema-generator: 1.2.1
  aws-amplify: 6.6.2
  aws-cdk: 2.154.1
  aws-cdk-lib: 2.154.1
  typescript: 5.5.4
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!                                                                            !!
!!  Node 21 has reached end-of-life on 2024-06-01 and is not supported.       !!
!!  Please upgrade to a supported node version as soon as possible.           !!
!!                                                                            !!
!!  This software is currently running on node v21.5.0.                       !!
!!  As of the current release of this software, supported node releases are:  !!
!!  - ^22.0.0 (Planned end-of-life: 2027-04-30)                               !!
!!  - ^20.0.0 (Planned end-of-life: 2026-04-30)                               !!
!!  - ^18.0.0 (Planned end-of-life: 2025-04-30)                               !!
!!                                                                            !!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
AWS environment variables:
  AWS_STS_REGIONAL_ENDPOINTS = regional
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
No CDK environment variables
npm notice
npm notice New minor version of npm available! 10.8.3 -> 10.9.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.9.0
npm notice To update run: npm install -g npm@10.9.0
npm notice
npm notice
npm notice New minor version of npm available! 10.8.3 -> 10.9.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.9.0
npm notice To update run: npm install -g npm@10.9.0
npm notice
```

### Describe the bug

I can't access data manager in my feature branch deployment that has been auto build using the regex "feature/".

My feature deployment branches seem to work just fine, but I can't access the dynamoDB tables through the data manger. 

Autodeployed using a regex that doesn't have "/" , such is "build*" works fine.

<img width="746" alt="image" src="https://github.com/user-attachments/assets/0d236e19-9b47-42c4-9d75-6838cede16bf">

### Reproduction steps

1- I create two new brancehs, feature/branchname gets build automatically.

2- Build succeeds, I create an account in my app and log in. 

3-Add data through the app, data is presistent after log in loug out

4- loging into aws amplify console, go to feature branch and data manager, get "Unexpected Application Error!
404 Not Found"

**Comment by Jay2113** [comment]
Hi @MagiciMan 👋 , thanks for reaching out. Can you share the following information:
- The URL that shows the 404 error in the browser
- The `package.json` file
- Did the issue recently started occurring? Potentially after upgrading any of the dependencies?

**Comment by MagiciMan** [comment]
@Jay2113  Here you go : 

1- This is for a branch called feature/dbbot that has this problem, any branch with feature/* has the same issue: https://us-west-2.console.aws.amazon.com/amplify/apps/d30rgxlqc276wa/branches/feature%2Fdbbot/data/data-manager

2- Here is my package.json 

`{
  "name": "amplify-vite-react-template",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "tsc && vite build",
    "lint": "eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 0",
    "preview": "vite preview",
    "test:e2e": "cypress open",
    "test:e2e:headless": "start-server-and-test dev http://localhost:5173 'cypress run'"
  },
  "dependencies": {
    "@ant-design/charts": "^2.2.1",
    "@ant-design/icons": "^5.4.0",
    "@aws-amplify/interactions": "^6.0.48",
    "@types/plotly.js": "^2.33.4",
    "@types/react-plotly.js": "^2.6.3",
    "antd": "^5.20.5",
    "aws-amplify": "^6.6.2",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-plotly.js": "^2.6.0",
    "react-plotlyjs": "^0.4.4",
    "reactflow": "^11.11.4",
    "recharts": "^2.12.7",
    "styled-components": "^6.1.13"
  },
  "devDependencies": {
    "@aws-amplify/backend": "^1.1.1",
    "@aws-amplify/backend-cli": "^1.2.4",
    "@types/react": "^18.2.66",
    "@types/react-dom": "^18.2.22",
    "@typescript-eslint/eslint-plugin": "^7.2.0",
    "@typescript-eslint/parser": "^7.2.0",
    "@vitejs/plugin-react": "^4.2.1",
    "aws-cdk": "^2.138.0",
    "aws-cdk-lib": "^2.138.0",
    "constructs": "^10.3.0",
    "cypress": "^13.15.0",
    "esbuild": "^0.20.2",
    "eslint": "^8.57.0",
    "eslint-plugin-react-hooks": "^4.6.0",
    "eslint-plugin-react-refresh": "^0.4.6",
    "start-server-and-test": "^2.0.8",
    "tsx": "^4.7.2",
    "typescript": "^5.4.5",
    "vite": "^5.2.0"
  }
}
`

3- I just recently enabled auto build on feature/* , so it's recent for me. I tired auto build on branches that didn't have "/" in their name and it worked just fine. My wild guess is that something can't parse the URL right.

**Comment by Jay2113** [comment]
Thanks for sharing the additional information. I was able to reproduce this behavior and marking it as a bug.

**Comment by ykethan** [comment]
Closing the issue as a fix has been released. Do reach out if you are still experiencing this issue.

**Comment by Jay2113** [comment]
@MagiciMan 👋 we have deployed a fix for this issue. Can you please verify?
