### ISSUE TITLE
AWS amplify manual deployment continous pending state for long period of time

### ISSUE THREAD

**Issue by sawrubgupta** [aws-amplify/amplify-backend#2137]
### Environment information

```plain text
npx ampx info
```

### Describe the bug

![image](https://github.com/user-attachments/assets/00d9422a-5560-4d2c-a11d-117b95ab35c5)

I am trying to do manual aws amplify deployment with react build, I do everyday but I dont face any issue but today its deployment status is coming as pending for past 3 hours, when I am trying more manual deployment, below error is coming 

The last job(deployment) 64 was not finished, please wait until it finish or use StopJob operation to cancel it before creating a new deployment.

How to clear old deployment and do latest deployment ?

* my account doenst have any billing pending
*  I am using react build folder for deploymeny
* Till yesterday, deployment was working fine but today is only going in pending state

### Reproduction steps

![image](https://github.com/user-attachments/assets/b91fe527-4a59-4703-881c-d7635a4186dc)

this is error, keep on coming up.

**Comment by Jay2113** [comment]
Hi @sawrubgupta 👋 , thanks for reaching out. To unblock your current deployments in `pending` state, run the following [stop-job](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/amplify/stop-job.html) command using the AWS CLI for each frozen deployment:

`aws amplify stop-job --app-id {VALUE} --branch-name {VALUE} --job-id {VALUE}`

This will cancel the pending jobs and you can then retry a new manual deployment. Additionally, refer to this [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/main/FAQ.md#deployments-or-jobs-are-stuck-with-a-pending-status-in-the-amplify-console) to learn more about why manual deployments could be failing.

**Comment by Jay2113** [comment]
Closing this thread as we have shared the workaround to unblock the deployments and best practices for using manual deployments.
