### ISSUE TITLE
Amplify Environment Cloning stuck - just loading nothing happens...

### ISSUE THREAD

**Issue by aranbit** [aws-amplify/amplify-backend#2140]
### Environment information

```plain text
...
```

### Describe the bug

We a have a multi tenant(silo) application that we developed using AWS Amplify, so every client of our has a backend and frontend environment of its own, right now were trying to open an environment to new clients like we always did and do - by cloning an existing backend environment and adding a new github branch for the frontend to connect backend to Amplify hosting.

This time when trying to clone an environment it just loads continuously for hours and once I refresh the page it disappears and nothing was created...(I attached a photo of the loading message that is initially shown and still for hours...

I need help urgently 🙏

### Reproduction steps

<img width="1114" alt="Screenshot 2024-10-22 at 21 07 28" src="https://github.com/user-attachments/assets/94306536-7c12-4d31-a847-f32d9eed30de">

I simply went to Amplify backend environments -> mange -> clone -> typing new environment name -> clone

This used to work all the time, I have used it plently but right know it's just stuck loading and doing nothing for some reason...

**Comment by aranbit** [comment]
Hi, there is no CloudFormation stack, but I did get a browser error: 

POST https://amplifybackend.us-east-1.amazonaws.com/backend/d3sgmyk8trust9/environments/km/clone 400 (Bad Request)

ncaught at  TypeError: Cannot read properties of undefined (reading 'id')
    at https://a.b.cdn.console.awsstatic.com/a/v1/QWSBNGRSTBJJICWBT3TWKULJEEKZUXWWACYGVAWZIAGAIGKVSKCA/main.js:1:387208
    at Array.map (<anonymous>)
    at alerts (https://a.b.cdn.console.awsstatic.com/a/v1/QWSBNGRSTBJJICWBT3TWKULJEEKZUXWWACYGVAWZIAGAIGKVSKCA/main.js:1:387169)
    at https://a.b.cdn.console.awsstatic.com/a/v1/YXBPAVFJL4HUPBF7TPLYSBXNVQW4XZK4ACFBG4TK75HRL7ABGZOQ/vendors.js:59:30528
    at g (https://a.b.cdn.console.awsstatic.com/a/v1/YXBPAVFJL4HUPBF7TPLYSBXNVQW4XZK4ACFBG4TK75HRL7ABGZOQ/vendors.js:59:29607)
    at https://a.b.cdn.console.awsstatic.com/a/v1/YXBPAVFJL4HUPBF7TPLYSBXNVQW4XZK4ACFBG4TK75HRL7ABGZOQ/vendors.js:59:15954
    at dispatch (https://a.b.cdn.console.awsstatic.com/a/v1/YXBPAVFJL4HUPBF7TPLYSBXNVQW4XZK4ACFBG4TK75HRL7ABGZOQ/vendors.js:59:31122)
    at https://a.b.cdn.console.awsstatic.com/a/v1/YXBPAVFJL4HUPBF7TPLYSBXNVQW4XZK4ACFBG4TK75HRL7ABGZOQ/vendors.js:59:28091
    at https://a.b.cdn.console.awsstatic.com/a/v1/YXBPAVFJL4HUPBF7TPLYSBXNVQW4XZK4ACFBG4TK75HRL7ABGZOQ/vendors.js:59:11187
    at a (https://a.b.cdn.console.awsstatic.com/a/v1/YXBPAVFJL4HUPBF7TPLYSBXNVQW4XZK4ACFBG4TK75HRL7ABGZOQ/vendors.js:59:24220)

Can you explain the workaround a bit more, where and how exactly do I use the cli command to clone an environment?

**Comment by ykethan** [comment]
Hey @aranbit, thank you for the information. To clone the environment using amplify cli. 
1. ensure the Amplify CLI is installed you check by running `amplify -v` on your local terminal or install the CLI using the setup instructions [here](https://docs.amplify.aws/gen1/react/start/getting-started/installation/)
2. pull the backend you would like clone to your local machine using the command present under the local setup instructions and running this in your terminal
![image](https://github.com/user-attachments/assets/0cfc8626-b1b9-4f1b-b3c4-c4749677e323)
3. after the project had been setup locally, run `amplify add env` and input the prompts provided
4. then `amplify push` to push the resources

**Comment by aranbit** [comment]
I successfully managed to clone an environment using the steps you mentioned, thank you !
Will you be able to fix the issue with cloning the environment from the AWS Amplify UI?(I added the console errors in the previous comment)

**Comment by ykethan** [comment]
@aranbit the Amplify team will be working on improvements around this feature. Marking as bug to track this behavior.

**Comment by aranbit** [comment]
Ok, thank you for the temporary other way for now, looking forward to hearing about this fix !

**Comment by Jay2113** [comment]
@aranbit 👋 , our recommendation going forward will be to use the Amplify CLI instead of the console flow to clone a backend environment. Steps will remain the same as stated [here](https://github.com/aws-amplify/amplify-backend/issues/2140#issuecomment-2435490326).
