### ISSUE TITLE
Trying to migrate to Github Application Failing

### ISSUE THREAD

**Issue by ishansharma** [aws-amplify/amplify-backend#2156]
### Environment information

```plain text
zsh: command not found: npx
```

### Describe the bug

I'm unable to connect Amplify to AWS Github app, this is blocking my site's build.

### Reproduction steps

1. Login to Amplify
2. Go to application, click "Start migration" on "Migrate to our GitHub app" notice
3. On next screen, click "Authorize Github App"
4. Authorize on GitHub, it then returns to AWS console where the message is not "Checking status..."
5. Getting redirected to GitHub, showing a 404. URL is `https://github.com/apps/aws-amplify-us-west-1/installations/new/installations/new?state=<state parameter removed, I'm assuming this is security sensitive>`

**Comment by ishansharma** [comment]
Yeah, this is a bug on Amplify's side. I went back and noticed the URL had 2 instances of `installations/new`. Removed the duplicate one and opened the page, I was able to connect.

**Comment by Jay2113** [comment]
Hi @ishansharma 👋 , thanks for raising this! I was able to reproduce the issue and marking it as a bug.

**Comment by Jay2113** [comment]
@ishansharma 👋 , we have deployed a fix for this issue and the manual workaround is no longer required. Closing this thread but feel free to reopen if you are still experiencing this issue.
