### ISSUE TITLE
Get resource's name/id/arn in lambda function

### ISSUE THREAD

**Issue by nam-truong-le** [aws-amplify/amplify-backend#2178]
### Environment information

```plain text
System:
  OS: macOS 15.1
  CPU: (8) arm64 Apple M3
  Memory: 109.86 MB / 24.00 GB
  Shell: /bin/zsh
Binaries:
  Node: 22.8.0 - ~/.nvm/versions/node/v22.8.0/bin/node
  Yarn: undefined - undefined
  npm: 10.8.2 - ~/.nvm/versions/node/v22.8.0/bin/npm
  pnpm: 9.12.3 - ~/.nvm/versions/node/v22.8.0/bin/pnpm
NPM Packages:
  @aws-amplify/auth-construct: 1.3.1
  @aws-amplify/backend: 1.5.2
  @aws-amplify/backend-auth: 1.2.0
  @aws-amplify/backend-cli: 1.3.0
  @aws-amplify/backend-data: 1.1.5
  @aws-amplify/backend-deployer: 1.1.4
  @aws-amplify/backend-function: 1.7.2
  @aws-amplify/backend-output-schemas: 1.4.0
  @aws-amplify/backend-output-storage: 1.1.2
  @aws-amplify/backend-secret: 1.1.4
  @aws-amplify/backend-storage: 1.2.1
  @aws-amplify/cli-core: 1.1.3
  @aws-amplify/client-config: 1.5.0
  @aws-amplify/deployed-backend-client: 1.4.1
  @aws-amplify/form-generator: 1.0.3
  @aws-amplify/model-generator: 1.0.8
  @aws-amplify/platform-core: 1.1.0
  @aws-amplify/plugin-types: 1.3.0
  @aws-amplify/sandbox: 1.2.2
  @aws-amplify/schema-generator: 1.2.4
  aws-amplify: 6.6.7
  aws-cdk: 2.164.1
  aws-cdk-lib: 2.158.0
  typescript: 5.6.3
AWS environment variables:
  AWS_STS_REGIONAL_ENDPOINTS = regional
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
No CDK environment variable
```

### Describe the feature

I follow this https://docs.amplify.aws/nextjs/build-a-backend/functions/grant-access-to-other-resources/#using-cdk to create resource that lambda can access to. But there is no way out of the box the know the resource's id/arn/name in the lambda. I have to create a new parameter to store the arn of the SNS topic (for example) and then in the lamda, I have to get the arn manually. It would be nice if somehow the arn is added to env in the lambda function, same as with graphql API endpoint & S3 bucket name.

### Use case

Get resources's name/id/arn in lambda function.

**Comment by ykethan** [comment]
Hey @nam-truong-le, thank you for reaching out. You should be able to use the `addEnvironment` property on the function to add a environment variable for the parameters you are looking to use in the function.

**Comment by ykethan** [comment]
Closing the issue due to inactivity. Do reach out to us if you require any assistance.
