### ISSUE TITLE
Failed to parse URL from undefinedget_page_config?page_type=home

### ISSUE THREAD

**Issue by anushkagarg56** [aws-amplify/amplify-backend#2259]
### Environment information

```plain text
TypeError: Failed to parse URL from undefinedget_page_config?page_type=home
```

### Describe the bug

Sometimes my Environment Variables not being carried over and throws this error. Have tried setting them in my next.config still the same

Any help would be highly appreciated

### Reproduction steps

when try to open the web app

**Comment by Jay2113** [comment]
@anushkagarg56 👋 , thanks for reaching out. Can you try the steps outlined [here](https://github.com/aws-amplify/amplify-backend/issues/2190#issuecomment-2455684425) to ensure the environment variables are accessible to the compute runtime?

**Comment by Jay2113** [comment]
Closing the thread as we have shared the documentation for setting up env variables for the SSR runtime.
