### ISSUE TITLE
Node 22 Support

### ISSUE THREAD

**Issue by ataylorme** [aws-amplify/amplify-backend#2268]
### Environment information

```plain text
System:
  OS: macOS 15.1.1
  CPU: (8) arm64 Apple M2
  Memory: 118.66 MB / 16.00 GB
  Shell: /bin/zsh
Binaries:
  Node: 22.9.0 - ~/.nvm/versions/node/v22.9.0/bin/node
  Yarn: undefined - undefined
  npm: 10.8.3 - ~/.nvm/versions/node/v22.9.0/bin/npm
  pnpm: undefined - undefined
```

### Describe the feature

Add support to `@aws-amplify/backend-function` for Node 22, which is a [supported Lambda runtime](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html#runtime-deprecation-levels) that was added in [`aws-cdk-lib/aws-lambda` version `2.168.0`](https://github.com/aws/aws-cdk/releases/tag/v2.168.0) on November 20th, 2024

I also suggest dropping support for Node 16 as it is a deprecated runtime.

### Use case

Node 22 is the current LTS version and I would like to use it for my Amplify functions

**Comment by josefaidt** [comment]
Hey @ataylorme :wave: thanks for raising this and taking the time to file a PR! Marking as a feature request 🙂

**Comment by ataylorme** [comment]
You are welcome. I started to drop Node 16 as well but many tests reference that version so I’ll need some help with that, perhaps as  follow up PR
