### ISSUE TITLE
Revisit `TargetLanguage` name in model-generator

### ISSUE THREAD

**Issue by dpilch** [aws-amplify/amplify-backend#247]
`TargetLanguage` is a type union of available targets for GraphQL statement generation in model-generator. The targets available for GraphQL statement generation are `'javascript'`, `'graphql'`, `'flow'`, `'typescript'`, and `'angular'`. https://github.com/aws-amplify/amplify-codegen/blob/main/packages/graphql-generator/API.md?plain=1#L61

Some of these are not languages so the name is inaccurate. Revisit this name before GA release.

**Comment by sobolk** [comment]
Let's see if we can just drop this type and use `StatementsTarget` instead see https://github.com/aws-amplify/amplify-backend/blob/40298a493099f8f085d79fdcb705dc24b15a2198/packages/model-generator/API.md?plain=1#L170 .

**Comment by ykethan** [comment]
@dpilch any update on this?

**Comment by dpilch** [comment]
I see no issue using the suggestion from @sobolk.
