### ISSUE TITLE
Revisit conversation on exposing stack outputs client

### ISSUE THREAD

**Issue by sdstolworthy** [aws-amplify/amplify-backend#267]
https://github.com/aws-amplify/samsara-cli/pull/261#discussion_r1333457152

This conversation was intentionally left unresolved to be revisited.

The PR for the comment thread introduces a utility that allows access to stack outputs.

At the time the PR was introduced, the only way to access output data conveniently was through the `client-config` package.
This effectively required all data used at runtime to be persisted in the client config file as well. Because the client config file has specific use cases for the amplify libraries, this was suboptimal.

Before release, we should revisit the exposed client in this PR and reevaluate the level of abstraction that the client operates at.

**Comment by sobolk** [comment]
We're leaving the deployed backend client api in current shape.
