### ISSUE TITLE
sandbox-created GraphQL API is created with fixed name, `amplifyData`

### ISSUE THREAD

**Issue by josefaidt** [aws-amplify/amplify-backend#277]
When I ran `npx amplify sandbox` for the first time it created the scaffolded resources, however I was expecting the GraphQL API to be named similar to the auto-generated stack name such as `<project-name>-sandbox-<whoami>-graphqlapi`. This can get confusing as multiple developers are using the same AWS account

**Comment by edwardfoyle** [comment]
We now have a `name` prop on `defineData` that can be used to specify a more identifiable name. This property can be changed at any time without recreating the API
