### ISSUE TITLE
Consider renaming `disambiguator` in UniqueBackendIdentifier

### ISSUE THREAD

**Issue by johnpc** [aws-amplify/amplify-backend#308]
See discussion here: https://github.com/aws-amplify/samsara-cli/pull/305#discussion_r1339181236

There are open questions on the naming of the `disambiguator` property in UniqueBackendIdentifier. This value could be the branchName or the literal string `sandbox`

**Comment by sobolk** [comment]
Addressed by https://github.com/aws-amplify/amplify-backend/pull/594
