### ISSUE TITLE
DeploymentType should be a required parameter

### ISSUE THREAD

**Issue by Amplifiyer** [aws-amplify/amplify-backend#358]
See https://github.com/aws-amplify/samsara-cli/pull/357#discussion_r1346259555

**Comment by sobolk** [comment]
After https://github.com/aws-amplify/amplify-backend/pull/594 it seems that deployer interface has two redundant inputs for deployment type. I.e. deployment type is now part of `BackendIdentifier` and is also present in `DeployProps` .
We should eliminate the latter.
