### ISSUE TITLE
Add e2e test that runs `pipeline-deploy` command on Amplify Hosting CI/CD

### ISSUE THREAD

**Issue by srquinn21** [aws-amplify/amplify-backend#363]
The `pipeline-deploy` command is intended specifically for Amplify Hosting CI/CD customers where the build container has specific runtime constraints controlled by the Amplify service team. Therefore, we should have at least one e2e test that covers running `pipeline-deploy` on Amplify Hosting CI/CD just like our customers would to prevent releasing new versions that don't run on the build container.

**Comment by sobolk** [comment]
This is covered by us excercising pipeline deploy command in both e2e tests and canary checks.

In addition to that we plan to cover node js versions here https://github.com/aws-amplify/amplify-backend/issues/785 which should exhaust this topic. Therefore closing this item.
