### ISSUE TITLE
Move Logger from create-amplify package into cli-core

### ISSUE THREAD

**Issue by 0618** [aws-amplify/amplify-backend#447]
Move the logger introduced in https://github.com/aws-amplify/samsara-cli/pull/413 to cli-core

See thread https://github.com/aws-amplify/samsara-cli/pull/441#discussion_r1364571393

**Comment by bombguy** [comment]
@sobolk To add verbosity level support to the Printer class, we will need to change the static class into more of singleton pattern. The Printer class is relatively new still and is not used widely, updating usage seems trivial for now. Do you see any problems with this approach?

**Comment by bombguy** [comment]
Is this issue to refactor the Printer class & remove the Logger class?

**Comment by sobolk** [comment]
@bombguy that's fine. Static instance of a class if fine.

**Comment by sobolk** [comment]
Done.
