### ISSUE TITLE
Write a script to verify if package-lock.json is updated

### ISSUE THREAD

**Issue by 0618** [aws-amplify/amplify-backend#476]
**Issue**: There's no checker for us to verify if package-lock.json is updated, so we were not able to automatically catch that changeset didn't update package-lock.json.

**Requirements**: Write a script and run as a GH PR checker to verify package-lock.json. 

Ref: https://github.com/aws-amplify/amplify-cli/blob/dev/scripts/verify-yarn-lock.sh
Related to: https://github.com/aws-amplify/samsara-cli/issues/475

**Comment by edwardfoyle** [comment]
wontfix
