### ISSUE TITLE
Write an E2E test that spins up a CDK app and runs cdk synth with Auth construct

### ISSUE THREAD

**Issue by awsluja** [aws-amplify/amplify-backend#477]
Currently we don't have e2e tests that test using the Auth construct in a standalone CDK project (outside of samsara ecosystem).
We need to add a test to ensure that we don't introduce breaking changes to CDK projects.
Error example: https://github.com/aws-amplify/samsara-cli/issues/343

Acceptance criteria:
- create a cdk app in typescript
- use Auth construct (bonus if also using Data construct) in stack
- build the cdk app
- run cdk synth
- verify that cdk synth is successful

**Comment by sobolk** [comment]
Solved in https://github.com/aws-amplify/amplify-backend/pull/810
