### ISSUE TITLE
Find a linter rule to forbid empty catch blocks.

### ISSUE THREAD

**Issue by sobolk** [aws-amplify/amplify-backend#557]
From https://github.com/aws-amplify/samsara-cli/pull/556#discussion_r1380608467 .

**Comment by edwardfoyle** [comment]
Did a little more research on this, and I'm not sure this is possible using AST selectors. The source code for the `no-empty` lint rule is [here](https://github.com/eslint/eslint/blob/main/lib/rules/no-empty.js#L72) and it's looking at the source code to determine if there are comments rather that just looking at the AST

**Comment by sobolk** [comment]
Fixed by https://github.com/aws-amplify/amplify-backend/pull/915
