### ISSUE TITLE
Use the AmplifyBackendDeployFullAccess policy in e2e tests to mirror the customer's dev environment

### ISSUE THREAD

**Issue by Amplifiyer** [aws-amplify/amplify-backend#693]
### Description

Our e2e tests are currently using a [different IAM policy](https://tiny.amazon.com/3i05wiim/IsenLink) than what we tell customers to use while using amplify-backend. We should use the same policy AmplifyBackendDeployFullAccess.

The hotswap test needs to be updated to also make every hotswappable change possible. (Currently only AppSync:Schema is tested)

**Comment by edwardfoyle** [comment]
Done in https://github.com/aws-amplify/amplify-backend/pull/768
