### ISSUE TITLE
while using Func, can't add layers and timeout

### ISSUE THREAD

**Issue by blinkdaffer** [aws-amplify/amplify-backend#772]
### Environment information

```plain text
System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 87.11 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 10.2.4 - /opt/homebrew/bin/npm
    pnpm: Not Found
    bun: Not Found
    Watchman: 2023.11.20.00 - /opt/homebrew/bin/watchman
  npmPackages:
    @aws-amplify/backend: ^0.5.5 => 0.5.5
    @aws-amplify/backend-cli: ^0.9.1 => 0.9.1
    aws-amplify: ^6.0.4 => 6.0.4
    aws-cdk: ^2.111.0 => 2.111.0
    aws-cdk-lib: ^2.110.1 => 2.110.1
    typescript: ^5.3.2 => 5.3.2
```

### Description

hello, 

Can't seem to add layers or modify the lambda timeout while adding custom business logic via Func

```
generate: a
    .mutation()
    .arguments({
      companyId: a.string(),
    })
    .returns(a.ref("GenerateResponse"))
    .authorization([a.allow.private()])
    .function("echoHandler"),
```

..........

```
  functions: {
    echoHandler: Func.fromDir({
      codePath: "./echo",
      name: "echoHandlerFunc",
    }),
  
```

I tried to reference the lambda from backend.ts, still can't access function via L1, or L2

if we use the Func, how do we modify layers, timeouts and permissions?

thanks in advance.

**Comment by ykethan** [comment]
Hey @blinkdaffer, thank you for reaching out. I was able to reproduce this, it appears the attributes are currently not exposed on the custom business logic via Func. Tried to see if we can modify the `IFunction` from the backend but doesn't appear to have an attribute. 

Marking this a feature request to enable additional attributes.

**Comment by edwardfoyle** [comment]
Hi @blinkdaffer, the functions experience is under active development right now. We have just released a change to replace the `Func.fromDir` experience with `defineFunction`. You can update your `@aws-amplify/backend` package to try it out. We haven't exposed timeout, layers, or permissions yet, but this is on our todo list.

You can use overrides to set permissions, layers, etc on the function until we support it natively:

```ts
// amplify/data/resource.ts

import { defineData, defineFunction } from '@aws-amplify/backend';
import { Function } from 'aws-cdk-lib/aws_lambda';

export const echoHandler = defineFunction({
  entry: './echo-handler.ts',
});

export const data = defineData({
  ...
  functions: {
    echoHandler
  }
})
```

```ts
// amplify/backend.ts

import { data, echoHandler } from './data/resource.ts'

const backend = defineBackend({
  data,
  echoHandler
});

const lambdaFunction = backend.resources.echoHandler.resources.lambda as Function;

lambdaFunction.addTrigger(...)
lambdaFunction.addPermission(...)
lambdaFunction.timeout = <number>
```

For more info on what's possible with custom resources and overrides, check out https://next-docs.amplify.aws/gen2/build-a-backend/add-aws-services/custom-resources/

**Comment by blinkdaffer** [comment]
thank you guys. 

P.S loving the new amplify dev experience. great job guys.

**Comment by josefaidt** [comment]
This is now possible with the `timeoutSeconds` prop :tada:

```ts
import { defineFunction } from "@aws-amplify/backend";

defineFunction({
  timeoutSeconds: 60
})
```

**Comment by edwardfoyle** [comment]
Closing as additional config options have been added to functions. We will evaluate the layers functionality moving forward
