### ISSUE TITLE
sandbox fails with stack trace if when destroying the env without cli and backend packages

### ISSUE THREAD

**Issue by ykethan** [aws-amplify/amplify-backend#830]
### Environment information

```plain text
System:
    OS: macOS 13.6.1
    CPU: (8) arm64 Apple M1
    Memory: 150.55 MB / 16.00 GB
    Shell: 3.6.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 18.18.0 - ~/.local/share/nvm/v18.18.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.8.1 - ~/.local/share/nvm/v18.18.0/bin/npm
    pnpm: 7.26.2 - /opt/homebrew/bin/pnpm
    bun: Not Found
    Watchman: Not Found
  npmPackages:
    @aws-amplify/backend: Not Found
    @aws-amplify/backend-cli: Not Found
    aws-amplify: ^6.0.7 => 6.0.7 
    aws-cdk: Not Found
    aws-cdk-lib: Not Found
    typescript: ^5.3.3 => 5.3.3
```

### Description

![image](https://github.com/aws-amplify/amplify-backend/assets/87995712/bb03f5f6-5f1c-45d2-b3d7-b386641a4d1f)

The deploy does throw an error message when starting the sandbox but fails when deleting the sandbox

reproduction:

1. `npm create amplify@latest`
2. `npm uninstall @aws-amplify/backend @aws-amplify/backend-cli`
3. `npx amplify sandbox` -> errors out and shows correct error but the `caused By` shows up as empty
4. Shutting down sandbox will fail with a generic error message `Unable to build Amplify backend. Check your backend definition in the amplify folder.` which is not helpful.

**Comment by edwardfoyle** [comment]
Why would sandbox be expected to work if you uninstall packages it depends on?

**Comment by ykethan** [comment]
@edwardfoyle was repoing a different issue, was not expecting that sandbox should work but more in terms of sandbox started even though we dont have the required packages and the sandbox exit doesnt fail gracefully

**Comment by edwardfoyle** [comment]
This error message seems pretty good? Sure there's some noise, but you removed the `@aws-amplify/backend` package and the error message says "Cannot find package @aws-amplify/backend"
