### ISSUE TITLE
Improvements to `resolve_secret_banner.ts`

### ISSUE THREAD

**Issue by rtpascual** [aws-amplify/amplify-backend#861]
From https://github.com/aws-amplify/amplify-backend/pull/845#discussion_r1440746002.

There are a couple enhancements that can be done for the `resolve secret banner` code snippet for customer lambdas:
- Multiline support for readability and inline comments (`// some comment`)
- Support for importing third party modules or other files

**Comment by edwardfoyle** [comment]
Done. There are still some possible improvements here (or different approaches we could take), but we will address those if / when future refactors of the ssm banner happen.
