### ISSUE TITLE
Need a mechanism to enforce adding helpful resolutions to customer facing errors

### ISSUE THREAD

**Issue by srquinn21** [aws-amplify/amplify-backend#873]
[`AmplifyErrorOptions`](https://github.com/aws-amplify/amplify-backend/blob/main/packages/platform-core/src/errors/amplify_error.ts#L100-L104) treats the resolution field as optional. Requiring a `resolution` to customer facing errors at the time of adding error handling allows us to prevent playing catch up in the future. Additionally, it requires contributors to think through the customer experience when an error is thrown and how/if the customer can do anything about it (hint: if they can't, this is our Fault)

**Comment by edwardfoyle** [comment]
Whoever picks this up, make the resolution field required and see what the changes look like to make TS happy. If it starts to look gross, we can reevaluate how / if we want to tackle this.
