### ISSUE TITLE
Error: "Dynamic require of \"buffer\" is not supported" in AppSyncResolverHandler

### ISSUE THREAD

**Issue by mujabmuneeb** [aws-amplify/amplify-backend#920]
### Environment information

```plain text
System:
    OS: macOS 13.4.1
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 30.29 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.19.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.8.0 - /usr/local/bin/pnpm
    bun: Not Found
    Watchman: 2023.07.10.00 - /usr/local/bin/watchman
  npmPackages:
    @aws-amplify/backend: Not Found
    @aws-amplify/backend-cli: Not Found
    aws-amplify: Not Found
    aws-cdk: Not Found
    aws-cdk-lib: Not Found
    typescript: Not Found
```

### Description

Trying to call existing queries/mutations inside new custom mutation but unable to do so. 

```
import type { AppSyncResolverHandler } from 'aws-lambda'; // types imported from @types/aws-lambda
import { callEcho } from '../api';
import {Buffer} from 'buffer'

type ResolverArgs = { email: string, password: string, first: string, last: string, organization: string };

type ResolverResult = { organizationId: string, ownerId: string};

export const handler: AppSyncResolverHandler<
  ResolverArgs,
  ResolverResult
> = async (event, context) => {

  await callEcho()
  
  return {
    organizationId: 'abcd',
    ownerId: '123',
  };
};
```

**Comment by josefaidt** [comment]
Hey @mujabmuneeb :wave: thanks for raising this! What is the full error message and stack trace you're receiving?

**Comment by josefaidt** [comment]
Hey @mujabmuneeb thanks for the clarification! This issue typically arises when attempting to ship ESM with CJS dependencies. Building with `esbuild` you can customize a "banner" prop to inject some code into the final bundle, like:

```js
import { createRequire } from 'module';const require = createRequire(import.meta.url);
```

Or, change the output format to CJS, however `bundling` is not yet surfaced to `defineFunction` (I'll file a separate issue for tracking) https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_lambda_nodejs.NodejsFunction.html#bundling

**Comment by jbp35** [comment]
> Hey @mujabmuneeb thanks for the clarification! This issue typically arises when attempting to ship ESM with CJS dependencies. Building with `esbuild` you can customize a "banner" prop to inject some code into the final bundle, like:
> 
> ```js
> import { createRequire } from 'module';const require = createRequire(import.meta.url);
> ```
> 
> Or, change the output format to CJS, however `bundling` is not yet surfaced to `defineFunction` (I'll file a separate issue for tracking) https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_lambda_nodejs.NodejsFunction.html#bundling

I'm facing the same issue when using qdrant-js client in a function. Will this be addressed using defineFunction or should I implement a custom CDK function?

**Comment by josefaidt** [comment]
Hey @mujabmuneeb and @jbp35 this should now be resolved with [@aws-amplify/backend@0.10.3](https://github.com/aws-amplify/amplify-backend/releases/tag/%40aws-amplify%2Fbackend%400.10.3). Can y'all try upgrading and see if you're still experiencing this?

**Comment by erickriva** [comment]
I can confirm it was fixed. Tested right now.

**Comment by jbp35** [comment]
It's working for me as well.

**Comment by josefaidt** [comment]
Awesome, thanks for confirming @erickriva and @jbp35 ! Closing 🙂
