### ISSUE TITLE
Improve error message of missing CDK bootstrap resources

### ISSUE THREAD

**Issue by kgopelo-dot** [aws-amplify/amplify-backend#921]
### Environment information

```plain text
null
```

### Description

AmplifyGen2 uses a one-time bootstrap setup for account and region before it can start deploying resources per docs. However, if one of the deployed resources are removed e.g `cdk-hnb659fds-deploy-role-XXX-us-west-2`, AmplifyGen2 cannot detect and the application will not deploy and fail with error:

```
This CDK deployment requires bootstrap stack version '6', but during the confirmation via SSM parameter /cdk-bootstrap/hnb659fds/version the following error occurred: AccessDeniedException
```

Steps to reproduce:

1. Run `npx amplify sandbox` on new region.
2. Wait for one time bootstrapping  and deploy application.
3. Remove `CDKToolkit` resources e.g `cdk-hnb659fds-deploy-role-XXXXX-us-west-2`
4. Try to deploy again.

**Comment by ykethan** [comment]
Hey @kgopelo-dot, thank you for reaching out. The issue appears to be similar to https://github.com/aws/aws-cdk/issues/17942, the comment [here](https://github.com/aws/aws-cdk/issues/17942#issuecomment-992295898) further explains the working. In this case as the CDK toolkit was removed we should be able to run `cdk bootstrap` and update the toolkit.
Marking this as feature-request to update the error message and consider auto-upgrading the tool kit versions.

**Comment by Milan-Shah** [comment]
We are working on enhancing the experience for Bootstrap experience in Console, specifically addressing the issue you called out above. It is code complete, we are in the testing phase and will update the this ticket once our changes are deployed in production.

**Comment by Milan-Shah** [comment]
This issue has been fixed and rolled out to all regions. If you are still having any issues, please let us know.
