### ISSUE TITLE
`pipeline-deploy` error map

### ISSUE THREAD

**Issue by 0618** [aws-amplify/amplify-backend#922]
### Environment information

```plain text
System:
    OS: macOS 13.6.3
    CPU: (12) arm64 Apple M2 Pro
    Memory: 201.81 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    Yarn: 1.22.21 - ~/.nvm/versions/node/v20.10.0/bin/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
    pnpm: 8.11.0 - ~/.nvm/versions/node/v20.10.0/bin/pnpm
    bun: 1.0.6 - ~/.bun/bin/bun
    Watchman: Not Found
  npmPackages:
    @aws-amplify/backend: Not Found
    @aws-amplify/backend-cli: Not Found
    aws-amplify: Not Found
    aws-cdk: Not Found
    aws-cdk-lib: Not Found
    typescript: Not Found
```

### Description

When running `npx amplify pipeline-deploy --branch $AWS_BRANCH --app-id $AWS_APP_ID`, if there's an error, we should get a very generic error message:

> BackendBuildError: Unable to build Amplify backend. Check your backend definition in the `amplify` folder.

We need to manually modify https://github.com/aws-amplify/amplify-backend/blob/149e3b3633f6373e8121fa3a0d49ca88265ceb39/packages/backend-deployer/src/cdk_error_mapper.ts#L118 to see the original error.

As an Amplify user, I want to see the original error log when running `pipeline-deploy`.

**Comment by ykethan** [comment]
Marking as feature-request error message improvements. 
related issues: https://github.com/aws-amplify/amplify-backend/issues/914
