### ISSUE TITLE
npx amplify sandbox fails for auth with domainPrefix

### ISSUE THREAD

**Issue by lazpavel** [aws-amplify/amplify-backend#930]
### Environment information

```plain text
System:
    OS: Linux 6.7 Arch Linux
    CPU: (24) x64 12th Gen Intel(R) Core(TM) i9-12900HX
    Memory: 112.41 GB / 125.50 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
    Yarn: 1.22.21 - /usr/bin/yarn
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.2/bin/npm
    pnpm: 8.14.1 - ~/.local/share/pnpm/pnpm
    bun: Not Found
    Watchman: Not Found
  npmPackages:
    @aws-amplify/backend: ^0.10.1 => 0.10.1 
    @aws-amplify/backend-cli: ^0.9.6 => 0.9.6 
    aws-amplify: ^6.0.12 => 6.0.12 
    aws-cdk: ^2.121.1 => 2.121.1 
    aws-cdk-lib: ^2.121.1 => 2.121.1 
    typescript: ^5.2.0 => 5.3.3 
```

### Description

When creating an auth resource with social providers and domainPrefix, `npx amplify sandbox` will fail if the changes are pushed in and deployed as it will try to reuse the same cognito domain for main environment user pool and sandbox user pool.

```
Domain already associated with another user pool. (Service: AWSCognitoIdentityProviderService; Status Code: 400; Error Code: InvalidParameterException; Request ID: f59cb18f-9520-4900-86f0-1e0f52f6a3c9; Proxy: null)
```

```
export const auth = defineAuth({
  loginWith: {
    email: true,
    externalProviders: {
      domainPrefix: 'foo-bar',
      ....
    }
  }
}
```
      
https://github.com/aws-amplify/amplify-backend/blob/main/packages/auth-construct/src/construct.ts#L828-L830

**Comment by edwardfoyle** [comment]
This is expected behavior. You'll need to configure the domainPrefix using an environment variable so that it can be adjusted in different environments. eg

```ts
export const auth = defineAuth({
  loginWith: {
    email: true,
    externalProviders: {
      domainPrefix: process.env.AUTH_DOMAIN,
      ....
    }
  }
}
```

**Comment by lazpavel** [comment]
Following the instructions here: https://docs.amplify.aws/gen2/deploy-and-host/fullstack-branching/secrets-and-vars/#access-environment-variables

Looks that env variables are not getting picked up: tested in branch with `.env` and in sandbox with `.env.local` files

**Comment by lazpavel** [comment]
I was able to bypass this by using `dotenv` and load the configuration with some preBuild scripts to populate the right env variables for sandbox vs main branch, closing the ticket
