### ISSUE TITLE
support for custom domains

### ISSUE THREAD

**Issue by chrisbonifacio** [aws-amplify/amplify-backend#954]
### Environment information

```plain text
N/A
```

### Description

I would like to be able to deploy my Gen 2 application to a custom domain

**Comment by exai-sukh** [comment]
The Amplify Console UI shows it's coming soon
![Screen Shot 2024-01-29 at 9 39 25 AM](https://github.com/aws-amplify/amplify-backend/assets/115499566/baf80edf-12ec-49d7-82a5-bfdf450fd021)

It would be great if there's a CDK-based solution for this as a workaround.

**Comment by blinkdaffer** [comment]
you can use 

aws amplify create-domain-association --app-id <VALUE> --domain-name <VALUE> --sub-domain-settings prefix=<VALUE>,branchName=<VALUE>

**Comment by ekpono-globalvoices** [comment]
Command to get your app-id `aws amplify list-apps`

Command to create custom domain
`aws amplify create-domain-association --app-id=d1b61z****l79 --domain-name=example.co.uk --sub-domain-settings prefix=,branchName=main`

**Comment by Jay2113** [comment]
Custom domain support for Amplify Gen 2 apps is currently in development and is not available as part of the preview. That being said, as stated in this thread you can add custom domains to your Gen 2 apps using the AWS CLI/API/SDK.

To add a custom domain, you can use the [create-domain-association](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/amplify/create-domain-association.html) API: 
```
aws amplify create-domain-association --app-id <VALUE> --domain-name <VALUE> --sub-domain-settings prefix=<VALUE>,branchName=<VALUE>
```

To retrieve the required dns records, you can use the [get-domain-association](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/amplify/get-domain-association.html) API: 
```
aws amplify get-domain-association --app-id <VALUE> --domain-name <VALUE> 
```

Also, you can add [wildcard subdomains](https://docs.aws.amazon.com/amplify/latest/userguide/wildcard-subdomain-support.html) on the app by modifying the `prefix` attribute as follows:
```
aws amplify create-domain-association --app-id <VALUE> --domain-name <VALUE> --sub-domain-settings prefix=\*,branchName=<VALUE>
```

**Comment by Milan-Shah** [comment]
As @Jay2113 called out, Custom domain support in Gen2 is work in progress. We will update this ticket in next few weeks as soon as its released in production. Stay tuned!

**Comment by rajeshrah22** [comment]
Will be waiting 😏

**Comment by ayepRahman** [comment]
Can't wait for GA. Any tentative date for GA?

**Comment by CGarces** [comment]
Any one knows if works for wildcard subdomains?

I have tested with the SDK

         {"prefix": "*", "branchName": "test"},
         {"prefix": "foo", "branchName": "test"},
         {"prefix": "bar", "branchName": "test"},


foo.domain.com and bar.domain.com works fine.
But another.domain.com not.

I have check the DNS propagation and the route53 configuration and looks fine.
The certificate is owned by ACM and looks fine also.

**Comment by PlayApple** [comment]
> As @Jay2113 called out, Custom domain support in Gen2 is work in progress. We will update this ticket in next few weeks as soon as its released in production. Stay tuned!
@Milan-Shah What is the approximate release time? I am also trying to deploy my new project with Gen 2, looking forward to the official release.

**Comment by elad-maimon** [comment]
THanks @Jay2113 !

How can I create a domain association for the domain apex?

**Comment by imana97** [comment]
any news?

**Comment by dr-star** [comment]
I share my code to create the association via CDK. Maybe it can be helpful for someone who wants to keep tracks
```
import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
import { aws_amplify as amplify } from 'aws-cdk-lib';

export class AmplifyDomainStack extends cdk.Stack {
    constructor(scope: Construct, id: string, props?: cdk.StackProps) {
        super(scope, id, props);

        const cfnDomain = new amplify.CfnDomain(this, 'WebsiteAmplifyCfnDomain', {
            appId: 'your-app-id',
            domainName: 'domain.com',
            subDomainSettings: [{
                branchName: 'main',
                prefix: '',
            }],
        });
    }
}
```

**Comment by jFensch** [comment]
We are getting a 404 accessing our custom domain after creating the association via CDK.  The response headers include

`X-Cache: Error from cloudfront`

**Comment by ideen1** [comment]
Custom domain feature seems to be live on the console.

**Comment by rosswickman** [comment]
> Custom domain feature seems to be live on the console.

@ideen1 What region? Is it for new or existing deployment?
I'm still seeing 'Coming Soon'

**Comment by ideen1** [comment]
@rosswickman Oh that is interesting. It may be a gradual rollout. I am seeing this in ca-central-1 on an existing app.

**Comment by rosswickman** [comment]
@ideen1 I have it now!!!

**Comment by swaminator** [comment]
This is now available.

**Comment by vaughngit** [comment]
Can you provide an example of how to do it via the native amplify CDK
