### ISSUE TITLE
Create a `printer` type in `plugin/types`

### ISSUE THREAD

**Issue by 0618** [aws-amplify/amplify-backend#958]
### Environment information

```plain text
n/a
```

### Description

As suggested in comment https://github.com/aws-amplify/amplify-backend/pull/947#discussion_r1471731673

We need to create a type for `printer` in `plugin/types` package.

**Comment by edwardfoyle** [comment]
This task should also include replacing the printer instances [here](https://github.com/aws-amplify/amplify-backend/blob/main/packages/cli/src/printer.ts) and [here](https://github.com/aws-amplify/amplify-backend/blob/main/packages/create-amplify/src/printer.ts) with the newly exported instance in `cli-core`

**Comment by edwardfoyle** [comment]
This is related / duplicate of https://github.com/aws-amplify/amplify-backend/issues/948
