### ISSUE TITLE
detect Package Manager using the file structure

### ISSUE THREAD

**Issue by 0618** [aws-amplify/amplify-backend#959]
### Environment information

```plain text
n/a
```

### Description

We detect what package manager the user uses via `npm_config_user_agent`. The user could use package manager A's command in a project which uses project manager B.

So we need to detect what package manager to use via the file structure. e.g., the lock file.

**Comment by edwardfoyle** [comment]
>The user could use package manager A's command in a project which uses project manager B.

Why do we need to support such a case?

**Comment by josefaidt** [comment]
This should only occur when executing the create-amplify bin directly with node. In a monorepo the lockfile is not typically located in the package's directory, which can make this tedious to look for

**Comment by josefaidt** [comment]
related to https://github.com/aws-amplify/amplify-backend/issues/983

**Comment by ykethan** [comment]
Closing as this is an unsupported use case
