### ISSUE TITLE
`attributeMapping` definition is getting ignored

### ISSUE THREAD

**Issue by lazpavel** [aws-amplify/amplify-backend#963]
### Environment information

```plain text
 System:
    OS: Linux 6.7 Arch Linux
    CPU: (24) x64 12th Gen Intel(R) Core(TM) i9-12900HX
    Memory: 112.74 GB / 125.50 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
    Yarn: 1.22.21 - /usr/bin/yarn
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.2/bin/npm
    pnpm: 8.14.3 - ~/.local/share/pnpm/pnpm
    bun: Not Found
    Watchman: Not Found
  npmPackages:
    @aws-amplify/backend: ^0.10.3 => 0.10.3 
    @aws-amplify/backend-cli: ^0.9.7 => 0.9.7 
    aws-amplify: ^6.0.13 => 6.0.13 
    aws-cdk: ^2.124.0 => 2.124.0 
    aws-cdk-lib: ^2.124.0 => 2.124.0 
    typescript: ^5.3.3 => 5.3.3
```

### Description

I am getting an error when deploying an app with attribute mapping and required fields:
```
The attribute mapping is missing required attributes [given_name, family_name] 
```

```
loginWith: {
  email: true,
  externalProviders: {
    google: {
      scopes: ['profile', 'email'],
      attributeMapping: {
        email: ProviderAttribute.GOOGLE_EMAIL,
        givenName: ProviderAttribute.GOOGLE_GIVEN_NAME,
        familyName: ProviderAttribute.GOOGLE_FAMILY_NAME,
      },
    },
  }
}
```

Changes introduced in this PR will ignore the mapping definition on login with email:
https://github.com/aws-amplify/amplify-backend/pull/931/files#diff-6abc24a79f5c544d266b3ebb39922b8e78536435bf71d43710019518e4ec854fR610-R617

**Comment by awsluja** [comment]
I believe you are missing the standard attributes for given_name and family_name:
`userAttributes: {
          givenName: { mutable: true, required: true },
          familyName: { mutable: true, required: true }
        }`

**Comment by lazpavel** [comment]
Discussed offline, this is not the case as the full defineAuth does have the user attributes set

**Comment by awsluja** [comment]
I've reproduced this issue on my machine, and found an issue with missing parenthesis around ?? and ternary operators

**Comment by ykethan** [comment]
Tested this in on beta which works as expected, closing this issue.

```
    "@aws-amplify/backend": "^0.13.0-beta.3",
    "@aws-amplify/backend-cli": "^0.12.0-beta.3",
```
