### ISSUE TITLE
config generation doesn't work with region env vars.

### ISSUE THREAD

**Issue by sobolk** [aws-amplify/amplify-backend#965]
### Environment information

```plain text
n/a
```

### Description

Repro:
```
mkdir testapp003
cd testapp003
# have default profile point to us-west-2
export AWS_DEFAULT_REGION=us-east-1
npm create amplify@latest
npx amplify sandbox
```

Error:
```
...
<deployment logs>
...
Stack ARN:
arn:aws:cloudformation:us-east-1:REDACTED:stack/amplify-testapp003-sobkamil-sandbox-075de243a0/2fd7c930-c058-11ee-a5f6-0e971123b7c5

✨  Total time: 304.5s


[Sandbox] Watching for file changes...
Amplify configuration could not be generated.Stack with id amplify-testapp003-sobkamil-sandbox-075de243a0 does not exist
```

**Comment by sobolk** [comment]
It seems that `AWS_REGION` is supported variable.
I.e. setting `AWS_REGION=us-east-1` makes above repo work.
https://stackoverflow.com/questions/59961939/what-is-the-difference-between-aws-default-region-and-aws-region-system-variable

**Comment by sobolk** [comment]
CDK seems to be handling that here https://github.com/aws/aws-cdk/blob/5a68f59b9b7313697145095819a0e65ede7b3ce2/packages/aws-cdk/lib/api/aws-auth/awscli-compatible.ts#L99

**Comment by sobolk** [comment]
Another note:
CDK seems to accept a variety of legacy env vars here https://github.com/aws/aws-cdk/blob/5a68f59b9b7313697145095819a0e65ede7b3ce2/packages/aws-cdk/lib/api/aws-auth/awscli-compatible.ts#L113-L114 .
Perhaps we should filter them when we spawn cdk cli process and allow recommended set.

**Comment by edwardfoyle** [comment]
When we solve this, we need to make sure that `amplify sandbox secret` CRUDL commands use the same resolution logic. See #973

**Comment by atierian** [comment]
Adding some details on what I encountered in case it helps:
```
> cat ~/.aws/config | grep -A 2 default
[default]
output = json
region = us-east-2

> echo $AWS_DEFAULT_REGION
us-east-2

> echo $AWS_REGION
```
Matching regions also resulted in the same error.

Setting `AWS_REGION` and re-invoking `npx amplify sandbox` resolved the issue for me.

**Comment by srquinn21** [comment]
The [AWS SDK for Javascript v3 only respects `AWS_REGION`](https://github.com/aws/aws-sdk-js-v3/blob/bff1afc54ad304b08525a342190bca43145d401d/packages/region-config-resolver/src/regionConfig/config.ts#L6) and not `AWS_DEFAULT_REGION` which is legacy CLI v1 cruft. As @sobolk pointed out, the CDK has a compatibility adapter where they respect the same env variables as the CLI as well as the SDK. Therefore, when the env variable `AWS_DEFAULT_REGION` is used, only the CDK deployment picks it up but not the AWS SDK resulting in the failure to call CFN `DescribeStack`.

Options:
* Throw when `AWS_DEFAULT_REGION` is used and have customer update to using `AWS_REGION`
* Normalize `AWS_DEFAULT_REGION` to `AWS_REGION`

**Comment by josefaidt** [comment]
> Normalize to `AWS_REGION` when `AWS_DEFAULT_REGION` is passed. We'd probably also want to consider normalizing `AWS_DEFAULT_PROFILE` when used.

I like this option -- to resolve the region similar to CDK
