### ISSUE TITLE
Set Sandbox Secrets ignores AWS_DEFAULT_REGION environment variable

### ISSUE THREAD

**Issue by bsmitches** [aws-amplify/amplify-backend#973]
### Environment information

```plain text
System:
    OS: macOS 13.5
    CPU: (8) arm64 Apple M1
    Memory: 82.25 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 10.2.4 - /opt/homebrew/bin/npm
    pnpm: Not Found
    bun: Not Found
    Watchman: Not Found
  npmPackages:
    @aws-amplify/backend: ^0.10.2 => 0.10.2 
    @aws-amplify/backend-cli: ^0.9.7 => 0.9.7 
    aws-amplify: ^6.0.13 => 6.0.13 
    aws-cdk: ^2.122.0 => 2.122.0 
    aws-cdk-lib: ^2.122.0 => 2.122.0 
    typescript: ^5.3.3 => 5.3.3
```

### Description

I use `us-east-1` for my workloads (defined in my AWS Profile or environment variables). When using `npx amplify sandbox secret set <name>`, these secrets are always put in `us-west-2`, resulting in an error when running `npx amplify sandbox` (as CloudFormation can't resolve secret from `import { secret } from '@aws-amplify/backend';`)

## Replication steps

1. `export AWS_DEFAULT_REGION=us-east-1`
2. `npx amplify sandbox secret set foo`
```
? Enter secret value
```
3. `npx amplify sandbox secret get foo`
```
 name: foo
 version: 1
 value: bar
 lastUpdated: Thu Feb 01 2024 14:56:42 GMT-0600 (Central Standard Time)`
```
4. `aws ssm describe-parameters --query "Parameters[].Name" `
```
[
    "/cdk-bootstrap/hnb659fds/version"
]
```
5. `aws ssm describe-parameters --query "Parameters[].Name" --region us-west-2`
```
[
    "/amplify/mmgen2/smitheit-sandbox-4d6faf4bcc/foo",
    "/cdk-bootstrap/hnb659fds/version"
]
```
6. `npx amplify sandbox` will fail with below error
```
Received response status [FAILED] from custom resource. Message returned: Failed to retrieve backend secret 'foo' for 'mm-gen2'. Reason: {"cause":{"name":"ParameterNotFound","$fault":"client","$metadata":{"httpStatusCode":400,"requestId":"fa745e1e-b19a-4e4c-8f06-c43829be7b73","attempts":1,"totalRetryDelay":0},"__type":"ParameterNotFound","message":"UnknownError"},"httpStatusCode":400,"name":"SecretError"} Logs: /aws/lambda/amplify-mmgen2-smitheit-s-SecretFetcherResourcePro-XbjeyifsPDff at handleCreateUpdateEvent (/var/task/index.js:5810:13) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async Runtime.handler (/var/task/index.js:5770:17) (RequestId: 8a41af80-8754-48e2-b021-935cf846a207)
```

**Comment by edwardfoyle** [comment]
Thanks for reporting this. I believe this is the same as (or very similar to) https://github.com/aws-amplify/amplify-backend/issues/965

**Comment by edwardfoyle** [comment]
I left a comment on that other issue to also note that we need to use the same env var resolution for `amplify sandbox secret` commands. Closing this issue in favor of that one.
