### ISSUE TITLE
improve separation of sandboxes (same project name causes updates to existing stack)

### ISSUE THREAD

**Issue by josefaidt** [aws-amplify/amplify-backend#980]
### Environment information

```plain text
System:
    OS: macOS 14.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 266.75 MB / 32.00 GB
    Shell: 3.7.0 - /opt/homebrew/bin/fish
  Binaries:
    Node: 18.10.0 - ~/Library/Caches/fnm_multishells/77574_1680319338649/bin/node
    Yarn: 1.22.19 - ~/Library/Caches/fnm_multishells/77574_1680319338649/bin/yarn
    npm: 8.19.2 - ~/Library/Caches/fnm_multishells/77574_1680319338649/bin/npm
    pnpm: 8.14.3 - ~/Library/Caches/fnm_multishells/77574_1680319338649/bin/pnpm
    bun: 1.0.21 - ~/.bun/bin/bun
    Watchman: Not Found
  npmPackages:
    @aws-amplify/backend: ^0.10.3 => 0.10.3 
    @aws-amplify/backend-cli: ^0.10.0 => 0.10.0 
    aws-amplify: ^6.0.13 => 6.0.13 
    aws-cdk: ^2.124.0 => 2.124.0 
    aws-cdk-lib: ^2.124.0 => 2.124.0 
    typescript: ^5.3.3 => 5.3.3
```

### Description

1. create a project in a directory called "backend" `npm create amplify@latest`
2. run `amplify sandbox` to deploy first sandbox
3. ctrl+c to exit but do not delete
4. move to a sibling directory and create a subdirectory named "backend"
5. create a second project with `npm create amplify@latest`
6. run `amplify sandbox`
7. observe CLI attempts to update existing sandbox stack

This issue occurs particularly when you are working with multiple Amplify apps locally, and/or using monorepos with the same package names.

**Comment by Amplifiyer** [comment]
This will be an issue even without the second project in sibling directory. If the packageJson.name is same, it will "connect" to the same sandbox. Relevant code here that shows the sandbox name is deterministically derived from name(`packageJson`) and namespace(`whoami`) https://github.com/aws-amplify/amplify-backend/blob/85e953f43cf89b44f8e6dfeb98c3b7eb15ce478e/packages/platform-core/src/backend_identifier_conversions.ts#L50-L71

Note that this won't be an issue for production as the name is disambiguated by the AppId in the Amplify console.

**Comment by josefaidt** [comment]
For this we can add a message at the beginning of sandbox

```
> npx amplify sandbox

  Starting sandbox for my-amplify-gen2-app
  To specify a different name, use —-name

[sandbox] synthesized...
[sandbox] ...
```
