### ISSUE TITLE
Amplify gen2 - Use same sandbox on multiple dev environments

### ISSUE THREAD

**Issue by jbp35** [aws-amplify/amplify-backend#986]
### Environment information

```plain text
System:
    OS: Windows 11 10.0.22000
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 2.68 GB / 15.73 GB
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: Not Found
    bun: Not Found
    Watchman: Not Found
  npmPackages:
    @aws-amplify/backend: ^0.10.3 => 0.10.3
    @aws-amplify/backend-cli: ^0.9.6 => 0.9.7
    aws-amplify: ^6.0.12 => 6.0.13
    aws-cdk: Not Found
    aws-cdk-lib: Not Found
    typescript: ^5.3.3 => 5.3.3
```

### Description

I would like to use the same sandbox on two different computers but 'npx amplify sandbox' creates a new sandbox for the second dev environnement.

The project name is the same. Howover, the `$(whoami)` part of the name of the sandbox is not the same (`amplify-<app-name>-$(whoami)-sandbox`)

**Comment by edwardfoyle** [comment]
Hi @jbp35, you can use `npx amplify sandbox --name <some name>` to substitute a value for $whoami. If you use the same `--name` arg across multiple machines, sandbox will deploy to the same stack.

**Comment by jbp35** [comment]
> Hi @jbp35, you can use `npx amplify sandbox --name <some name>` to substitute a value for $whoami. If you use the same `--name` arg across multiple machines, sandbox will deploy to the same stack.

Thanks, confirming it's working.

**Comment by rahulretnan** [comment]
Try this it worked for me

`--identifier `(string) - An optional name to distinguish between different sandbox

`npx amplify sandbox --identifier <some name>`

**Comment by DSep** [comment]
This does not work for me. 

The pattern is now: `amplify-<project>-<identifier>-sandbox-<hash>`

The hash at the end of the stack is not controllable, and thus changes depending on the machine. Is this intentional? Or is it a known issue that maybe I've missed in my search across issues and other amplify repos?
