### ISSUE TITLE
CORS issues with Storage

### ISSUE THREAD

**Issue by mapsi** [aws-amplify/amplify-backend#992]
### Environment information

```plain text
System:
    OS: macOS 14.3
    CPU: (11) arm64 Apple M3 Pro
    Memory: 124.06 MB / 18.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.0 - /opt/homebrew/opt/nvm/versions/node/v20.11.0/bin/node
    Yarn: Not Found
    npm: 10.2.4 - /opt/homebrew/opt/nvm/versions/node/v20.11.0/bin/npm
    pnpm: 8.12.0 - /opt/homebrew/bin/pnpm
    bun: Not Found
    Watchman: Not Found
  npmPackages:
    @aws-amplify/backend: ^0.10.3 => 0.10.3 
    @aws-amplify/backend-cli: ^0.10.0 => 0.10.0 
    aws-amplify: ^6.0.13 => 6.0.13 
    aws-cdk: ^2.124.0 => 2.126.0 
    aws-cdk-lib: ^2.124.0 => 2.126.0 
    typescript: ^5.3.3 => 5.3.3
```

### Description

Hello there 👋 

I need to add a bucket to upload... stuff. 🙂

So I did the following based on some well hidden documentation:

```
// amplify/storage/resource.ts
import { defineStorage } from "@aws-amplify/backend";

export const storage = defineStorage({});
```

```
// amplify/backend.ts
import { auth } from "./auth/resource";
import { data } from "./data/resource";
import { storage } from "./storage/resource";

const backend = defineBackend({
  auth,
  data,
  storage,
});
```

It felt awesome cos then I thought I could just use...
```
import { uploadData } from "aws-amplify/storage";

uploadData({
        key: `uploads/${file.id}`,
        data: file,
        options: {
          accessLevel: "private",
          onProgress: ({ transferredBytes, totalBytes }) => {
            if (totalBytes) {
              console.log(`Upload progress ${Math.round(transferredBytes / totalBytes) * 100} %`);
            }
          },
        },
      });
```

However this give a CORS issue.

Then I thought, I'll just create a new bucket and scrap the defineStorage option as shown above.

So based on the documentation found: https://docs.amplify.aws/gen2/build-a-backend/storage/
I did this ⤵️

```
const bucketStack = backend.createStack("BucketStack");
const bucket = new Bucket(bucketStack, "Bucket", {
  blockPublicAccess: BlockPublicAccess.BLOCK_ALL,
  lifecycleRules: [
    {
      id: "Delete incomplete multi-part uploads after 7 days",
      prefix: "",
      abortIncompleteMultipartUploadAfter: Duration.days(7),
      enabled: true,
    },
  ],
  removalPolicy: RemovalPolicy.DESTROY,
  cors: [
    {
      allowedHeaders: ["*"],
      allowedMethods: [HttpMethods.GET, HttpMethods.HEAD, HttpMethods.PUT, HttpMethods.POST, HttpMethods.DELETE],
      allowedOrigins: ["*"],
      exposedHeaders: ["x-amz-server-side-encryption", "x-amz-request-id", "x-amz-id-2", "ETag", "x-amz-meta-foo"],
      maxAge: 3000,
    },
  ],
});

// allow any authenticated user to read and write to the bucket
const authRole = backend.auth.resources.authenticatedUserIamRole;
bucket.grantReadWrite(authRole);
```

However, I no longer have access to the uploadData function as I'm getting a "bucket not found" issue and I don't know how I can configure this.

Then, I went back to the original attempt and realised that I cannot just modify the bucket created by `defineStorage` due to:
https://github.com/aws/aws-cdk/discussions/23184

So this _issue_ is a multifaceted one, it relates to documentation and lack of configuration options in defineStorage.
But I think it's pretty bad, it might have been better to say "look, storage is not available yet" rather than having this very limited version. 😞

**Comment by DominikXpertSource** [comment]
Seems issue here :)

**Comment by amineelmoussafer** [comment]
Seems issue here ! :)

**Comment by mapsi** [comment]
Thanks!

It did and now I'm getting a 403.

I added this ⤵️ hoping to fix this but I have the impression that this is the wrong approach and I need to add a _policy_ so that the authenticated users can add their files, is this right?
```
cfnBucket.addPropertyOverride("OwnershipControls", {
  Rules: [
    {
      ObjectOwnership: "ObjectWriter",
    },
  ],
});
```

**Comment by ykethan** [comment]
Hey, thank you for filing this issue. The `defineStorage` is currently still in works and the API shape is subject to change. Marking this as feature-request.
