### ISSUE TITLE
Export Stack output to amplifyconfiguration.json

### ISSUE THREAD

**Issue by malaquf** [aws-amplify/amplify-backend#998]
### Environment information

```plain text
System:
    OS: macOS 13.2
    CPU: (10) arm64 Apple M1 Max
    Memory: 16.72 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 21.6.0 - /opt/homebrew/bin/node
    Yarn: Not Found
    npm: 10.2.4 - /opt/homebrew/bin/npm
    pnpm: 8.14.1 - /opt/homebrew/bin/pnpm
    bun: Not Found
    Watchman: Not Found
  npmPackages:
    @aws-amplify/backend: ^0.10.3 => 0.10.3 
    @aws-amplify/backend-cli: ^0.10.0 => 0.10.0 
    aws-amplify: Not Found
    aws-cdk: Not Found
    aws-cdk-lib: ^2.126.0 => 2.126.0 
    typescript: ^5.3.3 => 5.3.3
```

### Description

Hello,

I believe the idea of amplifyconfiguration.json is to gather all environment related configuration generated by the backend in one place, and that's great. There are cases however that we must extend the resources using cdk stacks, and it would be very useful we can add information to the generated file based on CfnOutputs.

Example:
For long running queries, we must create alternative solutions using load balancer and lambdas, for example. As those resources will be created in sandbox environments with different aws domains by default, it would be very useful to have these domains exported in the generated amplifyconfiguration.json for reusing in the frontends.

**Comment by ykethan** [comment]
Hey @malaquf, the latest version of the backend-cli: 0.11.0 should now support adding custom outputs to the `amplifyconfiguration.json`. PR that adds this [functionality](https://github.com/aws-amplify/amplify-backend/pull/978).
We are currently working on adding this information to the documentation.

**Comment by malaquf** [comment]
Glad to see it @ykethan! Thank you.

**Comment by ykethan** [comment]
Closing this issue as we are tracking this on https://github.com/aws-amplify/amplify-backend/issues/841
